### ISSUE TITLE
[Investigation] Production errors - Large files

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#1009]
### Context
Over the past few months, we have made a strategic decision not to address some production issues regarding larger file sizes. The LOE of effort was deemed not worth the additional effort. However, talking with Jessie (the head of Board FOIA) and people at RMC, they are noticing a "trend of eFolder express errors".  

### Product concerns
There have been a rise of issues across our user group for larger files. The product concerns are as followed:

- Users are choosing to use VBMS for those who have a large number of files and some are just sticking with VBMS. 
   - I understand that it is a user choice, however, it is a choice from direct consequence of not fixing a known bug. 
- Maintenance and scalability concerns
   - Can we truly say eFolder Express is in maintenance, without fixing a known bug? Why/ 
- Under reporting
   - Following up with a few users, they have just opted to using VBMS and the issues we do have can be under reported. 

### Potential solutions
- We continue to ignore this and tell users to use VBMS despite the above risks. If this is our definitive decision, I want it to be very deliberate. 
  - We set a specific threshold where we start looking into this engineering side or when it is worth it
  - A clear support resolution path 

- We tackle this from an engineering perspective as part of the work  being done to clean up the code and errors that rockstar Nemo is doing now

- We tackle errored downloads on a case by case basis. As in resetting these downloads and looking as to why they are not working. 

### Past engineering work
- From engineering work with amazing Lowell, he found that they were errors and a pattern after a file size hit a certain number of downloads.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
