### ISSUE TITLE
Connection issues and empty downloads

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#1010]
### Context
We had about 5 to 7 tickets come in over the past few days. The end zip file is empty. See steps below. Re-tried after the outage that occurred. I am hoping that these just need to be cleared and restarted. 

### Reproduction
1.) Search Veteran ID
2. ) The retrieving page is skipped and goes straight to the success page
3.) Clicking download efolder on success page either renders an empty zip file or the connection is interrupted

### Affected manifest id's
30380
1454
35443

(waiting on 3 more Veteran ID's and will post the manifest id's)

**Comment by Chingujo** [comment]
@nemodjuric 

Feel free to ask me or lowell any questions. Getting more user data =D

Assigning you since you are the current efolder champ

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
