### ISSUE TITLE
Fix `Requested result set exceeds acceptable size` case

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#1013]
Sentry: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1162

It seems that some records have significance size and return this error instead now. See: https://github.com/department-of-veterans-affairs/dsva-vbms/issues/103

API paging reference can be found here: 
[0003AE_eFolder.v1.0.SCD.15.0_20180511.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/2073643/0003AE_eFolder.v1.0.SCD.15.0_20180511.pdf)

**Comment by pkarman** [comment]
Fixed in #1164
