### ISSUE TITLE
Handle Prometheus unavailability 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#1019]
We had an outage of Prometheus which caused outage of eFolder since pushgetaway was not available. 
https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1508/files

We should catch the failure when sending metrics.

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/jobs/middleware/job_prometheus_metric_middleware.rb#L13

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/jobs/middleware/job_data_dog_metric_middleware.rb

**Comment by RobertAlexanderUSDS** [comment]
@nemo I think this is complete. Can this be closed?

**Comment by nemo** [comment]
@RobertAlexanderUSDS I'd say it looks good to me, but you misspelt @nemodjuric's handle ;)
