### ISSUE TITLE
Reduce cap on Shoryuken Workers

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#1020]
We need to reduce the cap on our shoryuken workers since in our last incident our instances started falling over. We'll reduce the worker count from the default of 25/instance, but increase the number of instances to keep the total parallelism constant.

https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1020

**Comment by alisan16** [comment]
Aug 2, 2018 5:33:59 PM EDT
