### ISSUE TITLE
Move to calling findPagedDocumentSeriesReferences

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#1023]
Some eFolders are too large for us to pull from VBMS using `findDocumentVersionReference`. eFolders with over 5000 documents will fail. However, they have a paged version of the API: `findPagedDocumentSeriesReferences`. We need to start calling this instead to get all of the documents.

This will require updating the `connect_vbms` gem to enable calls to the `findPagedDocumentSeriesReferences` endpoint. Then we will need to update the call in eFolder to use this `findPagedDocumentSeriesReferences` endpoint. We'll have to provide the new `pagingCriteria` to the endpoint, starting with `startIndex` as 0 and incrementing it each call until the returned `pagingReference`'s `nextStartIndex` is `-1`. This should work for files that have fewer than 5000 documents as well as those that have more.

# AC
- [x] Files larger than 5000 documents can be retrieved.

**Comment by pkarman** [comment]
fixed by #1164
