### ISSUE TITLE
Some files not displaying upload date

### ISSUE THREAD

**Issue by gmorgana-va** [department-of-veterans-affairs/caseflow-efolder#103]
Confirmed issue appears on both preview page and download page

<img width="836" alt="screen shot 2016-06-13 at 1 07 42 pm" src="https://cloud.githubusercontent.com/assets/13436986/16016271/26a2bae6-3168-11e6-9944-56d5ea679464.png">

**Comment by shanear** [comment]
@gmorgana-va  what was the file number?

**Comment by gmorgana-va** [comment]
@shanear Sent over the download page for the file (download #579)
