### ISSUE TITLE
Remove unnecessary api call for recent downloads

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#1042]
We are making unnecessary call to get recent downloads as part of initial react data (and do nothing with it), then RecentDownloadsContainer does the same thing. 

<img width="1428" alt="screen shot 2018-10-04 at 9 57 29 am" src="https://user-images.githubusercontent.com/4960030/46478980-0c5cfd80-c7bc-11e8-9920-db60824b0f81.png">

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
