### ISSUE TITLE
Replace root path in routes and remove DownloadsController and Download model

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#1043]
We don't use download model anymore. However, root path still has downloads#new. 
We should remove all the code related to download(s).

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years

**Comment by pkarman** [comment]
I have an open PR against this one.

**Comment by pkarman** [comment]
closing in favor of #1095
