### ISSUE TITLE
Use C file number if SSN doesn't have files

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#1052]
Users sometimes requests a Veteran's eFolder with their SSN when the file is actually stored under the C-File-Number. We should add code like this: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/vbms_service.rb#L43 to eFolder so that we can try the C-File-Number if the SSN doesn't work.

Open question: What should we do with VVA? If someone provides the SSN should we also get what's under the C-File-Number?

**Comment by nemodjuric** [comment]
This will cause duplicate records, but I created separate issue for this, as I think we have to answer at some question first before fixing it. We can tackle one issue at the time, it will make things easier to track.
