### ISSUE TITLE
Standardize what is used for file_number in Manifests creation

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#1057]
See #1052 for context. 

Once we fix #1052, we'll have double records in our database since user can search both by C-file number and SSN. 
We should have a standard way what we use for file_number in Manifest creation. Either claim_number or SSN. 
The impression is that we should always use vbms_id as Manifest file_number. 
I believe that vbms_is is the same as claim_number from BGS which is same as slogid in CORRES in VACOLS.

**Comment by mdbenjam** [comment]
Yeah maybe we make the call to BGS first before anything to get the claim number and then always use that. Regardless of what they've entered.

**Comment by pkarman** [comment]
This is how we approach this problem in caseflow: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/intakes_controller.rb#L97
