### ISSUE TITLE
Add new UI for POA access errors

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#1064]
We want to roll out eFolder Express access to powers of attorneys (VSOs etc). Luckily we already make a call to request veteran information which will fail if the VSO doesn't have access:

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/a624035741b79072a8024f1d3798d16fe6cab8cf/app/controllers/api/v2/manifests_controller.rb#L11

The error returned is: `BGS::ShareError (Power of Attorney of Folder is '071'. Access to this record is denied.)`

We should catch this error and return an error message that is more descriptive to this VSO case like:

```
  def vso_denied_record
    forbidden("This efolder belongs to a Veteran you do not represent. Please contact your supervisor.")
  end
```

We should also have an automated test for both the sensitive record and the vso denied cases.

**Comment by nemodjuric** [comment]
@mdbenjam Do you have an example of VSO id that I can use to test this?
