### ISSUE TITLE
Create a retry download button

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#108]
If a user sees a download page they already downloaded, they should have the ability to restart the download from scratch.

**Comment by KHarshawat** [comment]
This is captured here: https://marvelapp.com/h141bc#13388416

![image](https://cloud.githubusercontent.com/assets/6335546/16717786/4cd1334c-46e8-11e6-9ada-6a82baf31b7f.png)

**Comment by shanear** [comment]
Per conversation, were changing the functionality to retry all.
