### ISSUE TITLE
Set Alerts for Suspicious/Unexpected User Behavior

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#109]
Audit monitoring.

**Comment by KHarshawat** [comment]
Here are some ideas for suspicious behavior we should look out for in eFolder Express. In general, we should be more conservative at first, triggering warnings more than is necessary. We can adjust the criteria once we have more confidence in the system and we've observed actual user behavior. 

- If someone tries fetching cases more frequently than they normally do (e.g. normally someone downloads 2 a day, then they start downloading 20 a day)
- If someone tries to access a case they don't have permission to view
- If someone tries to access a case they don't have permission to view X times in Y timeframe
- If someones started incrementing numbers in search/guessing eFolder IDs.

**Comment by shanear** [comment]
I think we need to start recording eFolder search attempts. Then we can log search counts (successful, permission denied, not found), on the login page.

Thoughts @KHarshawat ?

**Comment by orischwartz** [comment]
Update from standup today: We're going to start this by exposing download stats in the dashboard (#124). This way we see e.g., 

> the top 10 heaviest users per day and how many cases each downloaded.

This will give us a sense of what constitutes normal usage vs excessive/dangerous usage.

**Comment by shanear** [comment]
Added some base monitoring in #185. We should reassess in 1 to 2 months.

**Comment by shanear** [comment]
@cmgiven do you have time to discuss this today?

**Comment by shanear** [comment]
The current monitoring has been deemed sufficent
