### ISSUE TITLE
Remove API v1

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow-efolder#1095]
eFolder Express was redesigned to use React frontend and released as v2 in 2018. None of the now-unused v1 code was ever removed.

This ticket represents the tech debt of removing all the unused v1 code.

See also #1043 

## AC

- [x] Remove v1 code
- [x] Remove feature toggles that controlled v1 vs v2 code
- [x] Drop old tables

**Comment by alisan16** [comment]
@pkarman Can you add more details to this ticket so we can prioritize it if necessary?
