### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow-efolder#1114]
Few things I noticed about README:
- It doesn't mention that it needs the Docker Redis from Caseflow. Running `docker-compose up` from efolder isn't enough. You also have to run it from the caseflow repo
- I don't think we use PhantomJS anymore. The README says you need it, but I was able to run the tests without it, and I don't see it being installed in Travis.

**Comment by pkarman** [comment]
> It doesn't mention that it needs the Docker Redis from Caseflow.

These 2 should be in a `.env` (in the README)

```
REDIS_URL_CACHE=redis://localhost:16379/0/cache/
REDIS_URL_SIDEKIQ=redis://localhost:16379
```
