### ISSUE TITLE
Transient HTTP errors should be ignored in sentry

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow-efolder#1124]
Should not send these to Sentry:

HTTPClient::KeepAliveDisconnected
app/services/image_converter_service.rb in block (2 levels) in convert_tiff_to_pdf

HTTPClient::ReceiveTimeoutError
app/services/external_api/vbms_service.rb in block in send_and_log_request

**Comment by pkarman** [comment]
Some research:

* our VBMS client is set to 10 minutes for `read_timeout`. The `ReceiveTimeoutError` seems to happen after that long. Not sure whether that is to be expected for very large document sets that simply take longer than 10 minutes, or whether there is a transient problem with VBMS (or Efolder) that collides with that 10 minute limit. We should explore that before turning off those sentry errors.

eg. https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/6661/events/517678/

**Comment by alisan16** [comment]
How can I look into the average read times for VBMS? Is it through the DataDog VBMS Latency graph? Or will this require more manual research?

**Comment by pkarman** [comment]
Good question. I don't think DD would have timings, just the total number of calls. https://app.datadoghq.com/dashboard/sx6-wkr-isk/efolder-express-overview

What I would do is try running each of the Sentry alert jobs manually via the console and eyeball the times. If they consistently time out, then that smells like a configuration change might help (maybe try doubling to 20 minutes to start). If they work most of the time, esp if far less than 10 minutes, then that smells more like a transient problem to me and then I would just mute those alerts via the sentry2slack lambda in https://github.com/department-of-veterans-affairs/caseflow/wiki/Bat-Team#stop-sentry-from-sending-alert-on-to-slack

**Comment by pkarman** [comment]
fixed in https://github.com/department-of-veterans-affairs/appeals-lambdas/blob/master/sentry-to-slack/handler.js#L20
