### ISSUE TITLE
.zip files are invalid or too big

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow-efolder#1132]
User has trouble downloading folder for Veteran with 13k+ documents. PID: 3978641

User has trouble downloading folder with invalid ZIP file. PID: 5052060

Related to INC7523674

**Comment by alisan16** [comment]
Is this related to https://github.com/department-of-veterans-affairs/caseflow/issues/10665 and the VBMS::DocumentTooBig errors? It looks like there's an open task to add a fallback to use the updated VBMS paginated API when this happens: https://github.com/department-of-veterans-affairs/caseflow/issues/10901

**Comment by pkarman** [comment]
> Maximum total size of ZIP archive
> A standard ZIP file can be up to 2^32 bytes in size (4 gigabyte of total size of the archive), ZIP64 standard allows the maximum archive size of 2^64 bytes (16 exabyte of total zip size), exceeding the current needs and limitation of most of current implementations of filesystems.
Please note some old zip archivers supports up to 2 GB for maximum archive size (and for max size of each input file), using a signed integer for representing the 32-bit wide size variable.

**Comment by msj0nes** [comment]
@alisan16 let me know if I should open a VBMS ticket in your name regarding this issue and [other VBMS errors](https://github.com/department-of-veterans-affairs/caseflow/issues/10665#issue-440847078) present.  

**This would help clear:**
https://github.com/department-of-veterans-affairs/caseflow/issues/10732
https://github.com/department-of-veterans-affairs/caseflow/issues/10665
https://github.com/department-of-veterans-affairs/caseflow/issues/6680

**Info I need for ticket creation:**

- Data service associated to error
- Engineering Description of issue
- Case Details URL for Vet (PII Prevention - I can obtain ID from URL) 
- Best method of contact for VBMS to reach out

**Comment by pkarman** [comment]
@msj0nes I don't think we're at the point yet (for this ticket anyway) where there is a clear problem with VBMS per se. Most of these require investigation into the root problem.

**Comment by pkarman** [comment]
Confirmed that #1141 fixes this:
> User has trouble downloading folder with invalid ZIP file. PID: 5052060

This one seems to related to #1137

**Comment by pkarman** [comment]
The 13k+ documents generates `VBMS::DocumentTooBig` like

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/6744/events/575179/

**Comment by pkarman** [comment]
Closing this as fixed, moving to #10901
