### ISSUE TITLE
Establish Metrics for eFolder Express

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#124]
We want to establish business metrics for a dashboard to see what's going on in eFolder Express and make sure things are working as intended. There's a lot of possibilities here but I'm starting with the "start at the end" approach of figuring out what questions we want to answer with data. I'll continue to add here then assign to Shane when I think it's ready for feedback/implementation.

**Comment by KHarshawat** [comment]
Starting at the end ... here are some questions we'd like to address:

Are all the users who should be using it actually using it?
- Daily Active Users vs Expected Users broken up by OGC/RMC/etc e.g. `24/36 active OGC users | 9/10 active RMC users`
- Usage over time (hourly, daily, weekly)

Is the tool usable/ working as intended?
- Total Error Rate. e.g. `24% of files attempted errored out`
- Task completion e.g. Google Analytics Flow Analysis for Search > Fetch > Download.

- How long are users waiting on eFolder Express?
 - 95% percentile to download manifest
 - 95% percentile to download entire case

How much time are we saving employees?
- Total number of cases per day downloaded?


For later: 
- Daily percentage of eFolders that are attempted have VVA folders

We are explicitly punting on the "Status page" which is basically user-facing monitoring-lite. Things like is the system up or StatusPage.io. INstead we will rely on CloudWatch Logs for 500s and fatal errors + pager duty notifications. These are some of the things we might want to track on that page though ...
- Uptime
- Number of 500s
- Number of 400s
- Is VBMS down?
- Is BGS down?
- Is CSS down?
- Is Siteminder down?
- Total time per megabyte to download (5mb/s from VBMS)

**Comment by KHarshawat** [comment]
@shanear here are mocks for the immediate version and a version with some charts. One big question is do we include this on `efolder.cf.ds.va.gov/dashboard` or a standalone dashboard app. 

If we want to make a standalone dashboard app then I'll need to re-think the I/A to account for other apps like certification. 

Either way we'll probably want a standalone app for the "Status Page" whenever we make that.


![01_dashboard-v1](https://cloud.githubusercontent.com/assets/6335546/16742628/86a51f82-4776-11e6-8c83-8d5806c279c0.png)
![02_future-dashboard](https://cloud.githubusercontent.com/assets/6335546/16742629/86a89464-4776-11e6-976d-bc26056a0a49.png)

**Comment by shanear** [comment]
I've got the first draft of this up.

Moving to the backlog to reassess when Kavi gets back.

**Comment by KHarshawat** [comment]
@shanear I'd like to meet with you sometime this week to discuss. When are you available?

**Comment by KHarshawat** [comment]
- remove underline from tabs @shanear 
- toggle 95%tile to median @cmgiven 
- UI for going back in time is hover over the chart, all numbers change @cmgiven 
- change labels to `Downloads in August (so far)` and `Downloads in July` and `Downloads in January 2015` @cmgiven 
- Remove padding on all borderless tables @shanear 
- Add charts under each stat @cmgiven 
- Add "by X users" in little text after total downloads e.g. `234 downloads by 12 users`
- Add total number of documents downloaded @shanear 
- Figure out how much we pay per document. @kharshawat

**Comment by KHarshawat** [comment]
@shanear Chris is just gonna take all of these issues since he's already working on stuff.

**Comment by cmgiven** [comment]
- [x] remove underline from tabs
- [x] toggle 95%tile to median
- [ ] UI for going back in time is hover over the chart, all numbers change
- [ ] change labels to Downloads in August (so far) and Downloads in July and Downloads in January 2015
- [x] Remove padding on all borderless tables
- [ ] Add charts under each stat
- [ ] Add "by X users" in little text after total downloads e.g. 234 downloads by 12 users
- [ ] Add total number of documents downloaded
- [ ] Figure out how much we pay per document.
- [x] Use usds secondary for red instead of secondary-dark

**Comment by cmgiven** [comment]
Breaking out into #668, #669, #670, and #671.
