### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#126]
* Include support for events
* Define a funnel so we can track how users are getting from search to listing to zip download

**Comment by orischwartz** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74789258-2', 'auto');
  ga('send', 'pageview');

</script>
```
See https://github.com/department-of-veterans-affairs/caseflow-certification/pull/229 and https://github.com/department-of-veterans-affairs/caseflow-certification/pull/121 for the implementation details in Certification app.

**Comment by NickHeiner** [comment]
![image](https://user-images.githubusercontent.com/829827/28538346-f9a521ec-707b-11e7-88ee-79813d0fbc95.png)

This definitely worked initially, but has not worked in a long time.

**Comment by orischwartz** [comment]
Looks like I screwed up 47e8423456949bf41218f9b5a62d3321a1ba6565 -- the config attribute is named `analytics_account`, not `google_analytics_account` which is being set in production.rb.

**Comment by NickHeiner** [comment]
Yeah, I was thinking that may be problematic. :smile:

Fixing in #549.

**Comment by shanear** [comment]
hi @orischwartz 👋

**Comment by orischwartz** [comment]
hi everyone! :wave:
