### ISSUE TITLE
Leftpad 7-digit case numbers with 2 leading zero

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#134]
> When I enter in a 7 digit file number, it doesn’t pad with a leading zero so the user is told he/she doesn’t have permission to view that folder.

**Comment by shanear** [comment]
Waiting for some UAT test data from Michael Taylor to deal with this one.

**Comment by shanear** [comment]
Emailed michael to create test veteran with a 7 digit file number.

**Comment by lakohl** [comment]
Found an example in UAT.  8605113

**Comment by orischwartz** [comment]
@joofsh: When passing a 7-digit case number, looks like VBMS rejects them outright. 

```
irb(main):011:0> VBMSService.fetch_documents_for(Download.new(file_number: '1234567'))
VBMS HTTP Error 500 (VBMS::Requests::ListDocuments) <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Unmarshalling Error: cvc-minLength-valid: Value '1234567' with length = '7' is not facet-valid with respect to minLength '8' for type 'FileNumber'. </faultstring></env:Fault></env:Body></env:Envelope>
```

Left-padding w/ 2 zeroes does produce a response:

```
irb(main):017:0> VBMSService.fetch_documents_for(Download.new(file_number: '001234567'))
=> [#<VBMS::Responses::Document:0x0055ff76761940 @document_id="{27BXXXXX-0XXX-4XXX-8XXX-3BXXXXXX}", @filename="DD214 - Copy 5.pdf", @doc_type="488", @source="VBMS", @received_at=Fri, 27 May 2016, @mime_type="application/pdf", @alt_doc_types=[]>...]
```
I think just left pad case numbers with 2-zeroes if the length of the case number is exactly 7 digits. 8-digits is a valid length so we shouldn't pad those.

**Comment by orischwartz** [comment]
Just documenting before we forget: @nicholasholtz reports that padding with two leading zeroes is potentially incorrect as it could introduce a collision with an actual 9-digit SSN that begins with 00xxx.

Need to research more whether 1 leading zero will suffice.

**Comment by orischwartz** [comment]
Looks like at least for [above](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/134#issuecomment-240846599) UAT case number 1 leading zero returns no documents whereas two leading zeroes does.

**Comment by joofsh** [comment]
Will hold off on this ticket for now until I get more information. At the moment we do not have an example case that works due to adding a leading `0`

**Comment by lakohl** [comment]
Perhaps I mis-remembered this issue. I had the same experience just now trying out a short Vet ID first with a single zero in front - failed, then with two zeros in front - succeeded in both VBMS UAT and eFolder Express UAT.

**Comment by nicholasholtz** [comment]
Check out this document from SSA:

https://www.ssa.gov/policy/docs/ssb/v45n11/v45n11p29.pdf

Real issue probably comes up with Vets from New Hampshire, where SSNs start with 001, 002, and 003. Other potential troubling states include Maine (004, 005, 006, 007), and Vermont (008, 009).

**Comment by aroltsch** [comment]
Anya will try to re-produce it in production or uat and then contact the VBMS dev team about it.

**Comment by pkarman** [comment]
closing as this doesn't seem to be a live issue.
