### ISSUE TITLE
Enforce shorter session timeouts

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#138]
> You also might want to verify when/how often you close the active session for an authenticated user.  I closed the IE tab for caseflow from 12:38 to 1:00 pm (a little under 25 minutes) to test it and was able to restart the session without logging in again by clicking the link from my IE history without authenticating again

**Comment by shanear** [comment]
@orischwartz This is addressed in AC-11.1 in the ATO

https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/ATO/Caseflow%20ATO/Caseflow-ATO%20Working%20Docs/sops/AC.md

We're using the VA Laptop auto logoff to satisfy the requirement.

**Comment by shanear** [comment]
@gmorgana-va can you confirm? and if i'm correct lets close this one out.

**Comment by gmorgana-va** [comment]
The implementation referenced by @shanear is included in the ATO.  Will be reviewed as part of the ATO review in the first week of August as well (tracking in appeals-pm).
