### ISSUE TITLE
Add case # to heading

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#142]
https://marvelapp.com/h141bc#13388415

**Comment by shanear** [comment]
@KHarshawat 

There's a discrepancy in the heading on these two mocks:

https://marvelapp.com/h141bc#13388414
 and
https://marvelapp.com/h141bc#13388415

Which should we use?

**Comment by KHarshawat** [comment]
@shanear I think we should use this if we can:

![image](https://cloud.githubusercontent.com/assets/6335546/16717766/1d1a3324-46e8-11e6-8fef-d949676d4c05.png)
