### ISSUE TITLE
Deal with outdated eFolder downloads

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#147]
What should be done about the following scenario?

1) User downloads eFolder X
2) A new file is added to the eFolder X
3) User types in eFolder X but is redirected to the download that occured in 1), without containing the file added in 2)

**Comment by KHarshawat** [comment]
As discussed this depends largely on the timeout for the downloads. Currently the timeout is 24 hours. If it is longer than this we could

A) Poll for new files and show a message letting the user re-fetch the manifest
B) Poll for new files and automatically re-fetch the manifest

I'm tempted to say that we hold off until this actually becomes a known problem though.

**Comment by KHarshawat** [comment]
Closing this issue. We can re-open if we decide to increase the timeout period.
