### ISSUE TITLE
Create new "Admin" function in CSS

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#157]
We need to create a new function called something like"Admin" that gives us (DSVA) access to certain parts of our applications (such as a Dashboard)

**Comment by gmorgana-va** [comment]
Sent request for new function titled "System Admin"

**Comment by gmorgana-va** [comment]
Created in UAT.  @shanear to test

**Comment by KHarshawat** [comment]
Works in UAT, needs to be moved to pre-prod/prod.

**Comment by shanear** [comment]
Was supposed to be added yesterday, but doesn't look like it's working. I followed up with Lindsay about it today.

**Comment by shanear** [comment]
Fixed.

getting some campari now.
