### ISSUE TITLE
Add modal warning users when they "Download Anyway" if a Download has errored documents.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#160]
broken off from #51

**Comment by shanear** [comment]
Hey @lakohl  can you take a look at this and see if we need it, and what it should look like?

**Comment by lakohl** [comment]
It's a good idea. We should do it. I can provide a visual, but probably not until Tuesday. Sorry.

**Comment by shanear** [comment]
@lakohl No problem. We'll create something pretty lightweight, and you can tweak from there.

**Comment by amprokop** [comment]
i started investigation and started playing around with an alert for this while waiting for more direction.

just a note—modals can present accessibility difficulties. you have to trap the keyboard in the modal when it appears, ensure keyboard accessibility inside the modal, then return focus to someplace logical after the modal is closed. @shanear @lakohl— have we integrated modals elsewhere? what priority would you assign to the accessibility of this modal?

**Comment by shanear** [comment]
@amprokop we need it to be accessible (including all of the focus trapping stuff). I'm thinking a vanilla JS class similar to the ones we already have should work for creating the modal and doing all of that stuff

Does that sound good?

**Comment by amprokop** [comment]
great. after IRL discussion, action item is to take the modal from caseflow-certification, make it accessible, and port it to caseflow-efolder!
