### ISSUE TITLE
Change wording of "zip" file

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#170]
"Zip" is a technical term. Consider going back to "Fetch files."

**Comment by KHarshawat** [comment]
or "Downloaded files"

**Comment by lakohl** [comment]
@KHarshawat Will look into this. Where are the design docs for this? or what is your process for conveying these changes.

**Comment by KHarshawat** [comment]
Here's my current design. Feel free to ping for more. I'd also reference the existing app since what's designed might be different than what's built. :)

[eFolder Express v2.1.zip](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/425683/eFolder.Express.v2.1.zip)

**Comment by abbyraskin** [comment]
Let's also update the messaging to clarify when files are actually downloaded vs. retrieved/fetched/collected (whatever word we end up using - I think fetched may be overly technical too).

**Comment by lakohl** [comment]
see: https://github.com/department-of-veterans-affairs/appeals-pm/issues/698

**Comment by lakohl** [comment]
closing this as it's captured in #746
