### ISSUE TITLE
Users still think eFolder Express is "Downloading" files when they fetch them from VBMS

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#171]
Consider changing the wording back to "Fetch" instead of "Prepare for Download." Maybe wait for more feedback before making this change.

**Comment by lakohl** [comment]
@KHarshawat will investigate further after we meet with current users next week. Is there an existing Sketch file for this?

**Comment by KHarshawat** [comment]
Here's my current design. Feel free to ping for more. I'd also reference the existing app since what's designed might be different than what's built. :)

[eFolder Express v2.1.zip](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/425688/eFolder.Express.v2.1.zip)

**Comment by lakohl** [comment]
See #698

**Comment by abbyraskin** [comment]
We're hoping to have addressed this with our copy edits and will investigate this during usability testing - implementation tracked in #746. Closing.
