### ISSUE TITLE
Always provide a link to go back to the home page.

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#172]
Users clicked the efolder.cf.ds.va.gov link in the "Take a breather" message. We should include a similar link in the success message.

**Comment by lakohl** [comment]
@KHarshawat I need more details or a reminder about this.

**Comment by lakohl** [comment]
@KHarshawat can we discuss this for a few min?

**Comment by KHarshawat** [comment]
Sure! Just grab me @lakohl

**Comment by lakohl** [comment]
Am looking more closely at design options. But, putting this on hold while we are conducting usability sessions. So far returning to home has not been an issue during our testing.

**Comment by lakohl** [comment]
@KHarshawat based on our recent usability tests I am reluctant to do this. Lets discuss!

**Comment by KHarshawat** [comment]
Happy to discuss but I trust your judgement based on the feedback. We can close this issue as won't fix if you like :)

**Comment by lakohl** [comment]
Decided not to fix this right now until more users ask for it. Closing.
