### ISSUE TITLE
Add a scheduled job that removes all downloaded files from filesystem

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#183]
e.g., every night at midnight ET, delete all files in `${APP_SRC}/tmp/files/[case #]/*`. No additional logic should be required because we already account for the scenario of having incomplete downloads on local filesystem: 

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/download_documents.rb#L108

**Comment by KHarshawat** [comment]
@orischwartz do we clear out downloaded files from the filesystem today? If so would you mind closing this issue?

**Comment by orischwartz** [comment]
Closed via #184
