### ISSUE TITLE
Avoid duplicate database querying when collecting stats

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#186]
As discussed here https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/185#discussion_r73216568

Many metrics operate on the same underlying query, e.g., `Download.where(completed_at: range)`. We shouldn't repeat the query 7 times. Instead, query once and then operate in-memory.

**Comment by aroltsch** [comment]
I don't think this is an issue because the calculations are done as a Sidekiq job (`CalculateStatsJob`) and then saved in cache.  @orischwartz-gov @shanear

**Comment by shanear** [comment]
Because this is done in the job. I think it's not going to save us much. it's cool to close this.
