### ISSUE TITLE
Add revised "Take a breather" messaging

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#20]
Still need to tweak the wording. The message should communicate that you can close the window, the file will be accessible from the homepage, and that it'll only be available for X hours after all the files have been fetched

![image](https://cloud.githubusercontent.com/assets/6335546/15360729/be2d1316-1cdc-11e6-96b6-bb34014e5055.png)

**Comment by KHarshawat** [comment]
@maryannbrody thoughts on this?

**Take a breather!**
You can close this window at anytime and get back to this page from the eFolder Express homepage. 

Note: Zip files expire within 24 hours after they've been fetched by eFolder Express.

**Comment by maryannbrody** [comment]
How about this, @KHarshawat ?

Take a breather!
You can close this window at any time and get back to this page from the eFolder Express homepage.

Note: Zip files expire after 24 hours. After 24 hours, you will need to fetch the files again.

**Comment by KHarshawat** [comment]
Awesome! This is now in @shanear's court
