### ISSUE TITLE
Raise VBMS errors, don't just log them

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#207]
Right now there's no difference between "eFolder not found" and "VBMS Error", we should make a different error message for these and properly raise the error to Sentry

**Comment by shanear** [comment]
Also, we should provide a message in the UI that there was an error with VBMS.

@abbyraskin can you provide guidance on the copy?

**Comment by abbyraskin** [comment]
@shanear yes, would you mind attaching a screenshot with the current copy?

**Comment by shanear** [comment]
<img width="1554" alt="screen shot 2016-10-06 at 5 47 56 pm" src="https://cloud.githubusercontent.com/assets/1596259/19191865/2c0a8738-8c72-11e6-87dd-a344fd992a46.png">

**Comment by abbyraskin** [comment]
@shanear do you know at what point(s) a VBMS error could theoretically appear? only after searching for a veteran ID, or could it also happen after clicking the "Start Retrieving eFolder" button, for instance? I want to make sure the language meets the context...

**Comment by shanear** [comment]
@abbyraskin it would occur after entering the file number, but before the preview page appears. It occurs because there was a VBMS error when fetching the file list.

**Comment by abbyraskin** [comment]
OK - thanks.

@joofsh here's the copy:

Header: **Can't connect to VBMS**
Body: Please give VBMS a few moments to come back online, then try searching for the eFolder again.
