### ISSUE TITLE
Implement redesign for 404 page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#210]
@mmlumba based on what @shanear is saying, there are 2 error states. 
Update the Wording and styling of the two 404 pages for eFolder Express:

Scenario 1: A user enters an ID in the search box. On the backend we look in BGS to make sure there is a folder with that ID but can't find one. If we can't find one, we report this back to the user. This error state should look like the following:

![image](https://cloud.githubusercontent.com/assets/6335546/21613992/c2256cc4-d1a5-11e6-8fa9-2668fb127d09.png)

Scenario 2: A user enters an ID in the search box. On the backend we look in BGS to make sure there is a folder with that ID and successfully find one. We then connect to VBMS and try loading documents but there are no documents available in the eFolder. In this scenario, we show the following:

![image](https://cloud.githubusercontent.com/assets/6335546/21613968/9c691238-d1a5-11e6-9035-4512134a02d5.png)

See issue #161 for additional context.

**Comment by KHarshawat** [comment]
@lakohl use the error message styles in the messages page here:
[Caseflow_010616.zip](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/536480/Caseflow_010616.zip)

**Comment by lakohl** [comment]
<img width="395" alt="screen shot 2016-11-06 at 11 11 32 pm" src="https://cloud.githubusercontent.com/assets/4975959/20046333/7419f83a-a476-11e6-9d7c-ecda8449c3fd.png">

**Comment by mmlumba** [comment]
@lakohl @KHarshawat @shanear Is the screenshot above supposed to be on its own page or is it included as an error message within the main download page? (see below)
![screen shot 2016-12-09 at 9 19 21 am](https://cloud.githubusercontent.com/assets/4773320/21051966/a404d87e-bdf0-11e6-837f-10da0ac993e7.png)

**Comment by KHarshawat** [comment]
It's supposed to be it's own page like the one you worked on the other day :)

**Comment by lakohl** [comment]
@mmlumba the Search again doesn't need to be underlined. Also our other CTA are sentence case.

**Comment by kierachell** [comment]
Unable to test this because `demo` throws all kinds of errors for invalid searches; (but looks good in theory :D )

**Comment by shanear** [comment]
@mmlumba This doesn't seem to be working correctly. I think in our conversations on this one, I may have mislead you by saying there "No documents" and "No efolder" are the same. For VBMS, they are. But we also do a BGS check. We should regroup to see how we want this one done:

folder is missing in BGS:
<img width="1512" alt="screen shot 2017-01-02 at 8 35 40 am" src="https://cloud.githubusercontent.com/assets/1596259/21590083/8b3cc214-d0c6-11e6-8ad7-ffba45e52fbd.png">

folder is missing in VBMS:
<img width="1512" alt="screen shot 2017-01-02 at 8 35 44 am" src="https://cloud.githubusercontent.com/assets/1596259/21590084/8c386772-d0c6-11e6-97d2-26f0fbf09848.png">

**Comment by KHarshawat** [comment]
@mmlumba based on what @shanear is saying, there are 2 error states. 

Scenario 1: A user enters an ID in the search box. On the backend we look in BGS to make sure there is a folder with that ID but can't find one. If we can't find one, we report this back to the user. This error state should look like the following:

![image](https://cloud.githubusercontent.com/assets/6335546/21613992/c2256cc4-d1a5-11e6-8fa9-2668fb127d09.png)



Scenario 2: A user enters an ID in the search box. On the backend we look in BGS to make sure there is a folder with that ID and successfully find one. We then connect to VBMS and try loading documents but there are no documents available in the eFolder. In this scenario, we show the following:

![image](https://cloud.githubusercontent.com/assets/6335546/21613968/9c691238-d1a5-11e6-9035-4512134a02d5.png)

**Comment by KHarshawat** [comment]
@shanear can you confirm when you have a sec?

**Comment by shanear** [comment]
Yes this looks good.

@mmlumba as a technical guidance, in scenario 1 we will not have created a download (the state will be `:veteran_not_found` in search). In scenario two a download is created with a status of `:no_documents`.

**Comment by mmlumba** [comment]
@kierachell @astewarttistatech Per the summary above there's 2 scenarios to test.
Scenario 1 (for testing in dev):
1. Replace the following in `app/models.search.rb`:
```
def validate!
    if download.demo?
      return true
```
with this:
```
def validate!
    update_attributes!(status: :veteran_not_found)
      return false
```
2. Type anything with `DEMO` in the search bar
3. Validate scenario 1 looks similar
4. Revert code change

Scenario 2:
1. Type `DEMO_NO_DOCUMENTS` in the search bar.
2. Validate scenario 2 looks similar

**Comment by kierachell** [comment]
Works locally: will it work in `demo` is the question

<img width="1297" alt="screen shot 2017-01-06 at 15 36 55" src="https://cloud.githubusercontent.com/assets/18075411/21732148/1c1e660e-d426-11e6-8eb2-011b9a6bd9c7.png">
<img width="1305" alt="screen shot 2017-01-06 at 15 37 39" src="https://cloud.githubusercontent.com/assets/18075411/21732149/1c3ae40a-d426-11e6-8ec2-1b29ee34504f.png">

Can't really test that in `demo` because : 
<img width="912" alt="screen shot 2017-01-06 at 15 41 49" src="https://cloud.githubusercontent.com/assets/18075411/21732255/ab0af65c-d426-11e6-8ee3-433402bed4cb.png">

I know this is a separate issue but
I can add a hacky stub (we already have one for `download`)?

**Comment by mmlumba** [comment]
@shanear Screenshot for scenario 1 on UAT:
![screen shot 2017-01-09 at 10 17 43 am](https://cloud.githubusercontent.com/assets/4773320/21771466/7360a34c-d655-11e6-9436-0242744ea61a.png)

Can't recreate second scenario.

**Comment by kierachell** [comment]
@shanear @askldjd or someone who can get a NO_DOCUMENTS folder please validate and push this through;
