### ISSUE TITLE
Filter out XML document types

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#211]
[DBQs](http://www.benefits.va.gov/compensation/dbq_disabilityexams.asp) in XML format should not be returned to the user. 

These are sent back with a docType of `999981 - C&P Exam XML` and have a corresponding PDF with a docType of `356 - C&P Exam`.

**Comment by lakohl** [comment]
@orischwartz can you confirm that all the info in the .xml  is visible in the .pdf?
