### ISSUE TITLE
User reports that documents with same receipt date are not ordered the same as VBMS

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#213]
We store receipt date as a date with no time so documents with the same value will be ordered arbitrarily. 

Possible solutions:
* ~~Determine if VBMS stores the exact timestamp and use that instead~~ Per https://github.com/department-of-veterans-affairs/connect_vbms/issues/120, VBMS doesn't send the exact timestamp. 
* If VBMS returns the files in the expected order, their ids will be sequential. Use a compound ordering on the document sorting as follows:
  - Receipt date 
  - If equal, sort by document id

See #130 for original implementation.

**Comment by lakohl** [comment]
@orischwartz We received new feedback from OGC today. Cathy Chase re-tested the same 25 cases that she tested previously and still found some issues with the ordering of files received on the same day. Will share ID#s and her notes elsewhere.

**Comment by orischwartz** [comment]
Example from user report below.

Order received from VBMS manifest:

```
A. #<VBMS::Responses::Document @filename="xxxxx69.pdf", @doc_type="27", @received_at=Wed, 11 Feb 2015, @mime_type="application/pdf",>, 
B. #<VBMS::Responses::Document @filename="xxxxx04.pdf", @doc_type="353", @received_at=Wed, 11 Feb 2015, @mime_type="application/pdf">
C. #<VBMS::Responses::Document @filename="xxxxx05.pdf", @doc_type="45" @received_at=Wed, 11 Feb 2015, @mime_type="application/pdf">
```

Order displayed by eFolder Express:

```
C. xxxxx69.pdf
B. xxxxx04.pdf
A. xxxxx69.pdf
```

Which is exactly backwards. I had assumed since we were sorting by receipt date DESC that the sequential id should also be DESC. Apparently VBMS does it the other way.
