### ISSUE TITLE
Update eFolder Express Copy

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#216]
@KHarshawat @lakohl and I reviewed copy across eX. Here are our recommended changes. The layout for all of these should remain as-is, and  any copy that isn't called out below remains as-is for now. Let me know if anything is unclear or if you'd like more context for the edits.

@shanear: if it's possible to get to these by end of week, we're hoping to test the new copy with OGC contractors as soon as they're on board.

### Home Page
_Instructional copy:_ `Search for a Veteran ID number below to get started.`

_Label:_ ~~Download~~ `History`

### Search Results Page
_Instructional copy_: `eFolder Express found [#] files in eFolder #123456789 (VETERAN NAME). Verify the ID # and click the Start Retrieving eFolder button below to retrieve the files from VBMS. `

_Button Label:_ `Start Retrieving eFolder`

### Retrieving Files Page
_Informational message copy:_  

```
You can close this page at any time.
eFolder Express will still continue gathering the files from the VBMS. Go to the home screen: http://efolder.cf.ds.va to open the documents once they've been retrieved.

Note: eFolders remain in your History for three business days.
```

#### Success / Ready to Download Page
_Instructional copy:_ `All of the documents in the VBMS eFolder #123456789 are ready to download. Click the Download eFolder button below.`

_Button label:_ `Download eFolder`

**Comment by shanear** [comment]
@abbyraskin @lakohl A couple Q's

1) Just making sure this should be `eFolder Express found 200 files in eFolder #123456789 (VETERAN NAME).` and not `eFolder Express found [200] files in eFolder #123456789 (VETERAN NAME).`
2) Because of https://github.com/department-of-veterans-affairs/appeals-pm/issues/715. Can we say `eFolders remain in your History for 72 hours.` instead?

**Comment by abbyraskin** [comment]
1) correct! (the first option) 2) yes! that's clearer - thanks.



-----Original Message-----

**Comment by lakohl** [comment]
'Retrieving' page and 'Success' page still have to CTA as Download Zip. The button copy should be changed to `Download eFolder`
