### ISSUE TITLE
Revise homepage with previously fetched eFolders

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#22]
We currently have the following. 
- Recent searches isn't the right title. 
- Need to figure out a way to indicate when eFolder express couldn't fetch all the files (maybe force the user to view the status page first).
- Should consider adding the veterans name here for easier disambiguation 

![image](https://cloud.githubusercontent.com/assets/6335546/15360795/10e67016-1cdd-11e6-9713-d0661ec92320.png)

**Comment by shanear** [comment]
replaced with dev tasks
