### ISSUE TITLE
Use "lastName, firstName - lastfour" convention for packaged zip files

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#223]
See also #55.

For now just change the zip naming convention. 

- [ ] Modify BGSService to return e.g., array of [firstName, lastName]
- [ ] Store first and last names separately in `Download` model.
- [ ] Add convenience method to Download for full `veteran_name`.
- [ ] Update zip-naming format in `Download#package_filename`

**Comment by lakohl** [comment]
User feedback was that they currently use last name, last four digits of veteran ID. Hold off on changing just yet though.

**Comment by shanear** [comment]
this is confirmed per:
https://github.com/department-of-veterans-affairs/appeals-pm/issues/834

**Comment by amprokop** [comment]
Changing the format to Last, First - 1234.zip per discussion with @shanear.
