### ISSUE TITLE
BVA decision (doctype 27) should appear after the notification letter (doctype 184)

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#236]
The sorting criteria should be:
- Receipt date DESC
- DocType (only ordering imposed is that docType 27 appears after 184)
- VBMS order ASC (i.e., auto-increment document id ASC)

See also #213 and #130 for original discussion of document sorting.

**Comment by orischwartz** [comment]
There's no good way to do this sort in SQL so using ActiveModel's `has_many, order:` syntax so [the way we do it now](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/215/commits/6e4da029d4cc9a43e58f3f89943c228e1242bda0) won't work.

Options:

* Sort the documents once before [saving them](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/download_documents.rb#L15).
* Sort them in-memory in the `Download` model before returning them in the `documents` method (memoize result so it's not repeated on every invocation). Not sure what the cleanest way to do that is. The sorting algorithm is roughly:

```ruby
def sort_documents_in_display_order(documents)
  documents.sort do |left, right|

    # receipt_date DESC
    comp = -(left.received_at <=> right.received_at)

    return comp if comp != 0

    # special case, make sure BVA decision (27) appears after notification letter (184) if both arrive on same date
    # and viewing docs in reverse receipt date order
    if (left.doc_type == 27 || right.doc_type == 27) &&
      (left.doc_type == 184 || right.doc_type == 184) &&
      left.doc_type != right.doc_type
      return -(left.doc_type <=> right.doc_type)
    end

    # maintain VBMS API order, id ASC
    left.id <=> right.id
  end
end
```

**Comment by ariperez** [comment]
@orischwartz , should we remove the in-progress label on this?  Put it back in the sprint backlog column until someone picks it up?

**Comment by orischwartz** [comment]
@ariperez My understanding was we were targeting for release this week...will clarify.

**Comment by orischwartz** [comment]
Per [VBMS response](https://github.com/department-of-veterans-affairs/dsva-vbms/issues/57#issuecomment-253046565) we're on our own when it comes to matching the VBMS interface. The ListDocuments service doesn't match the web interface and there are no plans to change that.

The approach outlined here (reverse engineer the order based on user feedback) will have to suffice for now.

**Comment by shanear** [comment]
@lakohl Yeah, judging from VBMS's response, there's no way we can match their order without an update to their API, which could take months.

We can commit to receipt date order, but not the order in VBMS, because they don't tell us the manually created order.

We should discuss options, you free for a call?

**Comment by lakohl** [comment]
@shanear @orischwartz I can talk on this at 2:30

**Comment by lakohl** [comment]
@shanear I will reach out to Nicholas to find out if he knows more about the scanning protocol and ordering of VBMS files.

**Comment by lakohl** [comment]
I am going to see if I can get more info from Nicholas on the legal order of files with the same date

**Comment by KHarshawat** [comment]
Checking with Nicholas but I believe we cleared this up with OGC.

**Comment by lakohl** [comment]
@KHarshawat we determined that including the date, the doc type, and the doc id in the the file name was sufficient to solve this issue for now. No need to create a workaround to re-order the VBMS files eX receives. Closing this issue.
