### ISSUE TITLE
Change Retry Download button label

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#241]
Change copy on the Retry Download button to something like Try Again. The word download is misleading.

**Comment by shanear** [comment]
@lakohl need your guidance on what the button should say

**Comment by lakohl** [comment]
@abbyraskin what do you think?

'Try Retrieving eFolder Again'
'Retrieve eFolder Again'
'Re-Retrieve eFolder'

**Comment by abbyraskin** [comment]
@lakohl what about "Retry Retrieval"? Or even just "Try Again" (given that this is just the CTA, we have other copy describing the issue). Of the options above I like "Try retrieiving eFolder again" (if it just says re-retrieve or retrieve again it implies you did it once already)

**Comment by lakohl** [comment]
I feel like it's important to let the user know what they are going to get if they try again. 

@shanear let's do this:

**Some files couldn't be `added to eFolder`**
eFolder Express `wasn't able to` retrieve some files. Click on the 'Errors' tab below `to view them`.

You can still download the rest of the files by clicking the 'Download `Anyway`' button below.

_CTAs:_ **`Download anyway` `Try retrieving eFolder again`**

**Comment by shanear** [comment]
Thanks @lakohl!
