### ISSUE TITLE
Browser:  Back/Forward browser buttons cause error after searching

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow-efolder#247]
An error is received when the Back and Forward buttons are used in the browser.  Browser used: Chrome

### Reproduction Steps
1. Go to eFolder homepage
1. Search for any filename (DEMO).
1. Wait for resulting list of files, then wait another ~3 seconds (must have a polling request fire)
1. Click `back` browser button, to go to homepage (search bar)
1. Click forward in browser to go back to your initial search results
1. You'll end up at a JSON response page that looks like:

  <img width="1178" alt="screen shot 2016-10-12 at 6 03 34 pm" src="https://cloud.githubusercontent.com/assets/2256237/19329344/37f8d7e2-90a6-11e6-84e1-27e75ad3e197.png">

**Comment by nikitarockz** [comment]
@joofsh Is this still a problem? I tried to reproduce it but wasn't able to.

**Comment by joofsh** [comment]
I cannot reproduce either. Let's close the ticket 👍
