### ISSUE TITLE
Update warning copy on Retrieving page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#260]
From: https://github.com/department-of-veterans-affairs/appeals-pm/issues/832
Please change the copy on the 'Retrieving' page to:
'You can close this page at any time and eFolder Express will continue retrieving files in the background. View progress and download eFolders from the History on eFolder Express home page.'
<img width="752" alt="screen shot 2016-10-18 at 2 23 18 pm" src="https://cloud.githubusercontent.com/assets/4975959/19490864/d974ebc8-953e-11e6-94b2-11eb8f8064c2.png">

**Comment by lakohl** [comment]
@joofsh My bad. Making updates using old design files is a bad idea. Please keep the Note about about files remaining in the History for 72 hours on this page. No change there.

**Comment by amprokop** [comment]
nit:

maybe `on *the* eFolder Express home page`?

**Comment by amprokop** [comment]
if "home page" were a proper noun this would be right but it seems like we're using it in the generic sense here.

**Comment by amprokop** [comment]
cc @lakohl — gentle suggestion, feel free to thumbs it down

**Comment by lakohl** [comment]
@amprokop happy for the suggestion. Are you are saying we should change...
`Note: eFolders remain in your History for 72 hours.`
to
`Note: eFolders remain in your History on the eFolder Express home page for 72 hours.` 
If so, that works sounds good to me.

**Comment by amprokop** [comment]
oops sorry @lakohl — i actually meant to change

`View progress and download eFolders from the History on eFolder Express home page.'`

to

`View progress and download eFolders from the History on the eFolder Express home page.`

**Comment by lakohl** [comment]
ah ok. Yes, that sounds better!
