### ISSUE TITLE
make health-check return more useful stuff

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#266]
Instead of just returning some random text, we're going to update the app to return some json formatted meta info about the deploy to assist the jenkins health check:

Current plan is as follows:
```
{
  healthy: true,
  last_deployed_at: "Wed Jan 13 17:43:00 EST 2010",
  commit: "6cd04301307ddb3eb2e6ba990a0b0dfeb8abbe36"
}
```

**Comment by shanear** [comment]
@orischwartz how do you feel about this?

**Comment by orischwartz** [comment]
@shanear awesome, yeah very useful. As long as it returns 200 when healthy ELB will be ok change.

Somewhat related: our health-checks are pretty useless right now. They'll only detect if an instance is unresponsive. They should touch database or redis to make sure instance is still connected. (I've seen AWS availability zones lose connectivity before while others stay up; ELB can automatically remove instances in unhealthy zones from rotation if the health check detects this.)

**Comment by shanear** [comment]
I like that, we can build more checks into our health check too (including VBMS and BGS?).

I'll make that a separate issue.
