### ISSUE TITLE
Add link to submit feedback if user sees an error.

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#27]
If a user see's an error like those listed out in #21 they should have a way to submit feedback to help us catch edge cases.

**Comment by shanear** [comment]
@KHarshawat the designs don't capture this. What specific places/error messages do we want the link?

**Comment by KHarshawat** [comment]
@shanear thinking about this a little more there are two sides of this. First, we can probably just log every time a user sees an error message when they search for an ID that isn't there on the homepage or whenever the user sees any other type of issue. This is now captured in #148.

Second, I think there is the idea of empowering the user to take some action if they encounter an error message so they don't feel helpless. That was the idea behind adding the link in the error message, flag the issue in our logs, and then show the user the modal like the one below. These designs aren't final and I don't think this is launch blocking so we can punt it for now as long as we do the logging on the backend. I'll let you decide.

![image](https://cloud.githubusercontent.com/assets/6335546/16718132/e21925d4-46ea-11e6-9791-6f7500cf3459.png)

![image](https://cloud.githubusercontent.com/assets/6335546/16718133/e6727360-46ea-11e6-922b-9e07359e0d6a.png)
