### ISSUE TITLE
Remove connect_vbms source from vendor directory

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#271]
`connect_vbms` dependency is [pulled from](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/Gemfile#L54) git repo, no longer need the checked-in code in `vendor/`.

**Comment by amprokop** [comment]
I don't see this code  in `/vendor`anymore, closing

**Comment by orischwartz** [comment]
Hi! I think this is issue is still valid -- it's going to feel really good to delete thousands of lines of code :)

Connect VBMS included here in the gemfile: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/630e23811e2cfa5c5d35fc7e7e70dc9f1d6e2667/Gemfile#L86

Unused vendor code just taking up space: https://github.com/department-of-veterans-affairs/caseflow-efolder/tree/630e23811e2cfa5c5d35fc7e7e70dc9f1d6e2667/vendor/gems/connect_vbms

**Comment by amprokop** [comment]
hey @orischwartz! hope you're well. looks like you're right lol, will remove!
