### ISSUE TITLE
eFolder Dashboard Doesn't Show Accurate Usage Numbers

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#282]
Seems like there's something busted in the way we're tracking active users @cmgiven. When looking at the dashboard on the weekly tab. If I highlight a day with these statistics:

![image](https://cloud.githubusercontent.com/assets/6335546/20086948/57ffc2de-a542-11e6-96c5-006f7f5662b5.png)

It only shows me these active users:

![image](https://cloud.githubusercontent.com/assets/6335546/20086939/496753ae-a542-11e6-81c1-af8a79283284.png)

**Comment by cmgiven** [comment]
Expected functionality. We only show the top three most active users. Lmk if you'd prefer to show more.

**Comment by KHarshawat** [comment]
@cmgiven I'm not sure I understand how t his is possible. There were only 17 users and there were 22 completed downloads meaning at least one person had to download more than one eFolder. This only shows users who completed 1 download.
