### ISSUE TITLE
Decrease width of alert on eFolder Express homepage

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#287]
Decrease width of alert on eFolder Express homepage. Currently the page looks like dis

![image](https://cloud.githubusercontent.com/assets/6335546/20285121/36a98358-aa8e-11e6-8ce6-d3b3efb20c25.png)

It should look like dis:

![image](https://cloud.githubusercontent.com/assets/6335546/20285208/a0e38b6a-aa8e-11e6-81fe-86554b7218ff.png)

**Comment by mmlumba** [comment]
@KHarshawat This is what eFolder looks like with the error moved above the header
![screen shot 2016-12-14 at 1 03 42 pm](https://cloud.githubusercontent.com/assets/4773320/21194384/d0a00ce4-c1fd-11e6-9c42-1e1a7c7b445f.png)
If this looks ok to you I'll create the PR for this issue.

**Comment by KHarshawat** [comment]
Yep! Looks good @mmlumba !

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached
![screen shot 2016-12-14 at 4 31 24 pm](https://cloud.githubusercontent.com/assets/23038505/21231856/badb9a6c-c2b7-11e6-9297-4c7b2abb29ec.png)
