### ISSUE TITLE
Home |  Search |  Remove extra padding from the right of search box

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#288]
When an invalid veteran id is entered and the error message is displayed, the Search box is displayed with extra padding on the right.  This padding should be removed.  The Search button should be completely left aligned and not have this weird extra padding.

**Environment:**
- [x] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproductive Steps
1. On the home page, enter an invalid Veteran ID.
1. Click the Search button.
1. The "Couldn't find an eFolder with that ID" is displayed; however, the Search box is rendered with extra padding to the right of the box. 

## Screen Shots
**_View - Search Box with error message_**
![image](https://cloud.githubusercontent.com/assets/6335546/20285198/95112eb4-aa8e-11e6-9b5a-7b24bd214b5e.png)

**_View - Here's a closer look!_**
![image](https://cloud.githubusercontent.com/assets/23063044/20766245/a1690868-b703-11e6-9463-276a76b341ab.png)

**Comment by nikitarockz** [comment]
@KHarshawat Based on what I am seeing in this image, this seems to occur when you get the error message.  When I look at this while not having an error message it looks fine.  Or am I missing something here.  I am testing this out on the Demo site but I can't get the demo site to give me that same error message you have.

![image](https://cloud.githubusercontent.com/assets/23063044/20757863/f0b7c7ec-b6e5-11e6-8199-ea298a175a71.png)

**Comment by KHarshawat** [comment]
@nikitarockz yes, this is only when the error message is show after eFolder Express can't find an ID to match the one the user entered. The goal of this issue is to fix the appearance of said error message when it appears.

**Comment by Chingujo** [comment]
this has been resolved via style guide so closing.
