### ISSUE TITLE
Implement redesign for unauthorized page

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-efolder#29]

**Comment by paultag** [comment]
![unauthorized](https://cloud.githubusercontent.com/assets/132447/15370801/82b2f3ee-1d06-11e6-92cb-a89a4bfebae0.png)

**Comment by KHarshawat** [comment]
See https://github.com/department-of-veterans-affairs/appeals-pm/issues/399 for instructions on how to get access to eFolder Express.

**Comment by lakohl** [comment]
@KHarshawat could you elaborate on this a bit?

**Comment by KHarshawat** [comment]
So the idea is that when a user doesn't yet have access to eFolder Express they get to an un-authroized page. Our hope was that this page could provide an "escape hatch" of sorts where it would inform the user how they could request permission to access eFolder express (hence the issue in my comment above). If it's too much of a hassle to write the instructions for how to request access on this page, perhaps we could include a link like ...


"Click here to find out how you can request access to eFolder Express" that links to the relevant section of the help page.

**Comment by lakohl** [comment]
Contact your manager and say you want access to eFolder Express - Talk to your ISO.

**Comment by lakohl** [comment]
<img width="702" alt="screen shot 2016-11-01 at 11 46 17 am" src="https://cloud.githubusercontent.com/assets/4975959/19895955/1d25e3f0-a029-11e6-8ae2-98dfdb8ac90d.png">
'Click here' would link to the section in the FAQs with the Q & A 'How do I get access to eX?'

**Comment by lakohl** [comment]
@shanear was this implemented?

**Comment by mmlumba** [comment]
Hi @KHarshawat I'm working on this issue and I've tried to replicate the screenshot above, but can't seem to get the font right (this is on Chrome): 
<img width="1271" alt="screen shot 2016-12-07 at 11 07 03 am" src="https://cloud.githubusercontent.com/assets/4773320/20975397/660db600-bc6d-11e6-89a5-6a9a0ec9ec3c.png">
I think there's an issue with font inheritance but I'm not too sure. Thoughts?

**Comment by shanear** [comment]
@mmlumba, I think this is fine. @lakohl can take a look

**Comment by lakohl** [comment]
@mmlumba I spoke to Kavi and we decided that the best approach is to replicate the code used in the existing error messages that use Caseflow Commons. Right now the fonts aren't displaying correctly, but if we take that approach when we fix it - it will fix it across all the errors.

**Comment by shanear** [comment]
👍

**Comment by astewarttistatech** [comment]
Doesn't match the images posted prior, but this is what is currently on efolder's unauthorized page. 

Please see attached. 
<img width="1232" alt="screen shot 2016-12-07 at 4 14 02 pm" src="https://cloud.githubusercontent.com/assets/23038505/20986869/616f64b0-bc98-11e6-8ac7-e8587da68b5f.png">

@KHarshawat @mmlumba is this correct?

**Comment by lakohl** [comment]
@astewarttistatech good catch. @mmlumba I apologize, the confusion is my fault. I said error messages above, but what I intended was for you to use the styling of the other 'unauthorized user' messages that employ Caseflow Commons (they look more like the screenshots above). bad effect of multi-tasking :(

**Comment by mmlumba** [comment]
@lakohl I fixed the issue so it looks like the below screenshot:
![screen shot 2016-12-08 at 9 26 14 am](https://cloud.githubusercontent.com/assets/4773320/21013809/5c94a982-bd29-11e6-9a5e-6a01f4d06a9f.png)

**Comment by astewarttistatech** [comment]
**PASSED** 

Please see attached for the view in Dev. 
<img width="1378" alt="screen shot 2016-12-08 at 10 11 50 am" src="https://cloud.githubusercontent.com/assets/23038505/21015165/ea2021dc-bd2e-11e6-8ecb-daa441f196c2.png">
