### ISSUE TITLE
Logo | Should have multiply transparency

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#290]
The way the caseflow logo was originally designed was to show overlay between the grey and the colored sections of the logo.  This is probably because the asset we're using was not exported correctly.

**Environment:**
- [x] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Screen Shots
**_View - Correct Logo_**
![image](https://cloud.githubusercontent.com/assets/6335546/20285874/2c8ef07a-aa92-11e6-8f36-f52c2496ee4b.png)

**_View - Incorrect Logo_** 
![image](https://cloud.githubusercontent.com/assets/6335546/20285857/10b533aa-aa92-11e6-9c56-820f61fccee0.png)

**Comment by KHarshawat** [comment]
Same for the loading icon logo:

![image](https://cloud.githubusercontent.com/assets/6335546/20285908/58079590-aa92-11e6-9e67-119c9a3be702.png)

**Comment by shanear** [comment]
lol :upside_down_face:
