### ISSUE TITLE
Search Manifest | Last row in a table should not have a border bottom

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#291]
The last row of the table on the Search Manifest and Retrieve Manifest pages should not have a bottom border or blank row in it's tables.

**Environment:**
- [x] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
### Reproduction Steps
1. Enter a Veteran ID.
1. Click the Search button.
1. On Search Manifest page in the table listing of the files, the very last row is blank.
1. Click on the Start retrieving eFolder button.
1. On the Retrieval Manifest page, Completed tab, the last row in the table listing of files is blank. 

### Search Manifest
![291 - blank bottom row](https://cloud.githubusercontent.com/assets/23063044/20737798/11684f7a-b67d-11e6-9416-9dd47a93a68f.PNG)

### Retrieval  Manifest
![291 - retrieval manifest - blank bottom row](https://cloud.githubusercontent.com/assets/23063044/20738898/8e6efba2-b684-11e6-92d6-9cb02203894c.PNG)

**Comment by nikitarockz** [comment]
@KHarshawat Is the extra space/box that you are referring to the same ones I have in my screen shots above?  It actually looks like this blank row shows on 2 pages.

**Comment by KHarshawat** [comment]
Yes that's correct @nikitarockz

**Comment by aroltsch** [comment]
Fixed.
