### ISSUE TITLE
Remove <br> from success message

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#292]
Before:
![image](https://cloud.githubusercontent.com/assets/6335546/20286557/3c8e37f8-aa95-11e6-943e-416e10aab2d0.png)

Remove `<br>` from HTML here. It adds excessive padding between the text and the button on this alert.

![image](https://cloud.githubusercontent.com/assets/6335546/20286571/589685e0-aa95-11e6-9d51-505931946f1a.png)

After:
![image](https://cloud.githubusercontent.com/assets/6335546/20286595/730503b6-aa95-11e6-9dca-f93ec5f14360.png)

**Comment by astewarttistatech** [comment]
**PASSED** 

Please see attached.
![screen shot 2016-12-14 at 3 20 12 pm](https://cloud.githubusercontent.com/assets/23038505/21199357/35e1862e-c211-11e6-80f3-d9ecacf89041.png)
