### ISSUE TITLE
Change "Feedback" link in dropdown and footer to point to Caseflow-feedback

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#300]
As a user, I want to leave feedback in the Caseflow App.

### Acceptance Criteria
- Verify that when you click on "Send Feedback" in the header bar it redirects to Caseflow Feedback form, configured to leave feedback for eFolder Express

### Techincal Notes
- This should be behind a feature flag that enables the feature only on dev.
- We shouldn't be storing app name/url mappings in Feedback, just have Caseflow pass the app name as a url param

Some thing like this:
`feedbacks/new?app_name=eFolder Express`

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. 
<img width="1356" alt="screen shot 2016-12-06 at 11 04 29 am" src="https://cloud.githubusercontent.com/assets/23038505/20932785/d5ef058e-bba3-11e6-8c74-f0a3f2eb96ba.png">
