### ISSUE TITLE
Record email addresses of users that downloaded each file

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#301]
As  a site administrator, I want to know the email addresses of the user of each eFolder download

### Acceptance Criteria
- Verify that after initiating a download, the user's email address is recorded on that download for the logged in user
- Verify that you can see the users email address in the "Most Active Users" part of stats page.

### Technical Notes
- We may want a users table. Or we may not, because that's a lot of notes. Part of this story will be weighting the pros and cons of that.

**Comment by nemodjuric** [comment]
@shanear We can add a Users table or we can add it to Searches table (that already contains user_id column). What are your thoughts?

**Comment by shanear** [comment]
I think i'd be easier to just add it to searches. @amprokop what do you think?

**Comment by aroltsch** [comment]
Decided to add `email` to the `searches` table. In the future, we might create `users` table.

**Comment by aroltsch** [comment]
"Most Active Users" tab will include user's email, id and station ID. If email is not recorded, display "No Email Recorded". Example:
`test@example.com (CSFLOW3567 - Station 283)`
`No Email Recorded (CSFLOW7654 - Station 765)`

**Comment by kierachell** [comment]
Shows email when present; No email validation; Empty emails might be saved as blank in the DB so the "No Email Recorded" never shows.

**Comment by shanear** [comment]
@kierachell emails come directly from CSS in UAT, and thus they will not be blank. So we will go ahead and deploy this and test the "No Email Recorded" issue in UAT.

**Comment by shanear** [comment]
Confirmed that "No Email Recorded" is working correctly
