### ISSUE TITLE
OGC Contractors report that eX file count differs from VBMS

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#304]
Received a note from Upul an OGC contractor stating that the efolder file count he saw in VBMS differd from the one he got from eX. More detailed correspondence below.

## Related Issue  
**Product Support Issue** - File Retrieval: OGC Contractors report that eX file count differs from VBMS - [#8](https://github.com/department-of-veterans-affairs/appeals-support/issues/8)

**Comment by lakohl** [comment]
Below is the transcript of a series of emails I received on 12/1/16. (The latest one is at the bottom.)
Not entirely sure what to make of it, so pasting the whole thing here.

**1. from Upul Ratnayake, Upul.Ratnayake@va.gov (He's and OGC contractor who participated in the eX pilot).**

FYI. We have noticed different file count in VBMS and eFolder . Some cases have one or two files extra in eFolder.
 
16-3721 VBMS has 681 and eFolder has 682
16-3711 VBMS has 1374 and eFolder has 1376

**2. Response from Kevin Lovett, Kevin.Lovett@va.gov (I don't know him but he is a Lead Clerk at OGC.)**

16-3721 VBMS has 681 and eFolder has 682 – Seems to be an error from the scanning facility. There numerous documents postdating the Board decision on 7/19/2016 which would account for the difference in the document count at the time of original scanning and would also make these documents  irrelevant to the case. I have reviewed the documents uploaded after the BVA decision and did not see any that should predate the decision. I suggest start with BVA decision of 7/19/2016 and include everything that predates it.
 
16-3711 VBMS has 1374 and eFolder has 1376 – There is no discrepancy in the document count in VBMS. The document counts are the same (1,374).'

**3. Follow up from Upul:**
Can you please check the attached screenshots. ( I can share these over Lync).

**4. Response from Kevin L.**
Upul, I see what you are stating. It appears that there are two documents uploaded after the BVA decision and were not calculated upon the upload. That would give you the 1376 actual documents. Remember please start with the BVA decision.

**5. From Upul:**
Found another discrepancy in the document count (16-3732 )

**6. From Kevin L.**
There are 14 duplicates uploaded that would give you the 426 instead of 412.

**Comment by lakohl** [comment]
Screenshots for above.
[Case1.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/628283/Case1.pdf)
[Case2.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/628284/Case2.pdf)

**Comment by lakohl** [comment]
I can share case numbers over Lync.

**Comment by askldjd** [comment]
Got a few questions:
 1. Which environment is this?
 1. Are they saying the discrepancy is our fault?
 1. What is the priority of this bug?

**Comment by nikitarockz** [comment]
@Sjones352 @RTOLSON @askldjd  I have place some new labels on this issue and it can now be surfaced to the triage level (not get lost in the fold).  This will become smoother as the Product Support starts implementing their process.  Secondly, those are great questions because those are the same ones I need answered as well.

**Comment by lakohl** [comment]
@askldjd I answered your questions inline above

**Comment by paultag** [comment]
FWIW, back in the olden days, they were busy trying to figure out how to filter responses to us. 

You might consider looking what Caseflow's security number thing (security level?) is, and what the user using VBMS directly's security level is, as well as what the security level for the veteran is. 

cc @gmorgana-va who did the talking with the VBMS team

**Comment by askldjd** [comment]
Moving issue to https://github.com/department-of-veterans-affairs/appeals-pm/issues/1034 because there are new prod level information (sensitive). I would closing the issue here to consolidate the information.

**Comment by orischwartz** [comment]
When this came up in the past it was due to the API returning a meta-data document type in XML.

Cross referencing related issues:

* Determine if there are more metadata XML document types that shouldn't be returned to user #212
* Filter out XML document types #211

**Comment by askldjd** [comment]
Update: reopening this issue for developer tracking purposes.

**Comment by lakohl** [comment]
Once this issue is resolved we should alert OGC: Brian-Eric.Henderson@va.gov, Upul.Ratnayake@va.gov, Kevin.Lovett@va.gov

**Comment by nikitarockz** [comment]
@askldjd Thank you Alan.  I was going to do the same.  In the first comment, I have add the link to the official support ticket which will be tracked on the PM board.

**Comment by askldjd** [comment]
@shanear and I looked into the specific download (1117) that covers one of the cases with discrepancy. At a glance, all file id are unique. There are two document with empty filename, but that doesn't account for the file count discrepancy that we are looking for. The next step is to record the VBMS `ListDocument` output and have VBMS team explain the discrepancy.

Unfortunately, the only way to debug this is in prod. I will be doing this in prod in the after hours.

**Comment by shanear** [comment]
More reports of this in feedback:

<img width="936" alt="screen shot 2017-01-12 at 9 37 20 am" src="https://cloud.githubusercontent.com/assets/1596259/21893860/e341f4fc-d8aa-11e6-9e5a-8bd8f0e4fc1e.png">

**Comment by askldjd** [comment]
@amprokop Any update on this issue? If we are completely blocked, maybe we need to escalate this to @ariperez.

**Comment by amprokop** [comment]
@askldjd — I followed up this morning, and cc:ed you and @ariperez on the email chain. Also I called you our "Senior Technical Architect" to make it sound important :)

**Comment by askldjd** [comment]
Haha, I love the title inflation.

**Comment by askldjd** [comment]
Just additional information:
@amprokop filed VBMS Ticket I12420045FY17 on Jan 25th, and there has been no update.

**Comment by amprokop** [comment]
I asked for another update today. @shanear jumped in last week with an additional clarification, and the ticket was transferred back to a Tier 3 resource. I have given them my phone number and email.

http://vaww.sdm23127.nsd.va.gov/CAisd/pdmweb1.exe

**Comment by amprokop** [comment]
""After speaking with our next level of support, we have concluded the following: With respect to the first veteran initially referred to as an invalidated example in his first comment and attachment, the document type "VA 21-6798 Disability Award" is considered a restricted document type, only visible to users with the role of "Fiduciary." This accounts for the discrepancy between VBMS and eFolder express as there are 9 documents of this type for this veteran -- this is the difference between eFolder Express compared to the VBMS eFolder. Therefore, this issue is a perceived discrepancy only -- attributable to VBMS document level security policy -- and not an actual one.  This is attributable to document level security -- a required feature in VBMS -- and not missing documents etc.Should you have any questions, please contact VBMS Tier 2 Support or simply reply to this email."

**Comment by amprokop** [comment]
VBMS support team has told us that in at least one case, it's permissions discrepancy. Next step is to actually try the download and verify that the discrepant files appear in the eX download. In either case, we'll close this issue aim to resolve this with the VBMS API upgrade to v5.

**Comment by kierachell** [comment]
See if the API we use pulls archived/restricted documents. It might be that eFolder user access and VBMS user access is different

**Comment by amprokop** [comment]
Removing myself as an assignee for now, opened #410.

**Comment by shanear** [comment]
@amprokop can we close this one then? what other issues are there?

**Comment by shanear** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/427

It was determined that fiduciary docs were the only reason for the differing counts
