### ISSUE TITLE
Create a test endpoint that deletes a cached eFolder

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#306]
In order to write a repeatable external automated test against UAT, we'll need to have an endpoint that deletes an eFolder from the cache, so we can ensure that we are testing the VBMS upload, and not just retrieving a cached file.

This pattern of Data resets is one that will have to be repeated for other automated tests. Would be good to have opinions on how we should tackle this.

**Comment by shanear** [comment]
After speaking with @askldjd, the current plan is to set a test user id in ansible, that user is allowed to delete all data associated with themselves.

**Comment by kierachell** [comment]
Should this just be limited to `dev` and `test` - that way we don't have to hardcode the user.
The access to a specific download is already authorized by session, right?

**Comment by kierachell** [comment]
@ashmahm or someone can check the functionality on `UAT`/`Prod`

**Comment by kierachell** [comment]
Ok; I just checked it against our testing eFolder in UAT AND IT WORKS
