### ISSUE TITLE
Allow ruby-bgs logging configurations to be specified

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#310]
Currently, Savon library outputs all request and responses to stdout. Since the file contain sensitive information, the following enhancements are needed:

- [ ] Do not output raw req/resp in stdout. Instead, output the information on a specific file based on configuration.
- [ ] Allow raw req/res logging to be enabled or disabled based on configuration.

While the issue is captured in efolder, the code change may occur in ruby_bgs gem.

**Comment by aroltsch** [comment]
Closing as it is no longer a problem.
