### ISSUE TITLE
Investigate why Savon (SOAPFault) exceptions are not logged.

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#311]
From the efolder outage (https://github.com/department-of-veterans-affairs/appeals-deployment/issues/270), we notice that the `SOAPFault` from ruby_bgs is not being logged in cloudwatch. Because of this, we wasted a lot of engineering time chasing the wrong issues.

At a glance, ruby-bgs is re-throwing this error (https://github.com/department-of-veterans-affairs/ruby-bgs/blob/master/lib/bgs/base.rb#L110).

**Comment by shanear** [comment]
closing in favor of:
https://github.com/department-of-veterans-affairs/ruby-bgs/issues/20
