### ISSUE TITLE
Support "Out of Service" mode

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#312]
As a developer, when external dependencies go down, we need to quickly declare the application to be out of service. Ideally, if `OUT_OF_SERVICE` is defined, it will prevent user from making changes to the site.

## Acceptance Criteria
1. Verify that, when the out-of-service mechanism is engaged, visiting any part of the site renders the following mock instead of the entered url. It should say "Please check back in a little bit." instead of "Please stand by."
    ![technical difficulties](https://cloud.githubusercontent.com/assets/25437276/22708140/3b15fbfe-ed43-11e6-9398-a5cd928d4d7e.png)

## Notes
- This exact same mock and mechanism will be used in caseflow, so putting the html and css in commons might be useful.
- See also https://github.com/department-of-veterans-affairs/appeals-deployment/issues/270

**Comment by KHarshawat-gov** [comment]
![technical difficulties](https://cloud.githubusercontent.com/assets/25437276/22708140/3b15fbfe-ed43-11e6-9398-a5cd928d4d7e.png)

If we can auto-reload the page when the issue is resolved then we should say "Please stand by" in the text above. Otherwise we should change the text to "Please check back in a little bit."

**Comment by KHarshawat-gov** [comment]
cc/ @lakohl for awareness

**Comment by lakohl** [comment]
Thanks @KHarshawat-gov

**Comment by shanear** [comment]
@KHarshawat-gov should we allow a customized message?

**Comment by KHarshawat-gov** [comment]
@shanear I would say no for this one because presumably the entire app wouldn't work and the only thing I would customize is a link to the homepage which wouldn't work in this instance.

**Comment by nemodjuric** [comment]
Prerequisite to this: #392

**Comment by kierachell** [comment]
**PASSED**

validated in `preprod`

The design is incorrect, but @KHarshawat-gov didn't catch it ;)
<img width="1056" alt="screen shot 2017-03-03 at 3 22 41 pm" src="https://cloud.githubusercontent.com/assets/18075411/23567724/aaf01564-0025-11e7-81e1-d54c5c3a040a.png">
