### ISSUE TITLE
Create "users" table in eFolder Express

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#325]
1. Add `css_id` in `searches` and `downloads` table. Duplicate `user_id` to `css_id`.
2. Create `users` table with the following columns: id, station_id, css_id, email. Migrate data into the `users` table. Populate `user_id` with the id from the `users` table
3. Change code to use `users` table

**Comment by aroltsch** [comment]
Tech Details: 
1st PR should:

add css_id to both searches and downloads
migrate all values in user_id to css_id
write both css_id and user_id in new downloads and searches.
The next PR should:

remove all references to user_id in the code, replacing them with css_id
The 3rd PR should:

remove the user_id column.
The 4th PR should:

Add the users table.
Add user_id column back to both searches and downloads as an integer
Begin writing new users to the users table, and adding the appropriate user_id value to new searches and downloads.
Migrate all css_id and station_id on downloads and searches to the users table, and add the appropriate user_id to each row.
The 5th PR should:

Remove all references to css_id and station_id on the downloads or searches table.
The 6th PR should:

Remove the css_id and station_id column from downloads and searches

**Comment by kierachell** [comment]
The functionality has not changed for `dev`/`demo`; however, (as you've already experienced) `prod` can be a different story.
Needs @shanear 's validation.

**Comment by shanear** [comment]
validated in prod. Nice work @aroltsch !
