### ISSUE TITLE
Use standard loading button when clicking search button

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#327]
Currently when you click the search icon, we show the following.

![image](https://cloud.githubusercontent.com/assets/6335546/21357860/d83c176c-c6a4-11e6-9b6b-f3b6e7834d13.png)

Instead we should use the following as described in the style guide

![image](https://cloud.githubusercontent.com/assets/6335546/21358168/dd9caf90-c6a5-11e6-8cbd-1ea31452bbdd.png)

The logo should animate just like the loading icon when documents are being fetch from the manifest. The CSS to do this animation is in here: https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/app/assets/stylesheets/caseflow_main.scss

The color of the logo should be `grey-dark`.

**Comment by slj** [comment]
The search button is already styled properly.  Once clicked, the user currently sees this:

![efolderloading](https://cloud.githubusercontent.com/assets/1053255/22745018/229881dc-eded-11e6-861b-efe38dc4b120.gif)

Do we really gain from changing this?  @mmlumba, @KHarshawat I value your thoughts.

**Comment by slj** [comment]
A previous commit already renders the **Submit** button in the recommended style.

I created some CSS rules to make the caseflow logo spin on top a disabled button, but I don't know how to test this, or if we should even bother.   The **Submit** button fires off a request to `/downloads`, so we're leaving the view immediately and getting the view I mentioned above.  @mmlumba mentioned that there may be cases where something goes wrong and the original view is not left, but in that case it's better, IMO, to keep the blue **Search** button present.

Based on this, I recommend we close this ticket.

**Comment by slj** [comment]
Closing with consent from @lakohl

**Comment by kierachell** [comment]
![efolderloader](https://cloud.githubusercontent.com/assets/18075411/22897150/a05014e4-f1f0-11e6-9226-a779593eb000.gif)

Need clarification from @Chingujo or @KHarshawat about the specific color of the loading animation - unable to find `grey-dark` in US Web Design standards.

**Comment by Chingujo** [comment]
"gray dark" which is #323a45

**Comment by slj** [comment]
@kierachell the logo should now render well across browsers.  Here's a snip from the logo's SVG:
```
inkscape:connector-curvature="0"
       style="fill:#323a45;fill-opacity:1;fill-rule:evenodd;stroke-width:1" />
    <path
       style="mix-blend-mode:multiply;fill:#323a45;fill-opacity:1;fill-rule:evenodd;stroke-width:1"
       id="Fill-12-7-4"
```
which uses the gray defined/confirmed by @Chingujo.

**Comment by slj** [comment]
@kierachell please note that "Loading..." will appear beside the icon as specified by the Style Guide:

![loadingwicon](https://cloud.githubusercontent.com/assets/1053255/22947194/0f9132ac-f2c8-11e6-87de-94b9c4a1aded.gif)

**Comment by kierachell** [comment]
**PASSED**
validated in `UAT`
![loadefoldersearch](https://cloud.githubusercontent.com/assets/18075411/22985037/3c666934-f375-11e6-8728-7570d92325f9.png)
