### ISSUE TITLE
Fix off-by-one pixel on tabs

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#328]
As you can see in the screenshot below, the left most side of the tabs is not aligned with the rest of the table. the blue border should align with the border below it.

![image](https://cloud.githubusercontent.com/assets/6335546/21358757/bb87e44a-c6a7-11e6-85b3-fa8eeb679851.png)

**Comment by slj** [comment]
The last tab is also off:
![pixelproblem2](https://cloud.githubusercontent.com/assets/1053255/22654689/a1ff9138-ec5b-11e6-8f3f-9ee3c3320221.png)

**Comment by slj** [comment]
Fixed in https://github.com/department-of-veterans-affairs/caseflow-commons/tree/issue-fix-off-by-one-pixel-on-tabs; issued pull request to @mmlumba

**Comment by slj** [comment]
Approved by @mmlumba / merged into master.

**Comment by astewarttistatech** [comment]
Current view: 
<img width="742" alt="screen shot 2017-02-07 at 8 28 34 am" src="https://cloud.githubusercontent.com/assets/23038505/22693004/77ec5e80-ed0f-11e6-91b3-7e95ab96564c.png">

Moving back to In Progress @slj

**Comment by slj** [comment]
Thx.  Investigating...

**Comment by kierachell** [comment]
<img width="1036" alt="screen shot 2017-02-07 at 10 52 58" src="https://cloud.githubusercontent.com/assets/18075411/22698921/ec2ef5e6-ed23-11e6-91b8-06d0356d6a52.png">
👍

**Comment by astewarttistatech** [comment]
UAT matches the above screenshot.
