### ISSUE TITLE
Add right chevron to actions in history table

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#329]
Today the history table in eFolder express contains the "View results" action. 

![image](https://cloud.githubusercontent.com/assets/6335546/21358810/f2318424-c6a7-11e6-88f7-503c09149e87.png)

A right chevron ("»") should be added to these actions as is shown in the style guide.

![image](https://cloud.githubusercontent.com/assets/6335546/21358858/1d9c0e9a-c6a8-11e6-9590-8b57c5dbb609.png)

**Comment by mmlumba** [comment]
@KHarshawat Are there any other places in the Caseflow apps where the chevron is needed or just this table?

**Comment by KHarshawat-gov** [comment]
@mmlumba in addition to using them in tables occasionally i've used them in link buttons like the back button below the app canvas in certification. Now most of those are just `cancel` links.

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell Instructions for testing are in PR #374

**Comment by astewarttistatech** [comment]
**PASSED** 

Steps to Validate: 

1. Go to https://efolder.cf.uat.ds.va.gov/ *
2.* if there are efolders already downloaded, you can just look at the history directly.
3. Search and download a valid efolder 
4. Go back to the efolder.cf.uat.ds.va.gov/ page and view the history and see each efolder has the right chevron. 

Screenshots: 
<img width="1380" alt="screen shot 2017-02-03 at 11 31 36 am" src="https://cloud.githubusercontent.com/assets/23038505/22599357/a5f4318a-ea04-11e6-88fd-b8445de36caf.png">
