### ISSUE TITLE
page should stop polling (refresh) after failing to find a file

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#33]

**Comment by lakohl** [comment]
@orischwartz can you elaborate?

**Comment by shanear** [comment]
@lakohl this is a technical issue where the page continues to "poll" the server for updates to a download even after a download has errored.

A user wouldn't really notice that this was happening, it's just sloppy.

**Comment by lakohl** [comment]
got it @shanear
