### ISSUE TITLE
SPIKE | Look into document errors

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#330]
There are a bunch of errors happening in eFolder Express. We should look into what could be causing these.

<img width="372" alt="screen shot 2016-12-20 at 2 03 14 pm" src="https://cloud.githubusercontent.com/assets/1596259/21364131/84bdf718-c6bd-11e6-96be-6d63f02c530e.png">

**Comment by amprokop** [comment]
A sampling from Cloudwatch of errors during December:

``2016-12-01 23:44:15 UTC-5
I, [2016-12-01T23:44:15.428586 #2919] INFO -- : SOAP response (status 500)
2016-12-02 09:37:40 UTC-5
I, [2016-12-02T09:37:40.973926 #2919] INFO -- : SOAP response (status 500)
2016-12-02 10:39:50 UTC-5
I, [2016-12-02T10:39:50.315006 #2904] INFO -- : SOAP response (status 200)
2016-12-02 10:56:12 UTC-5
I, [2016-12-02T10:56:12.350006 #2904] INFO -- : SOAP response (status 200)
2016-12-02 20:39:42 UTC-5
I, [2016-12-02T20:39:42.391609 #2919] INFO -- : SOAP response (status 500)
2016-12-03 12:01:46 UTC-5
I, [2016-12-03T12:01:46.934518 #2919] INFO -- : SOAP response (status 500)
2016-12-05 12:22:17 UTC-5
I, [2016-12-05T12:22:17.224096 #2919] INFO -- : SOAP response (status 500)
2016-12-05 12:52:12 UTC-5
I, [2016-12-05T12:52:12.088730 #2919] INFO -- : SOAP response (status 500)
2016-12-05 13:54:31 UTC-5
I, [2016-12-05T13:54:31.652395 #2904] INFO -- : SOAP response (status 500)
2016-12-05 14:29:34 UTC-5
I, [2016-12-05T14:29:34.527550 #2919] INFO -- : SOAP response (status 500)
2016-12-05 17:52:59 UTC-5
I, [2016-12-05T17:52:59.805500 #2904] INFO -- : SOAP response (status 200)
2016-12-06 00:27:29 UTC-5
I, [2016-12-06T00:27:29.725007 #2919] INFO -- : SOAP response (status 200)
2016-12-06 08:36:19 UTC-5
I, [2016-12-06T08:36:19.688025 #2919] INFO -- : SOAP response (status 500)
2016-12-06 08:52:51 UTC-5
I, [2016-12-06T08:52:51.410883 #2919] INFO -- : SOAP response (status 500)
2016-12-06 19:25:52 UTC-5
I, [2016-12-06T19:25:52.277115 #2933] INFO -- : SOAP response (status 500)
2016-12-07 06:47:44 UTC-5
I, [2016-12-07T06:47:44.471244 #2933] INFO -- : SOAP response (status 500)
2016-12-07 06:47:45 UTC-5
I, [2016-12-07T06:47:45.610185 #2933] INFO -- : SOAP response (status 500)
2016-12-07 06:48:18 UTC-5
I, [2016-12-07T06:48:18.743832 #2933] INFO -- : SOAP response (status 500)
2016-12-07 06:48:19 UTC-5
I, [2016-12-07T06:48:19.864169 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:24:31 UTC-5
I, [2016-12-07T07:24:31.012730 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:24:32 UTC-5
I, [2016-12-07T07:24:32.533697 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:24:52 UTC-5
I, [2016-12-07T07:24:52.759259 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:24:53 UTC-5
I, [2016-12-07T07:24:53.886619 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:25:07 UTC-5
I, [2016-12-07T07:25:07.462346 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:25:08 UTC-5
I, [2016-12-07T07:25:08.547499 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:25:25 UTC-5
I, [2016-12-07T07:25:25.675781 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:25:26 UTC-5
I, [2016-12-07T07:25:26.764864 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:26:19 UTC-5
I, [2016-12-07T07:26:19.759774 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:26:20 UTC-5
I, [2016-12-07T07:26:20.839891 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:26:33 UTC-5
I, [2016-12-07T07:26:33.994529 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:26:34 UTC-5
I, [2016-12-07T07:26:34.908745 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:27:29 UTC-5
I, [2016-12-07T07:27:29.126706 #2933] INFO -- : SOAP response (status 500)
2016-12-07 07:27:30 UTC-5
I, [2016-12-07T07:27:30.071306 #2933] INFO -- : SOAP response (status 500)
2016-12-07 08:14:36 UTC-5
I, [2016-12-07T08:14:36.590769 #2933] INFO -- : SOAP response (status 500)
2016-12-07 08:14:37 UTC-5
I, [2016-12-07T08:14:37.670190 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:08:12 UTC-5
I, [2016-12-07T09:08:12.457692 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:08:13 UTC-5
I, [2016-12-07T09:08:13.588363 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:35 UTC-5
I, [2016-12-07T09:34:35.096075 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:36 UTC-5
I, [2016-12-07T09:34:36.398996 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:45 UTC-5
I, [2016-12-07T09:34:45.187471 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:46 UTC-5
I, [2016-12-07T09:34:46.276248 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:57 UTC-5
I, [2016-12-07T09:34:57.750659 #2933] INFO -- : SOAP response (status 500)
2016-12-07 09:34:59 UTC-5
I, [2016-12-07T09:34:59.076872 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:23:43 UTC-5
I, [2016-12-07T10:23:43.666736 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:23:45 UTC-5
I, [2016-12-07T10:23:45.251477 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:24:20 UTC-5
I, [2016-12-07T10:24:20.386089 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:24:22 UTC-5
I, [2016-12-07T10:24:22.079327 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:29:57 UTC-5
I, [2016-12-07T10:29:57.169691 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:29:59 UTC-5
I, [2016-12-07T10:29:59.276141 #2933] INFO -- : SOAP response (status 500)
2016-12-07 10:47:19 UTC-5
I, [2016-12-07T10:47:19.569162 #2933] INFO -- : SOAP response (status 500)
```

**Comment by amprokop** [comment]
The first one we found appears to be a permissions issue:
```
 [2016-12-01T23:44:15.428586 #2919] INFO -- : SOAP response (status 500)
2016-12-01 23:44:15 UTC-5
D, [2016-12-01T23:44:15.428672 #2919] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>This is a Sensitive Record and you do not have high enough access to update it</faultstring><detail><ns2:ShareException xmlns:ns2="http://services.share.benefits.vba.va.gov/"><message>This is a Sensitive Record and you do not have high enough access to update it</message></ns2:ShareException></detail></S:Fault></S:Body></S:Envelope>
```

**Comment by amprokop** [comment]
@nemodjuric and I are going to pursue a strategy of exporting all the logs to S3 from the AWS console.

See: http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3ExportTasksConsole.html

**Comment by nemodjuric** [comment]
There were about 50 soap error messages in December of two types(in opt/efolder-express/src/log/efolder-express.out):
- "This is a Sensitive Record and you do not have high enough access to update it"
- "Password has expired"
There was a lot of noise in logs due to old version of httpclient gem (look at #361).

**Comment by shanear** [comment]
@nemodjuric good work! I can take over from here 👍

**Comment by aroltsch** [comment]
* "This is a Sensitive Record and you do not have high enough access to update it"
* "Password has expired"

These ^^ are both BGS errors coming from findPersonByFileNumber.
