### ISSUE TITLE
More informative & better looking application error page for prod.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#338]
We should have a more informative error message in prod when there are application errors.

It currently looks like this:
<img width="1450" alt="screen shot 2017-01-02 at 10 22 38 am" src="https://cloud.githubusercontent.com/assets/1596259/21591813/97e02fa6-d0d5-11e6-9221-221830eef5e7.png">

**Comment by shanear** [comment]
@lakohl @KHarshawat any thoughts on this one?

**Comment by lakohl** [comment]
Happy to help, could you provide me some more context as to when a user might see this?

**Comment by shanear** [comment]
@lakohl They'll see it for any random error that occurs in caseflow. It's the caseflow equivalent of this:

https://github.com/500

**Comment by KHarshawat-gov** [comment]
@shanear here's a mockup of what the message should look like.

![generic 500](https://cloud.githubusercontent.com/assets/25437276/22709198/f8c4d758-ed46-11e6-88c5-bb29908296d9.png)

**Comment by KHarshawat-gov** [comment]
cc/ @lakohl for awareness

**Comment by aroltsch** [comment]
This is done.
