### ISSUE TITLE
GetDownloadManifestJob doesn't handle VBMS::ClientError

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#35]
silently swallows exceptions and sets download status to no documents.

**Comment by orischwartz** [comment]
@shanear Any thoughts on this? Does ruby have [nested exceptions](http://www.skorks.com/2013/04/ruby-why-u-no-have-nested-exceptions/)?

**Comment by shanear** [comment]
ahh, yeah we should log the exception, but not shut down the job.
