### ISSUE TITLE
File Retrival | Download counts is inaccurate on re-download

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#353]
Steps to reproduce:

1. Download a efolder.
2. After the efolder is downloaded, redownload the efolder. On second download, the remaining download count is inaccurate.

E.g. In this download, 48 files have been completed, yet it shows 26 completed on the status.
<img width="1094" alt="screen shot 2017-01-09 at 3 35 13 pm" src="https://cloud.githubusercontent.com/assets/3258724/21782511/b17d0266-d681-11e6-9c8b-2f2774d472a3.png">

**Comment by aroltsch** [comment]
re: testing, on Demo, you can use "DEMO3" download. It will download documents with errors.

**Comment by kierachell** [comment]
As far as `DEMO3` folder goes the retrieved amounts are the same upon repeated attempts (20 total, 15 retrieved, 5 errors):
<img width="1017" alt="screen shot 2017-01-31 at 08 18 28" src="https://cloud.githubusercontent.com/assets/18075411/22466425/30c1e2d6-e78e-11e6-9c81-99ec3b855c01.png">

If downloaded, the resulting .zip file has 16 (not 15) documents:
<img width="228" alt="screen shot 2017-01-31 at 08 19 25" src="https://cloud.githubusercontent.com/assets/18075411/22466444/482b22ca-e78e-11e6-90ba-059d8a48869f.png">

Subsequent retrieval will update the amount of files to 16 out of 20:
<img width="1023" alt="screen shot 2017-01-31 at 08 21 08" src="https://cloud.githubusercontent.com/assets/18075411/22466466/580f887a-e78e-11e6-9a1b-3aaa7fdc9043.png">

Seems like a bug.

**Comment by kierachell** [comment]
Now with `DEMO2` folder (100 documents):
<img width="996" alt="screen shot 2017-01-31 at 08 28 08" src="https://cloud.githubusercontent.com/assets/18075411/22466694/7233f28a-e78f-11e6-8be6-52d997e826dc.png">
<img width="466" alt="screen shot 2017-01-31 at 08 28 28" src="https://cloud.githubusercontent.com/assets/18075411/22466695/7233f0f0-e78f-11e6-9e46-e9d8d4d4daf7.png">
Redownloading the folder produces the same results 100 documents.

**Comment by kierachell** [comment]
Now for `DEMO4`:
<img width="1035" alt="screen shot 2017-01-31 at 08 40 10" src="https://cloud.githubusercontent.com/assets/18075411/22467068/1c42e69a-e791-11e6-8663-35d5e9f06e27.png">
<img width="729" alt="screen shot 2017-01-31 at 08 40 43" src="https://cloud.githubusercontent.com/assets/18075411/22467067/1c3ffea8-e791-11e6-84e9-9570355aef81.png">
Seems fine like `DEMO2`
Counts are correct on repeated downloads.

**Comment by kierachell** [comment]
While the error counts are randomized, there was one case where Retrieved amount did not match Downloaded amount.

If that is not the issue, update the criteria.

**Comment by kierachell** [comment]
As far as eFolders on UAT:
was able to redownload a folder with 125 files, each time correct file counts on all pages and in ZIP:
<img width="1021" alt="screen shot 2017-02-03 at 9 05 33 am" src="https://cloud.githubusercontent.com/assets/18075411/22594511/57067c76-e9f1-11e6-8056-503c81ab17a9.png">
<img width="1002" alt="screen shot 2017-02-03 at 9 05 47 am" src="https://cloud.githubusercontent.com/assets/18075411/22594513/572d4b44-e9f1-11e6-98dd-3fd0464b23b1.png">
<img width="1034" alt="screen shot 2017-02-03 at 9 08 04 am" src="https://cloud.githubusercontent.com/assets/18075411/22594512/571c68a6-e9f1-11e6-8d07-42676d00438d.png">
<img width="1012" alt="screen shot 2017-02-03 at 9 09 29 am" src="https://cloud.githubusercontent.com/assets/18075411/22594509/570552b0-e9f1-11e6-94e4-67dd4ee5381e.png">
<img width="1028" alt="screen shot 2017-02-03 at 9 10 18 am" src="https://cloud.githubusercontent.com/assets/18075411/22594510/5705c6a0-e9f1-11e6-97ab-dc5058ac7e27.png">
<img width="975" alt="screen shot 2017-02-03 at 9 10 30 am" src="https://cloud.githubusercontent.com/assets/18075411/22594508/57030e6a-e9f1-11e6-80ac-70ebccfa70a5.png">
