### ISSUE TITLE
efolder is leaking disk space in its /tmp folder

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#354]
efolder writes all downloaded files into `rails.root/tmp` folder. However, there is no job to clean up this folder. Over time, we run out of disk space.

![image](https://cloud.githubusercontent.com/assets/3258724/21791463/e75c7108-d6b0-11e6-87d2-936398110f15.png)

@shanear

**Comment by shanear** [comment]
I'm thinking a two pronged approach to this:
1) Clean up all files after they're zipped up.
2) Daily job that cleans `\tmp` at midnight.

Thoughts @askldjd?

**Comment by askldjd** [comment]
Complete agreed with 1.

For 2, do we have data on when is a quiet period? Just based on my personal experience, ~3am EST seems to be a better pick.

**Comment by shanear** [comment]
@askldjd good call. I just chose midnight because I assumed it was a quiet period. I'll go ahead and set it up for 3am and then do some probing to see the best time.

**Comment by kierachell** [comment]
I set an alarm for myself to validate this at 2:59am :D

**Comment by askldjd** [comment]
Looks like the pdfs are deleted, but the zip files remains until the next clean up schedule (3am). If this is expected, then the issue is resolved.
