### ISSUE TITLE
Downloads w/ status packaging_contents: 4 will never be restarted by RestartStalledDownloadsJob

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#356]
`RestartStalledDownloadsJob` loads all downloads w/ status 3,4 (pending documents and packaging contents) :
```ruby
    Download.where(status: [3, 4]).each do |download|
      start_download_files(download) if download.stalled?
    end
```

It then further filers out just downloads that match `stalled?`.

```ruby
  def stalled?
    pending_documents? && ((Time.zone.now - TIMEOUT) > updated_at)
  end
```

But `stalled?` only returns true if the download is `pending_documents?`, which contradicts the initial intent to filter both the `pending_documents` and `packaging_contents` status: 

```ruby
Download.where(status: [3, 4])
```

As first reported by @Sjones352 . cc @joofsh and @askldjd

**Comment by alisan16** [comment]
This hasn't been updated in over 3 years. Closing.
