### ISSUE TITLE
Add Prometheus client to efolder

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#362]
Add prometheus client to efolder to track HTTP request rate and latency.
https://github.com/prometheus/client_ruby

The setup should be similar to Caseflow.

## AC:

- Going to eFolder's `/metrics` page (credentials under Prometheus scraper in 1password) should display gauges and summaries for:
  - VBMS requests 
  - BGS requests
  - VVA requests
  - Background Jobs

- If the metrics don't show up, try 
  - refreshing the page
  - Searching/Fetching/Downloading some documents
  - Calling the API endpoints

- Sample format:
```
bgs_request_latency_gauge{app="eFolder",name="veteran.find_by_file_number"} 1.1974508579999963
# TYPE bgs_request_latency_summary summary
# HELP bgs_request_latency_summary latency of completed BGS requests
bgs_request_latency_summary{app="eFolder",name="veteran.find_by_file_number",quantile="0.5"} 1.1974508579999963
bgs_request_latency_summary{app="eFolder",name="veteran.find_by_file_number",quantile="0.9"} 1.1974508579999963
bgs_request_latency_summary{app="eFolder",name="veteran.find_by_file_number",quantile="0.99"} 1.1974508579999963
bgs_request_latency_summary_sum{app="eFolder",name="veteran.find_by_file_number"} 2.124837057999997
bgs_request_latency_summary_count{app="eFolder",name="veteran.find_by_file_number"} 2
```
```

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access /metrics page for eFolder
2. Search "VBMS" "BGS" and "VVA" requests

Screenshots: 
<img width="1077" alt="screen shot 2017-08-09 at 12 49 12 pm" src="https://user-images.githubusercontent.com/23038505/29133700-5521eab8-7d02-11e7-989e-bda866978c30.png">
<img width="996" alt="screen shot 2017-08-09 at 12 49 27 pm" src="https://user-images.githubusercontent.com/23038505/29133701-55230e16-7d02-11e7-9b1f-891999ade4dd.png">
<img width="1082" alt="screen shot 2017-08-09 at 12 50 47 pm" src="https://user-images.githubusercontent.com/23038505/29133699-551f0e10-7d02-11e7-99bd-086ee12a6850.png">
