### ISSUE TITLE
File Retrival | Download eFolder | Partial download of documents

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#366]
# Descripton
User expressed that Efolder did not pull all of the contents from a applicants file.  User explained that while downloading a file in Efolder Express, he noticed that the appeal has 383 documents in VBMS to be transferred and Efolder Express only captured and downloaded 162 documents and left the rest. At that point, there was nothing more that he could do with this case because of this discrepancy, so he canceled download and reported the issue.

**Environment:**
- [x] Production
- [ ] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Security
- [x] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproduction Steps
1. Enter Veteran ID and click the **_Search_** button on the `eX Home` page.
1. Click on the **_Start retrieving eFolder_** button on the `Manifest `page.
1. Click on the **_Download eFolder_** button on the `File Retrival` page.
1. Open the downloaded zip folder.
# Related Issues
**_Support Ticket_**
File Retrival: Partial download of docments [#16](https://github.com/department-of-veterans-affairs/appeals-support/issues/16)

**Comment by amprokop** [comment]
@nikitarockz — is it possible to follow up with this user and get the file #, so we can attempt to reproduce this?

**Comment by amprokop** [comment]
Unassigning myself as I'm not currently working on this. This seems like a different issue from the document type filtering we'll implement in https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/427, which I was working on.

**Comment by nikitarockz** [comment]
# Closing
Unable to obtain Case ID.  User who reported the issue has not been responsive.
