### ISSUE TITLE
Add an "All Time" tab to eFolder Express (and other) dashboards.

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#369]
We should add a running count of money saved daily, weekly, monthly to the eFolder express dashboard. We've calculated that it costs $.077 per document downloaded in the eFolder so we can multiple the total number of documents downloaded by that ammount to see what the cost savings were in that time period. 

We can add a new row under the "Errors per week" row and add a new bar chart using green as the primary color. The row should be titled "Money saved" and the chart title should be "Total Dollars saved". 

![image](https://cloud.githubusercontent.com/assets/6335546/22380729/7663df74-e48c-11e6-894d-14a86d643139.png)

Eventually we can break this out by RMC, and other FOIA offices.

**Comment by cmgiven** [comment]
We talked about this one a bit. Summary: I'm a bit trepidatious of bragging on a very back-of-the-napkin kind of number, particularly in this format without additional context and too much implied specificity.

Idea: What about a new "Cumulative" tab, which breaks the format of the other tabs, but can provide both 1) a lifetime picture of eFolder's impact, and 2) a space to describe, with all the necessary context, the value and story of eFolder. In addition to cumulative numbers, this might also be a place to describe which organizations are using eFolder and tell our roll-out story in more detail.
