### ISSUE TITLE
File Retrival | Download eFolder | Error Message | File names too long to extract in Windows

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#371]
# Description
Some filenames of either zip files or documents within the zips are too long to extract on Windows. We should fix this issue by shortening file names when necessary.

**Environment:**
- [x] Production
- [ ] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Security
- [x] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [x]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproduction Steps
1. Enter Veteran ID and click the **_Search_** button on the `eX Home` page.
1. Click on the **_Start retrieving eFolder_** button on the `Manifest `page.
1. Click on the **_Download eFolder_** button on the `File Retrival` page.
1. Open the downloaded zip folder.
# Related Issues
Zip Folder: Error Message: Unable to extract - file names too long  [#35](https://github.com/department-of-veterans-affairs/appeals-support/issues/35)

**Comment by nikitarockz** [comment]
# Sprint Planning
@nikitarockz Add feature information

**Comment by nemodjuric** [comment]
Was able to reproduce it on Windows 7 Service Pack 31.

**Comment by nemodjuric** [comment]
@ariperez-gov @KHarshawat-gov @shanear @lakohl 
The problem involves path length of the file which includes file name. Meaning, file name itself can be less than allowed Windows limit (255 characters in Windows 7 case), but it would still cause extracting error if the path is over the limit.
The file name from this case was around 192 characters (and folder path on user side probably over 63 characters). We can still make file names shorter, but it would have to be discussed in which exact manner.

**Comment by astewarttistatech** [comment]
**PASSED**

Tested in UAT on a Windows machine

Steps to Validate: 
1. Go into VBMS, select a vet
2. Upload a document with a really long file name. 
3. Go to eFolder express on UAT
4. Access the vet that was first accessed in VBMS
5. Validate that the same amount of documents is the same as what was in VBMS
6. Download efolder
7. Validate document uploaded has a changed filename. 

*Note:
The AC doesn't give a criteria to what the filename should be changed to.

Screenshots:
![validation](https://cloud.githubusercontent.com/assets/23038505/22896340/b862a180-f1ed-11e6-9efe-c347851abd5a.png)
