### ISSUE TITLE
Efolder client side polling is too aggressive, and leads to HTTP backup.

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#373]
When you try to search a VBMS ID in efolder, the first thing the application does is to fetch the document list in VBMS. During this period, `@download.fetching_manifest` is set. When this happens, client side javascript is set to poll for fetch status once per second using [`setInterval`](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/assets/javascripts/application/download_status.js#L19). This is too aggressive because `setInterval` fires regardless of server response time and network latency.

In my situation, my VA VPN network connection occasionally results in 2+ second response time, and therefore generated a lot of backed up HTTP requests. (see image)

When it gets really backed up, the page occasionally hangs.

This can be easily resolved by using `setTimeout` instead of `setInterval`, and only start a timer to poll when you receive a response from the server.

<img width="1199" alt="screen shot 2017-01-31 at 2 24 20 pm" src="https://cloud.githubusercontent.com/assets/3258724/22480903/0737f468-e7c1-11e6-8001-3a6585b36c8c.png">

Artem:
This might be related #375

**Comment by kierachell** [comment]
**PASSED**
checked the polling on `uat`... seems to timeout properly (save for slow networks)
