### ISSUE TITLE
Cannot log out of eFolder in IE | UAT

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow-efolder#376]
**Description** 

If logged into eFolder Express in UAT, when the user tries to log out via drop-down menu, the page reloads back to the homepage of eFolder Express. 

**Expected**

The user should be prompted to the SAML login page for eFolder Express with empty text fields. 

**Environment Found**: UAT

**Associated Issues/Stories**:

**Reported By:** Alexis Stewart

**Comment by shanear** [comment]
So CSS has a quirk where it wont let you logout for 30 minutes or so after you log in. Can you test logging out after having been logged in for 1hr?

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate:
1. Log into eFolder
2. Wait for 30+ minutes in order to log out
3. Successfully log out of Efolder.

 @wturne assisted me while testing this issue.
