### ISSUE TITLE
Connect Caseflow eFolder to Redis

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#392]
- [x] Deploy and configure a redis instance for certification https://github.com/department-of-veterans-affairs/appeals-deployment/issues/456
- [x] Add redis URL to deployment role (e.g., `REDIS_URL: "{{ redis_url }}"`)
- [x] Add a redis library to Gemfile
- [x] Modify [application.rb](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/config/application.rb#L30) to use a redis-backed `cache_store`

**Comment by nemodjuric** [comment]
Similar thing was done in Caseflow Certification:
https://github.com/department-of-veterans-affairs/caseflow/issues/313

**Comment by kierachell** [comment]
**PASSED**
validated on `uat` and `preprod`
