### ISSUE TITLE
Document changes to "secrets"

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-efolder#4]
(filepaths to change, etc)

**Comment by shanear** [comment]
@paultag can you explain what you mean by this?

**Comment by paultag** [comment]
Not actually needed anymore @shanear -- we're using a relpath now :D

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/config/secrets.yml

**Comment by paultag** [comment]
(I filed this before that was landed)
