### ISSUE TITLE
Stats | Update styling for header/title

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#401]
# Description
Current styling for eFolder stats dashboard is not consistent with other apps.
`need designer input`

**Environment:**
- [X] Production
- [X] UAT
- [X] Demo
- [X] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [X]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 - Visit eFolder stats page
1. Visit eFolder at `/stats`

1. Observe header and page title

## Screenshots
![screenshot_2017-02-25_12-50-19](https://cloud.githubusercontent.com/assets/18075411/23333417/070665aa-fb59-11e6-9976-b83b6249041b.png)
**versus**
![screenshot_2017-02-25_12-50-10](https://cloud.githubusercontent.com/assets/18075411/23333416/070561b4-fb59-11e6-9fec-048bc490084d.png)

# Related Issues
https://github.com/department-of-veterans-affairs/caseflow-commons/issues/19

**Comment by lakohl** [comment]
@kierachell are you saying that eX is the only app that has a header on the dashboard?

**Comment by lakohl** [comment]
a note: Our headers tend to be left aligned on other pages.
It does seem like a header would be useful here now that we are surfacing stats to the Dispatch manager.

**Comment by kierachell** [comment]
Correct: only **eFolder Express** has the title text **eFolder Express Dashboard**

**Comment by lakohl** [comment]
Style Guide Issue for this is here: https://github.com/department-of-veterans-affairs/caseflow/issues/1099

**Comment by gnakm** [comment]
This has been implemented: https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#dashboard
