### ISSUE TITLE
Ensure that a user can download documents from eFolder Express only if they have the correct user role

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#410]
We should ensure that eFolder Express users can only download documents if they have the permissions to access those documents in VBMS.

This issue results from the investigation of #304. We've found two file numbers where the VBMS eFolder and eFolder Express document counts didn't match for Nicholas Holtz's account, and both of them appear to be due to document level security—Nicholas's account doesn't have the role "Fiduciary", and these documents were only available to users with that role. Here, we break down a path forward to research & implement a fix.

- Determine that role discrepancy across VBMS/Caseflow is the main culprit for document # discrepancy issues
  - Ask support team to collect veteran IDs as they come in, and continue to look at them to determine which documents are missing
  - Can Artem and Alexis help with this? It needs to be someone with a VBMS prod account.
- Confirm that VBMS CSS roles determine VBMS document security policy.
  - According to @shanear, roles are scoped to their application—so VBMS and Caseflow have their own separate sets of roles. 
  - Can we read VBMS roles in eFolder Express?
  - Can we sync VBMS roles with eFolder Express roles somehow?
  - We might have to engage with both VBMS and CSS on this
- Find out how to determine what eFolder documents are only visible to users with certain roles
  - currently we use the `ListDocuments` service
  - Anya is currently working on integration of the `Read/findDocumentSeriesReference` service, so we'll be using that service by March
  - We will likely have to engage with VBMS on this
  - Here's some metadata from a document returned from VBMS `ListDocuments`. Do these properties determine document security policy? 
```
{ name = "metadata", value = "{\"userFacilityJob\":\"Fiduciary\",\"userSARL\":\"9\",\"restricted\":\"false\"}" })
```
- Only allow the Caseflow user to download documents if they would be able to do so in VBMS 
  - One possibility is to prefix cached S3 zip files by role 
  - e.g. `Fiduciary-Veteran_Name.zip` would contain all documents that are only visible to users with role "Fiduciary") and  `Veteran_Name.zip` would contain documents that are visible to all users
  - Then, if a user has the role "Fiduciary", that user would get the contents of both `Fiduciary-Veteran_Name.zip` and `Veteran_Name.zip`

**Comment by amprokop** [comment]
Assigning to @shanear so he can take a look and offer his thoughts async on this.

**Comment by shanear** [comment]
So I looked into the new eFolder service docs and there are only two roles that can restrict document types:

- Fiduciary
- Pension Management Center PMC

We need to know if any eFolder express users (FOIA officers, Attorneys) need access to these types of restricted documents. My guess is no. If that's the case, we can just outright toss out any documents with these restrictions.

**Comment by amprokop** [comment]
whooa @shanear — where did you look? in what document is this?

**Comment by nicholasholtz** [comment]
Sent: (POCs provided by VBA ISO)

From: Holtz, Nicholas B. 
Sent: Tuesday, March 07, 2017 3:23 PM
To: Sylvia, Lauren, VBAVACO; Bridges, Monte, VBAVACO
Subject: VBMS & the Common Security Services form - inquiry re: Appeals Modernization

Good afternoon, 
I am Counsel for Technology Integration with the Board of Veterans’ Appeals, and work closely with the Digital Service at VA as we are in the process of developing the Caseflow system for processing appeals, as part of Appeals Modernization. 

I am trying to track down what impact the selection of certain user roles on the Common Security Services form have on viewing restricted documents in VBMS. Specifically we came to realize that certain documents, such as documents with the label “Change of Address Fiduciary” are not visible to users with certain user roles, such as BVA Attorney. We believe there are other similar document types, possibly related to fiduciary concerns, that may impact visibility for other users.  Our goal is to ensure that those accessing documents through eFolder Express and other Caseflow web applications are seeing the appropriate documents, based on user roles.
 
Do you have a reference document that defines the various VBMS user roles/functions that are listed on the CSS form? If not, (or can you point me in the direction of someone who could provide that?
 
 ![image](https://cloud.githubusercontent.com/assets/16781398/23677956/27ad7042-0350-11e7-9fbd-0e0339b5995b.png)

Thank you!
 
Nicholas

**Comment by nicholasholtz** [comment]
In re-reading what you wrote, @shanear, I realize I may have been answering a different question, one you might already have the answer to. That being said, I was provided this document today, which may help in confirming information you've received:  http://vbaw.vba.va.gov/VBMS/docs/12.0.122_VBMS_Roles.pdf

I will look into the eFolder user question you asked.

@amprokop

**Comment by amprokop** [comment]
Even if eFolder Express users sometimes need those documents, can we add a note to the front page telling them that they have to download them from VBMS separately?

**Comment by nicholasholtz** [comment]
@amprokop The more I think about this, the less I think documents merely labeled "fiduciary" should be excluded. I don't actually know why they are excluded from VBMS views currently, as they are not Federal Taxpayer Information ("FTI", such as received from the IRS, which cannot be housed in VBMS at all). It is possible that they fall under restrictions I am not aware of though. 

I've asked for a complete document list from VBMS folks, so hopefully will be able to figure out a better answer soon.

**Comment by amprokop** [comment]
Thanks for helping us untangle this, @nicholasholtz!

**Comment by nicholasholtz** [comment]
Got a list of the restricted documents: (all documents - whether restricted is in the far right column)

[Master Document Type Categories August 2016.xlsx](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/828630/Master.Document.Type.Categories.August.2016.xlsx)

**Comment by nicholasholtz** [comment]
Re: Privacy/FOIA:

Spoke to VBA Privacy Officer, and learned the following: 

 - For FOIA, we have to be able to provide a valid legal reason not to provide a record that is relevant to the inquiry. 
 - For Privacy, if it is deemed to be a record of that Veteran, we have to provide it.
 - IVM is an exception, but as of now, no IVM documents are in VBMS; they are all stored in Virtual VA.

**Comment by nicholasholtz** [comment]
This might be old news, but placing it here for throroughness:

Higher Level Permissions
Some permissions are enforced at levels above the user role. For example, a user may have the permissions
to establish, authorize and award claims. However, users cannot both establish and authorize the same claim,
or authorize and award the same claim, due to permissions that are enforced at a higher level – in this case,
claim level permissions. Similarly, many user roles can edit claim information, but most non-supervisor users
can only do so for claims that have been assigned to them.
Important higher level permissions are:
 The currently active ruleset collection cannot be edited, including the rulesets that make up that
collection.
 Users cannot approve a ruleset collection that they submitted.
 Users can only stop or delete their own simulation jobs.
 No user can both establish and authorize the same claim, or authorize and award the same claim.
 Users with a coach role can edit team membership and team assignment rules, but only for their own
teams.
 POA users are granted permissions to view Veteran Profile information, but only for the Veterans they
represent.
 POA access to eFolder documents is granted or denied based on the wishes of the individual Veteran.
 Fiduciary users only have access to Fiduciary documents.
 PMC users only have access to IRS, SSA and IVM documents.
 Only Central Office Rep users can upload or edit Military Service documents.

http://vbaw.vba.va.gov/VBMS/docs/12.0.122_VBMS_Roles.pdf#3

**Comment by nicholasholtz** [comment]
Sensitivity and Access:
[Understanding Access Rules - VBMS User Guide Oct 2015.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/828718/Understanding.Access.Rules.-.VBMS.User.Guide.Oct.2015.pdf)

From that document:
![image](https://cloud.githubusercontent.com/assets/16781398/23719436/5cd24874-0409-11e7-9b4b-4e6d9ad0aa1a.png)
![image](https://cloud.githubusercontent.com/assets/16781398/23719439/675f4378-0409-11e7-920d-8210a07f51b9.png)

**Comment by amprokop** [comment]
Thanks, @nicholasholtz. There seem to be three of those items that affect interaction with eFolder documents:
```
 Fiduciary users only have access to Fiduciary documents.
 PMC users only have access to IRS, SSA and IVM documents.
 Only Central Office Rep users can upload or edit Military Service documents.
```
The Military Service documents rule doesn't apply to us since we only download documents, but it seems like filtering Fiduciary documents and PMC documents out of eFolder could still be the best fix we can make at this time.

**Comment by amprokop** [comment]
The sensitivity level stuff seems to be a separate concern, as it would affect the ability to view a Veteran's eFolder at all, not document count in the eFolder, right? We should likely investigate that too if we haven't.

**Comment by nicholasholtz** [comment]
I have a call in to the "guru" of user roles - hope to hear back soon, which should be able to get a definitive answer. 

Have reached out to OGC to determine impact of document access on their use of eX for RBA.

The hardest question is figuring out who the authoritative figure on the question is for attorneys here at the Board!

**Comment by nicholasholtz** [comment]
Another document for reference as to how the user roles affect things - and this one seems to be fairly conclusive, with the relevant info in a single place:

[CO_ACR148v16_Maintaining VBMS Role Functions_11232016 Supporting Artifact_HIGHLIGHTED-FIDUCIARY-PMC_nh.xlsx](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/831132/CO_ACR148v16_Maintaining.VBMS.Role.Functions_11232016.Supporting.Artifact_HIGHLIGHTED-FIDUCIARY-PMC_nh.xlsx)

The skinny:
![image](https://cloud.githubusercontent.com/assets/16781398/23754102/d3360956-04a9-11e7-8dc2-217ac9d8eff2.png)

**Comment by shanear** [comment]
closing in favor of #427

Conclusion is that we are filtering all fiduciary docs
