### ISSUE TITLE
Migrate eFolder express to use VBMS eFolder Service Version 1

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#414]
eFolder express should be using VBMS eFolder Service Version 1.0 endpoints from connect_vbms gem

**Comment by aroltsch** [comment]
To turn on the feature in UAT, use FeatureToggle: ```FeatureToggle.enable!(:vbms_efolder_service_v1)```

**Comment by kierachell** [comment]
**PASSED**
Seems to be working as before.
