### ISSUE TITLE
[UI] Download Anyway Modal | Top right button overlaps header text

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#423]
<img width="571" alt="screen shot 2017-03-17 at 9 27 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/24067896/cd1f3f32-0b58-11e7-9675-61451b927601.png">

nuff said.

**Comment by Sjones352** [comment]
@kierachell and @aroltsch I think this ticket should be closed because it has already been fixed.

<img width="565" alt="screen shot 2017-11-12 at 12 37 35 am" src="https://user-images.githubusercontent.com/23080951/32703523-59ce2bfe-c7c5-11e7-84be-97c1bc7baf9c.png">

**Comment by kierachell** [comment]
**PASSED**

dunno what y'all did
