### ISSUE TITLE
Update the caseflow gem for eFolder cf-help-divider

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow-efolder#424]
.cf-help-divider {
  margin: 5px 25px 30px auto;
}

**Comment by mmlumba** [comment]
Fix will be incorporated with issue https://github.com/department-of-veterans-affairs/caseflow/issues/1863

**Comment by mmlumba** [comment]
Closing since the design team is still working on specifications for dividers across all caseflow apps.
