### ISSUE TITLE
If BGS is down, display a more informative message to a user

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#426]
### User Story 
As an eFolder Express user, I want to know when the system is down and how to follow instead of a generic page does not exist message when BGS or a technical error occurs.

### Acceptance Criteria
1. Verify that when BGS is down and/or a related error occurs the message in the mock appears
1. Verify that dimensions of the message follows style guide
1. Verify that the title of the message reads "We are having technical difficulties" 
1. Verify that the line one of the body copy reads "Caseflow is experiencing a technical error." 
1. Verify that the second line of the body copy "If the problem persists, you can Send feedback or contact Caseflow Support at caseflow@va.gov or 1-844-876-5548. 
1. Verify that Send feedback is a link that opens up the feedback form 
1. Verify that caseflow@va.gov is a mail to link that opens up their email 

### Mocks 
<img width="501" alt="screen shot 2017-12-19 at 1 49 37 pm" src="https://user-images.githubusercontent.com/4975959/34173579-ed22a1e4-e4c3-11e7-96f7-92b5031dc28f.png">

### Related Tickets 
#458 BGS Error 

Sentry alerts: 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/574/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/701/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/706/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/697/
 
Tech Notes: 
Follow this example for page not_found: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/downloads_controller.rb#L4

**Comment by Chingujo** [comment]
@aroltsch 

I added user story, AC, and an approved mock. 

The first line of the mock copy should read: 

"We are having technical difficulties"

Will update after a few meetings but added in case people wanted to start working on this today =D.

**Comment by Sjones352** [comment]
@aroltsch and @Chingujo we already have a 503 page that looks like this. 

<img width="1207" alt="screen shot 2017-12-28 at 2 03 58 pm" src="https://user-images.githubusercontent.com/23080951/34420525-10ad887a-ebd8-11e7-8f48-71f6138ebb94.png">

So basically do you want me to update it to this?. @Chingujo I am still working on the style.

<img width="914" alt="screen shot 2017-12-27 at 10 38 08 pm" src="https://user-images.githubusercontent.com/23080951/34420592-7e05c7de-ebd8-11e7-8142-aae2453b8cf7.png">

**Comment by Chingujo** [comment]
@Sjones352 

Yes please!

**Comment by Chingujo** [comment]
Thanks @Sjones352 

If that's the length across all eFolder express messaging, that's fine. We can fix it/file a UI bug for it later. The most important thing is that the spacing between the heading, the first, and second line of copy matches the mock. 

Awesome job getting the links to work =D

**Comment by astewarttistatech** [comment]
@aroltsch do we have anyway to simulate BGS going down in order to validate this?

**Comment by aroltsch** [comment]
@astewarttistatech I don't think we can simulate it. Although you can check the page by going to GET /500 in the browser.

**Comment by astewarttistatech** [comment]
Message is displayed although conditions cannot be reproduced.

**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access /500 from the efolder URL
2. Verify that the Technical Difficulties message matches mocks. 

Screenshots:
