### ISSUE TITLE
Show history with the most recent download at the top

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#434]
Currently eX History shows the files that have been searched for in order from oldest (at top of the list) to newest (at bottom of the list). It should be the opposite.

## Acceptance Criteria
- Verify that the most recently searched eFolder shows at the top of the History and the oldest search shows at the bottom of the list, and that the list is in reverse chronological order.

## Mocks
When this issue is implemented DEMO987 would represent the most recent search and DEMO123 represents the oldest search.
<img width="939" alt="screen shot 2017-03-23 at 12 22 57 pm" src="https://cloud.githubusercontent.com/assets/4975959/24258239/84cb8ba4-0fc3-11e7-80e2-f272bc42137e.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers Validated: FF and Chrome

Steps to Validate: 
1. Go to Efolder on UAT 
2. Retrieve about 4+ eFolders for applicable veterans. 
3. View the History and see that the retrievals are in most recent to oldest order.

Screenshots: 
<img width="1011" alt="screen shot 2017-04-04 at 8 48 27 am" src="https://cloud.githubusercontent.com/assets/23038505/24657407/17ecc552-1914-11e7-95f3-afddff895b77.png">
