### ISSUE TITLE
Log VBMS requests

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#438]
Currently requests to VBMS are not being logged at all; So debugging sucks
**CURRENT:**
<img width="1211" alt="screen shot 2017-03-27 at 2 04 55 pm" src="https://cloud.githubusercontent.com/assets/18075411/24370729/75217962-12f6-11e7-9597-57a1da282f1c.png">
aka _NOTHING_

**EXPECTED:**
- See the following metrics in the logs:
```
FINISHED VBMS::Requests::FetchDocumentById for {1F6F611C-8E3A-41E0-A734-3BED15F7DE1E}:   0.050000   0.010000   0.060000 (  1.642620)
```

## Steps

- Get into eFolder
- Download some files
- Watch the Cloudwatch logs for BGS/VBMS/VVA calls (like `ListDocuments`, etc)
- Validate that they are with the added Metrics as shown in the sample above

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access eFolder
2. Search an appropriate eFolder
3. Download the eFolder. 
4. Check the time you downloaded said eFolder. 
5. Open AWS Cloudwatch
6. Navigate to the corresponding instance of the UAT server for eFolder (worker.out)
7. By time, locate when the download was "FINISHED" 
8. Verify that the metrics shown in the AC are in that log. 

Screenshots: 
<img width="1433" alt="screen shot 2017-08-09 at 12 15 44 pm" src="https://user-images.githubusercontent.com/23038505/29132040-da78ce1c-7cfc-11e7-8f9b-7a666f6f0e7f.png">
