### ISSUE TITLE
Postmortem: Migrations with zero downtime (04/03/2017)

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#443]
Due to a migration taking too long, deployment lasted over 1 hour. It started at 16:10 UTC. 

1. The download that Artem noticed that was hanging with id `15938` started at 16:52 UTC and finished at 17:12 UTC, exactly when Alan cancelled the deployment. The status of the download is success. The download id `15938` is very large and there were only 207 downloads in the past as big as this one. 
2. It seems as `find_each` does not lock the database. 
3. We found downloads that were created and completed successfully within this time range.
4. Add `zero_downtime_migrations` gem to all of our projects https://github.com/LendingHome/zero_downtime_migrations

## Action Items
- for long migrations we should have progress monitors.
- we now have separate jobs for deploy with migration and deploy with no migration. DONE
- every prod issue should cause a page. If not, an issue should be created.
- add https://github.com/LendingHome/zero_downtime_migrations to our CI @aroltsch
5. Avoid long lasting migrations and migrations that lock the table: https://ctoinsights.wordpress.com/2012/07/28/when-not-to-use-rails-dbmigrate/

**Comment by askldjd** [comment]
I would also suggest to print progress so we know how far along we are.

**Comment by shanear** [comment]
Yeah I think you're right Alan, this migration was actually fine.

1) There was a false alarm on eFolder being down. I think we should be better about keeping cool when there are potential prod issues before going crazy that everything is down. Any time we have a hunch that things are not working in prod. We should do 3 things:
a) Verify the business metrics (ie. are there downloads happening right now?)
b) Verify there are no sentry errors
c) Smoke test the application manually in prod
We should be more specific about the nature of the issue after we know information from these actions. If it truly is an outage, and for some reason pager duty didn't go off (which is a problem we would need to address later on in the post-mordem), we should use the `/page-appeals` slack command.

2) There was a large migration happening didn't have great logging, and QA didn't know was coming. We should have let QA (and probably all of engineering) that there was a big migration happening on eFolder. This goes back to being over communicative. Also +1 to Alan's point above about having good logging.

**Comment by kierachell** [comment]
Checklist for "iffy deployments":
- Check with engineering channel for recent functional changes
- Check other monitoring
- Check prod logs/sentry for errors and validate against known bugs
- Smoke test the application in Prod
- Breathe

## Next Actions:

1. Document the above steps in a single document
1. Identify `smoke testable` data for prod
1. Ask engineers to ping QA about migrations
1. Document/acquire DB copies to test large migrations for issues

**Comment by shanear** [comment]
## Action Items
- for long migrations we should have progress monitors.
- we now have separate jobs for deploy with migration and deploy with no migration. DONE
- every prod issue should cause a page. If not, an issue should be created.
- add https://github.com/LendingHome/zero_downtime_migrations to our CI @aroltsch
