### ISSUE TITLE
Handle empty documents in the Veteran's efolder

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#454]
Upon investigation, it was discovered that there are empty documents in VBMS Veteran's eFolder. Determine whether we should add a comment in eFolder Express next to the document when it is empty.

**Comment by lakohl** [comment]
@aroltsch would you be able to include a screenshot of what happens in VBMS when you hit this kind of doc?

**Comment by aroltsch** [comment]
![image](https://cloud.githubusercontent.com/assets/3811786/24814105/626fc994-1b9e-11e7-956e-079d7f57d72a.png)
@lakohl

**Comment by amprokop** [comment]
@aroltsch — how might we tell if a document is empty? by checking the file size?

**Comment by aroltsch** [comment]
We can check the file size. We can also check the size of the content being returned before even generating the file. @amprokop

**Comment by lakohl** [comment]
I'm thinking that it might be helpful to alert the user when the eX file manifest is returned. It could prompt the person processing FOIA/PA requests to delete the empty file from VBMS. But in the event that they don't, could we edit the message displayed to read: 'This document has no content.'?

eX view:


.pdf preview

**Comment by lakohl** [comment]
@aroltsch if the above works for you then go ahead and update the AC and implement it.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
