### ISSUE TITLE
BGS Error | Update style

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#458]
# Description
When BGS goes down we don't display a _descriptive_ or _consistent_ error. It's kinda lame

assigned @lakohl for design ideas (see related stories)

## Reproduction Steps

**Scenario 1 -**

1. Take down BGS

1. Log onto eFolder

1. Attempt a search

1. Get a lame-looking error

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Sentry:

https://10.236.66.247/sentry/efolder-uat-u4/issues/182/

## Screenshots
**_Scenario 1 - [Lame BGS Error Page]_**

<img width="1096" alt="screen shot 2017-04-13 at 6 36 09 pm" src="https://cloud.githubusercontent.com/assets/18075411/25027094/45029e8e-2078-11e7-82b6-cd2c0b9d12b8.png">

**_Engineering_**
#287

**Comment by lakohl** [comment]
@kierachell does the error still look as above? or did this get addressed by another system failure ticket?

**Comment by kierachell** [comment]
Yes, pretty much all error pages in eFolder are lame:
### 404
<img width="887" alt="screen shot 2017-08-02 at 7 11 41 pm" src="https://user-images.githubusercontent.com/18075411/28898945-6eb1af78-77b6-11e7-9075-681a8cbd6e3e.png">


### 500
<img width="886" alt="screen shot 2017-08-02 at 7 11 58 pm" src="https://user-images.githubusercontent.com/18075411/28898952-798065de-77b6-11e7-8a65-091ce6b9eaf0.png">

### Only Unauthorized works:
<img width="1089" alt="screen shot 2017-08-02 at 7 12 49 pm" src="https://user-images.githubusercontent.com/18075411/28898977-9ffbed50-77b6-11e7-9c11-1e77da64fb6e.png">

**Comment by lakohl** [comment]
OK. We should fix this then.

**Comment by lakohl** [comment]
@Chingujo Do you wan to take this on? But prioritize it after Work Queue :)

**Comment by Chingujo** [comment]
Happy to re design the above error page. Will mock some up...mostly taking from the style guide =D

**Comment by lakohl** [comment]
perfect

**Comment by Chingujo** [comment]
Just used the style guide one for general technical difficulties. Noticed that our copy for it is missing any contact information, so added some (unless it was intentional). Ready for your feedback Lara when you get back. 

#### Feedback Link Copy 

![efolder express](https://user-images.githubusercontent.com/23316107/29284126-7782e442-80f7-11e7-9ef1-462a5f9c8403.jpg)


#### Contact Only
![efolder express 2](https://user-images.githubusercontent.com/23316107/29284217-cb72ef48-80f7-11e7-8b48-72272bc65414.jpg)

**Comment by kierachell** [comment]
Make sure the finalized design is in the main issue (you can edit other people's issues/comments/tickets yes...)

**Comment by Chingujo** [comment]
Will do Artem. I will make a comment when I edit the original issue with the finalized mocks =D

**Comment by Chingujo** [comment]
@lakohl 

We are going to implement this messaging for BGS errors. Most likely the one with the feedback link. 

Do you have any feedback or thoughts =D?

**Comment by lakohl** [comment]
@Chingujo I think keeping the message short and sweet is ideal and I wonder if 'please standby' could be misleading. Not wedded to this, but here is a version I started working on a while back: 

<img width="501" alt="screen shot 2017-12-19 at 1 49 37 pm" src="https://user-images.githubusercontent.com/4975959/34173579-ed22a1e4-e4c3-11e7-96f7-92b5031dc28f.png">

**Comment by Chingujo** [comment]
Thanks @lakohl!

Def like the shorter copy and generic messaging around data base. 

Updated the mock above =D

**Comment by Chingujo** [comment]
@lakohl 

Found out this would also display for general code errors. What are your thoughts on changing the first line of code to be more general?

"Caseflow is having trouble connecting to one of it's databases or experiencing another technical error."

"Caseflow is experiencing a technical error"

**Comment by lakohl** [comment]
let's go with the latter.

**Comment by Chingujo** [comment]
Done! Thanks @lakohl

**Comment by aroltsch** [comment]
Can we close it @Chingujo ?

**Comment by lakohl** [comment]
@Chingujo Is this covered by Caseflow Status?

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
