### ISSUE TITLE
Redesign Document List Page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#46]
In our usability session we saw that many users didn't notice the call to action because the file list was so long. Moreover the list would be much longer than we had it. Here are some suggested tweaks for that page for Kavi to explore.

- Find a way to show both instructions and download button 
 - Option 1: Pagination
 - Option 2: Put file list in a scrollable view
 - Option 3: Consider moving call to action to the top of the page (breaks CF Pattern)
 - Option 3: ???
- Change copy to list spell out that these are all the documents in the eFolder
- Add copy that this does not include Virtual VA documents
- Consider changing "Start fetching files" to "Start downloading files" *Kavi waiting for more details from @maryannbrody on this*

**Comment by KHarshawat** [comment]
From @maryannbrody re: changing the wording of "Fetch files from VBMS"

> We talked a bit about how the fetching & downloading connection was not clear. I see your point - what if it's "Prepare files for downloading" or something -- i just think it would be better to show that downloading is the next step. "Scan files for downloading." "Load files from VBMS" ... ??*​

**Comment by shanear** [comment]
Moving into broken apart dev tasks
