### ISSUE TITLE
Record not found for a new download

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#463]
I'm just gonna keep remaking new issues for this stupid *Uh Oh* message.

If you start a new download, for whatever reason we throw a `Record Not Found` exception...

```
Download Load (0.8ms)  SELECT  "downloads".* FROM "downloads" WHERE ("downloads"."created_at" BETWEEN '2017-04-18 18:23:32.945406' AND '2017-04-21 18:23:32.945428') AND "downloads"."user_id" = 2 AND "downloads"."
id" = $1 LIMIT 1  [["id", 59]]
dsva-appeals-efolder-preprod/opt/efolder-express/src/log/efolder-express.out i-04a8dd5e853984b1c-172.30.70.39 [efolder.cf.preprod.ds.va.gov] [b6a95498-bf91-44cc-baee-7efbd2dad547] [172.30.70.39] [CASEFLOW_283   caseflow@va.gov] [2017-0
4-21 14:23:32 -0400] Record not found... Exception ActiveRecord::RecordNotFound: Couldn't find Download with 'id'=59 [WHERE ("downloads"."created_at" BETWEEN '2017-04-18 18:23:32.945406' AND '2017-04-21 18:23:32.945428') AND "downloads
"."user_id" = 2]
dsva-appeals-efolder-preprod/opt/efolder-express/src/log/efolder-express.out i-04a8dd5e853984b1c-172.30.70.39 [efolder.cf.preprod.ds.va.gov] [b6a95498-bf91-44cc-baee-7efbd2dad547] [172.30.70.39] [CASEFLOW_283   caseflow@va.gov] [2017-0
4-21 14:23:32 -0400]   Rendered downloads/not_found.html.erb within layouts/application (0.5ms)
```

## Retry searching and...

<img width="1117" alt="screen shot 2017-04-21 at 2 29 24 pm" src="https://cloud.githubusercontent.com/assets/18075411/25291164/f0483dea-269e-11e7-9807-a8e52497c666.png">

**Comment by amprokop** [comment]
Do you know if there's an issue collecting other folks' experience trying
to track this bug down? I remember a few folks gave it a shot

**Comment by amprokop** [comment]
Perhaps it would be better to just continually add to that issue rather
than making new ones each time?

**Comment by kierachell** [comment]
Sure, and devs keep on closing it "until it shows up again." Then, by the time they decide to look at it, it goes away.

**Comment by kierachell** [comment]
OBSOLETE

cause... meh
