### ISSUE TITLE
Remove VBMS eDocument v4 requests

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#465]
As we move forward with the VBMS eFolder v1, we should remove eDocument v4 requests.

Tech details:

1. Look for FeatureToggle.enabled?(:vbms_efolder_service_v1)
2. Remove the following calls:
* VBMS::Requests::ListDocuments
* VBMS::Requests::FetchDocumentById
* VBMS::Requests::UploadDocumentWithAssociations

**Comment by aroltsch** [comment]
Latest update: VBMS team admitted they have a problem with the eFolder VBMS API. Waiting on the fix.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
