### ISSUE TITLE
Creating a Zip for a veteran with a forward slash in their name causes errors

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#466]
# Description
Weird edge case, but apparently we might be adding a `/` to some `.zip` names, which leads ruby to look for a new folder, instead of the actual file when `package_contents` runs:

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Get a filenumber for a vet with `/` in their name (download id 19985 in `prod`)
1. Attempt to download
1. Fail

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:

PII, can't really log it
```
Errno::ENOENT: No such file or directory @ rb_sysopen
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/160/

**Comment by tejans24** [comment]
This happened 3 times in the past 24 hours.

**Comment by aroltsch** [comment]
This has not happened this April. We can re-open if happens again.
