### ISSUE TITLE
Add ability to select/deselect files

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#47]
Many users told us that they wanted the ability to select or deselect files from the file list. We should also add a select all/deselect all for good measure. This should work with pagination if we add it. 

Kavi to mock up.

**Comment by KHarshawat** [comment]
There was additional feedback that this was dependent on date ranges for example all the files after a Board Decision was issues..

**Comment by KHarshawat** [comment]
This isn't super urgent and we may not even want to add this feature unless we hear it for more feedback.

**Comment by lakohl** [comment]
@KHarshawat @orischwartz Is this doable? It was my understanding that users could only download the entire eFolder. Does not seem like a feature needed by OGC - so not urgent, but other user groups may want it if it is not a big lift.

**Comment by KHarshawat** [comment]
@lakohl Agree not super urgent, probably more of a future feature enhancement if we hear the feedback from other users. Perhaps we should have an icebox label for issues like these that are explicitly de-prioritized?

**Comment by lakohl** [comment]
@Chingujo this is something we should try to mock out. I can provide context

**Comment by lakohl** [comment]
@Chingujo can you update this issue?

**Comment by Chingujo** [comment]
@lakohl 

Thanks for the reminder =D. Here is the link to the current working mocks for selection features: 
https://marvelapp.com/project/1074900/

**Comment by Chingujo** [comment]
@lakohl 

Updated with feedback.

**Comment by lakohl** [comment]
closing for now
