### ISSUE TITLE
[1] Restrict certain document types.

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#474]
Filter out the following doc types:
444 Misuse - Referral to Office of Inspector General
548 Change of Address Fiduciary
549 Change of Address Beneficiary

For more information check out:
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/450#issuecomment-297449722

**Comment by kierachell** [comment]
**PASSED**

Works for all 3 types: 444 shown below
```
#<OpenStruct upload_document_response={:veteran_reference=>{:id=>{:@file_number=>"453454305"}, :@xmlns=>""}, :type_category=>{:@xmlns=>"", :@category_id=>"18", :@category_description_text=>"Fiduciary", :@type_id=>"444", :@type_descr
iption_text=>"Misuse - Referral to Office of Inspector General", :@type_label_text=>"L444"}, :va_receive_date=>Sun, 14 May 2017, :vbms_upload_date=>Tue, 16 May 2017, :@xmlns=>"http://service.efolder.vbms.vba.va.gov/eFolderUploadService
", :"@xmlns:com"=>"http://vbms.vba.va.gov/cdm/common/v4", :"@xmlns:efc"=>"http://service.efolder.vbms.vba.va.gov/common", :"@xmlns:efu"=>"http://service.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:part"=>"http://vbms.vba.va
.gov/cdm/participant/v4", :"@xmlns:doc"=>"http://vbms.vba.va.gov/cdm/document/v5", :@new_document_version_ref_id=>"{1859E7A4-54F1-4A4C-8683-0A35D8DE64E5}", :@document_series_ref_id=>"{F69C7EAE-D99E-4258-89AC-8CB6CA93FE62}", :@mime_type
=>"application/pdf"}>
```
<img width="936" alt="screen shot 2017-05-16 at 4 30 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/26126800/fb0d9972-3a54-11e7-812e-8f51b2b93fe2.png">
<img width="798" alt="screen shot 2017-05-16 at 4 31 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/26126843/1f119a94-3a55-11e7-94a1-a6c2de267852.png">
