### ISSUE TITLE
Fetching large files from S3 may lead to download timeout

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#475]
Efolder operates in the following matter when you press the **Download File** button

1. Checks if the bundled zip file is on disk. If so, go to step 3. If not, proceed to step 2.
2. Download the zip file from S3.
3. Call `send_file` with the file file path.

If the file is really large, step 2 may take considerable amount of time, and may exceed the HTTP timeout. So in user's perspective, they will see a 504 error.

Based on quick benchmark, EC2 can fetch from S3 at ~23MB/s. So in the case of https://github.com/department-of-veterans-affairs/appeals-support/issues/133, it will take 104s to fetch the 2.4GB file from S3. This easily exceed the HTTP timeout of 60s.

Possible Solutions:
1. ~~Modify Nginx to allow for larger timeout and hide the problem.~~
1. Allow Rails to stream the file from S3 (not sure how to stream data in Rails)
1. Nginx proxying S3 (how do we authenticate?)
1. AWS Presign URL (might have ATO issue)
1. Use a small Node.js streaming server with Rails

**Comment by askldjd** [comment]
Attempted to resolve this bug by changing Nginx, and this path led to a lot of issues.
 - By increasing nginx timeout, we moved the timeout to ELB.
 - By increasing ELB idle timeout, we moved to the timeout to browser.

In the end, the timeout happened on the browser side. Therefore, solution #1 is a no-go.

**Comment by askldjd** [comment]
After fiddling with https://github.com/vala/s3streamer, I was unable to find a working solution in Rails 4.

However, I have another solution working:

A much simpler approach is to have Rails generate a presigned S3 URL that expires in a short period of time (say 60s). After a quick prototype, I was able to get this to work with the following changes.

```ruby
# in caseflow-commons s3_service.rb
def self.get_presigned_url(filename)
  Aws::S3::Presigner.new.presigned_url(
    :get_object,
    bucket: bucket_name,
    key: filename,
    expires_in: 60
  )
end
```

```ruby
# efolder / download_documents.rb
def fetch_presigned_url_from_s3
  @s3.get_presigned_url(@download.s3_filename)
end

# efolder / downloads_controller.rb
def download
...
  redirect_to @download_documents.fetch_presigned_url_from_s3
end
```

I have discussed this with @shanear before and the ATO issue has come up. However, after giving it a good thought, I am not sure how this is any less secure than our current approach.

**Comment by askldjd** [comment]
If downloading straight from S3 is a no-go, another way of doing this is to use a node.js streaming server.

1. User clicks "Download File"
1. Rails handles the request, generate a token, and store the S3 bucket/key in Redis. Rails then redirect the user to another URL `/stream-download/#{token}`
1. Browser follows the redirect and make another HTTP request to the new URL
1. Nginx intercepts `/stream-download` prefix and redirects it to Node.js streaming server at port 3002
1. Node.js handles the request, gets the token param and lookup the bucket/key info. 
1. Node.js stream the S3 object to the user.

This sounds complicated, but the Node.js server is around ~30 lines of code

```
var express = require('express')
var app = express()
var AWS = require('aws-sdk');

var s3 = new AWS.S3();
app.get('/download/:tokenId', function (req, res) {
  var key, bucket;
  // Get key/bucket from Redis using tokenId
  // ...
  s3.getObject({Bucket: bucket, Key: key })
    .on('httpHeaders', function (statusCode, headers) {
      res.set('Content-Length', headers['content-length']);
      res.set('Content-Type', headers['content-type']);
      this.response.httpResponse.createUnbufferedStream()
        .pipe(res);
    })
    .send();
})
app.listen(3002, function () {
  console.log('listening on 3002')
})
```

**Comment by ToddStumpf** [comment]
If you wanted to build this with entirely off-the-shelf parts, you could do:
* amend step 0 to stuff a preshared secret in an secure s3 bucket
* amend step 2 to return a JWT against the preshared secret
* amend step 4 to route to Varnish cache with the JWT module enabled against the preshared
* amend step 7 to rotate the secret periodically
I think that'd be the fastest secure way to go from A to B.  Saves writing any custom code for pumping data ... I think.  Bandwidth still passes thru our AWS account, but at least it's not the rails server.

All that said, there's a lot of value from fighting the good fight for signed S3 urls, though -- once that's blessed, there's a lot of re-use for that solution to other problems.  I think pursuing S3 signed urls is worth pursuing first.  Then off the shelf.  Then custom.

**Comment by aroltsch** [comment]
We are going forward with this solution: 
http://smsohan.com/blog/2013/05/09/genereating-and-streaming-potentially-large-csv-files-using-ruby-on-rails/

**Comment by aroltsch** [comment]
We will be using UAT efolder with 561349918 and 561349919 to test the code. Branch: anya/stream_large_downloads

**Comment by kierachell** [comment]
**PASSED**
Well, _downloading_ works... if we even manage get that big a list of documents.
