### ISSUE TITLE
Search | Missing or Extra leading 0s cause a fetch_documents_for hang

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#477]
# Description
When searching for a file number with 0s; Adding or removing them will cause a weird fetch_documents_for behavior.

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Search for 008605113 in UAT
1. Try adding or removing 0s
1. See the search hang

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [Hanging with missing 0]_**
<img width="1093" alt="screen shot 2017-05-03 at 10 48 35 am" src="https://cloud.githubusercontent.com/assets/18075411/25666409/7bf9583a-2fee-11e7-88b5-d2f978915dae.png">

**_Scenario 1 - [Found with normal #]_**
<img width="1101" alt="screen shot 2017-05-03 at 10 51 47 am" src="https://cloud.githubusercontent.com/assets/18075411/25666442/91718a98-2fee-11e7-9624-8a18c4f380d9.png">

# Related Issues
**_Support_**
https://github.com/department-of-veterans-affairs/appeals-support/issues/142

**Comment by amprokop** [comment]
If we're having trouble reproducing this, let's try to timebox this to an hour or two, and put it back in the backlog if there isn't a readily apparent solution.

**Comment by kierachell** [comment]
**PASSED**

Fixed a while ago
