### ISSUE TITLE
eFolder Express missing or not sending :region parameter

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow-efolder#479]
Sentry [details](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/178/)

<img width="639" alt="screen shot 2017-05-03 at 4 23 51 pm" src="https://cloud.githubusercontent.com/assets/1053255/25679881/ecbbf11c-301c-11e7-8235-1841d18b1abc.png">

**Comment by aroltsch** [comment]
This has been fixed.
