### ISSUE TITLE
NameError: download_documents not defined

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow-efolder#480]
Sentry [details](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/179/)

<img width="628" alt="screen shot 2017-05-03 at 4 47 35 pm" src="https://cloud.githubusercontent.com/assets/1053255/25680859/434a0cfa-3020-11e7-8d2b-949816fee0d9.png">

**Comment by aroltsch** [comment]
This has been fixed.
