### ISSUE TITLE
Consider not sending SAML error to Sentry when the user enters the wrong credentials

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#491]
Sentry APP [Today at 11:10 AM] 
in #appeals-devops-alerts
OmniAuth::Strategies::SAML::ValidationError: SAML response missing
Culprit
----------------
app/middleware/metrics_auth.rb in call at line 10

Project
----------------
Appeals eFolder Express

2 replies
Alan Ning 
[1 hour ago] 
We should consider silencing this error.

Alan Ning 
[1 hour ago] 
I think this happens when user enters the wrong credential

**Comment by aroltsch** [comment]
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/382#issuecomment-342843840

**Comment by aroltsch** [comment]
@kierachell is this still an issue?
