### ISSUE TITLE
List Documents | File number is not validated with non alphanumeric characters

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#496]
# Description
When I go search for a filenumber, the `C` at the end is not removed,
so the List Documents just hangs...

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Search for `879325490C`
1. Watch spinner
1. Question life

**Scenario 1 -**

1. Go to eFolder
1. Search for `0909+1293`
1. Cause Sentry error
1. Question life

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [You spin me right round]_**
<img width="1048" alt="screen shot 2017-06-14 at 2 44 37 pm" src="https://user-images.githubusercontent.com/18075411/27148933-0329f9e4-5110-11e7-8016-c4d7a3f30faa.png">

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/250/

Acceptance Criteria:
1. Display error if when file number is less than 8 characters long
2. Display error if when file number contains letters
3. Works correctly when file_number is at least 8 characters long and all digits

Header text in the error should say: "The veteran ID you entered was not valid."
Body text in the header should say: "Check to make sure you entered the ID correctly and try again."

**Comment by amprokop** [comment]
@kierachell — is this new?

**Comment by amprokop** [comment]
the S and C are only in VACOLS, i'm not sure eFolder Express should accept them.

**Comment by kierachell** [comment]
It should not, but it also should not hang when there's something other than `S` at the end. It should either error out or suggest removing all non-numerics.

**Comment by kierachell** [comment]
So yeah, there's a fix, but what is it?
@shellicious or @amprokop  - can you provide "expected behavior" and/or error message mocks to the original issue so that I know what to expect?

**Comment by shellicious** [comment]
@kierachell I don't have much context about this, but I did add copy to the description of this issue: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/516, which I believe was resolved by this PR: https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/506

**Comment by kierachell** [comment]
**PASSED**
![faceroll](https://user-images.githubusercontent.com/18075411/27806998-fc3d77c2-600b-11e7-86e0-b84df580c7bb.gif)
