### ISSUE TITLE
Investigate bug where 32 of 38 files are downloaded

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#497]
See https://github.com/department-of-veterans-affairs/appeals-support/issues/181

First try to repro and post results here.

**Comment by amprokop** [comment]
First obtain the case number from @RTOLSON .

**Comment by RTOLSON** [comment]
@alex I have the claim number.

**Comment by nemodjuric** [comment]
@RTOLSON is waiting on information from the user.

**Comment by nemodjuric** [comment]
I was able to download all 39 documents successfully logged in as CSDNNEUG. Waiting on CSDNNEUG to try it again.

**Comment by amprokop** [comment]
Closing this.
