### ISSUE TITLE
SPIKE | Investigate coach mark implementation 

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#499]
We would like to implement Coach Marks within the Caseflow application.  We would like to start by doing a simple implementation within eFolder Express.

There are different options for implementing coach marks.  However, we need to determine which one will fit well technically in our environment (Ruby).  We need to identify the pros and cons of the different options.  Each one of the following options have a demo of how they are displayed on the UI and provide code instructions.

**_Options (Visual Preference Order)_**
1. [Crumble](https://github.com/tommoor/crumble)
1. [Hopscotch](http://linkedin.github.io/hopscotch/#general-usage)
1. [Shephard](https://github.com/HubSpot/shepherd)
1. [Intro.js](https://github.com/usablica/intro.js)

# Related Stories
n/a

**Comment by mmlumba** [comment]
Hopscotch:
![hopscotch-demo](https://user-images.githubusercontent.com/4773320/27302667-f861937e-5505-11e7-9a16-eecfc7f008c4.gif)

**Comment by mmlumba** [comment]
IntroJS:
(in motion)
![introjs-demo](https://user-images.githubusercontent.com/4773320/27304746-10c234f8-550d-11e7-8cd4-eb6067c41688.gif)

(in still)
<img width="1280" alt="screen shot 2017-06-19 at 4 31 15 pm" src="https://user-images.githubusercontent.com/4773320/27304784-31578d12-550d-11e7-9b4b-ef795554b746.png">

**Comment by mmlumba** [comment]
**Unfeasible options**
- Crumble: This project has not been maintained since 2012. The library that this package is dependent on, Grumble, has not been maintained since 2013.
- Shepherd: The main dependency of this project, Tether, will no longer be maintained as of May 2017. No code (besides documentation) has been pushed to the dependency since Dec 2016.

**Comment by mmlumba** [comment]
Closing this ticket as it seems that Hopscotch is a clear winner according to the feedback in the appeals-design channel.
