### ISSUE TITLE
Update eX Copy referencing VVA

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#500]
As a Case Supporter, I would like the copy on the Manifest page ....

# Acceptance Criteria with Mocks
1. Copy Updates:
- Remove '!' after Welcome to eFolder Express
- Update note copy to the following:
> Note: eFolder Express now includes Virtual VA documents from the Legacy Content Manager Documents tab in VBMS.

_Current:_
<img width="1077" alt="screen shot 2017-06-30 at 4 34 40 pm" src="https://user-images.githubusercontent.com/4975959/27753093-3ea1384e-5db2-11e7-8ee7-3e8a963f4033.png">

_New_
**_View - Manifest page_**
<img width="614" alt="screen shot 2017-06-30 at 4 22 22 pm" src="https://user-images.githubusercontent.com/4975959/27752691-585378c6-5db0-11e7-973f-1925d3c355e5.png">

2. Copy Update:
- Change Database name to VVA/LMC on this page and on the following pages.
- Update note copy to the following:
> eFolder Express found a total of 123 documents (109 from VBMS and 14 from VVA/LCM ) for Joe Snuffy #222222222. Verify the Veteran ID and click the Start retrieving eFolder button below to start retrieving the eFolder.

_Current:_
<img width="1049" alt="screen shot 2017-06-30 at 4 35 03 pm" src="https://user-images.githubusercontent.com/4975959/27753098-442ef576-5db2-11e7-83fb-fe5263abb6d9.png">

_New_
<img width="677" alt="screen shot 2017-07-03 at 11 32 10 am" src="https://user-images.githubusercontent.com/4975959/27799496-64d84056-5fe3-11e7-8a38-011312301001.png">

3. Copy Update: 
- Update last line of note copy to display the following:
> This efolder contains 133 documents: 100 from VBMS and 33 from VVA/LCM.

_Current:_
<img width="981" alt="screen shot 2017-06-30 at 4 35 22 pm" src="https://user-images.githubusercontent.com/4975959/27753100-4841dc6e-5db2-11e7-9817-359541f9a7a0.png">

_New_
<img width="502" alt="screen shot 2017-06-30 at 4 30 55 pm" src="https://user-images.githubusercontent.com/4975959/27752972-9c5464d0-5db1-11e7-85dd-f212e2356cf3.png">

# Related Stories
n/a

**Comment by lakohl** [comment]
Working on developing this issue in: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/195

**Comment by lakohl** [comment]
@abbyraskin can you take a look at the copy in the AC?Could use a second pair of eyes

**Comment by kierachell** [comment]
**PASSED**

<img width="824" alt="screen shot 2017-07-05 at 9 19 44 am" src="https://user-images.githubusercontent.com/18075411/27866882-074e9122-6166-11e7-9b78-297e67c5a6da.png">
<img width="928" alt="screen shot 2017-07-05 at 9 20 39 am" src="https://user-images.githubusercontent.com/18075411/27866883-07510bb4-6166-11e7-96c7-9ad483725bcf.png">
<img width="135" alt="screen shot 2017-07-05 at 9 20 43 am" src="https://user-images.githubusercontent.com/18075411/27866884-0754bf3e-6166-11e7-816f-ed75cd27c9e6.png">
<img width="931" alt="screen shot 2017-07-05 at 9 40 19 am" src="https://user-images.githubusercontent.com/18075411/27866885-0754e720-6166-11e7-937c-7dce228b15dd.png">
