### ISSUE TITLE
eFolder Express Integration | Adding /api/v1/documents/:document_id endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#504]
Read the full eFolder Express integration tech spec [here](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md).

/api/v1/documents/:document_id - will stream the document with document_id from S3

# AC
1. Verify that if the file has been uploaded to S3, then stream the file directly to the user.
1. Verify that if the file has not been uploaded to S3, download the file from VBMS, put it in S3, then serve it.

Steps to validate:

Test eFolder Express that it functions as normal
Test API call /api/v1/documents/document_id:
a) enable the feature reader_api
b) document_id is the DB ID of the document that should already exist in the EX DB
c) example using CURL: curl -i -X GET http://localhost:3000/api/v1/documents/23548
d) disable the feature flag as it is the only thing that protects the API (no authentication in place)

**Comment by kierachell** [comment]
### What if the Document is in the DB but not on S3?
```
Document Load (1.3ms)  SELECT  "documents".* FROM "documents" WHERE "documents"."id" = $1 LIMIT 1  [["id", 200]]
2017-06-29 11:12:26 -0400: Read error: #<Aws::S3::Errors::NoSuchKey: The specified key does not exist.>
```

**Comment by aroltsch** [comment]
@kierachell can you please add steps to reproduce? It should have fetched the document from VBMS if the file is not in s3.

**Comment by kierachell** [comment]
Another pass:

1. Find a completed download:
```
#<Download id: 434, request_id: nil, file_number: "879325490", status: 5, created_at: "2017-06-22 14:56:19", updated_at: "2017-06-22 14:57:51", lock_version: 16, manifest_fetched_at: "2017-06-22 14:56:27", started_at: "2017-06-22 14
:57:35", completed_at: "2017-06-22 14:57:51", veteran_last_name: "JONES", veteran_first_name: "RICHARD", veteran_last_four_ssn: "5490", user_id: 9, zipfile_size: 2160975>
```
1. Get a document from that download.
```
#<Document id: 275927, download_id: 434, download_status: 1, document_id: "{BD57C2CF-F8A7-4143-8579-12DCE24673A4}", vbms_filename: "", filepath: "/opt/efolder-express/src/tmp/files/434/00010-BVA D...", source: "VACOLS", mime_type: "
application/pdf", received_at: "2017-06-08 00:00:00", created_at: "2017-06-22 14:56:27", updated_at: "2017-06-22 14:57:36", started_at: "2017-06-22 14:57:35", completed_at: "2017-06-22 14:57:36", lock_version: 2, type_description: "BVA
 Decision", type_id: "27", error_message: nil, downloaded_from: "VBMS", jro: nil, ssn: nil>
```
1. Not have a filename? Weird...
1. Error
```
Document Load (3.7ms)  SELECT  "documents".* FROM "documents" WHERE "documents"."id" = $1 LIMIT 1  [["id", 275927]]
dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-0af8bee8cfdc3d8b6-172.30.71.235 [efolder.cf.uat.ds.va.gov] [c56370f5-7831-4f3f-9e49-a323fa5e9373] [172.30.71.235] [2017-06-29 11:45:39 -0400] Completed 200 OK in 7ms (ActiveRecord: 3.7ms)
dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-0af8bee8cfdc3d8b6-172.30.71.235 2017-06-29 11:45:39 -0400: Read error: #<Aws::S3::Errors::NoSuchKey: The specified key does not exist.>
``

**Comment by mdbenjam** [comment]
For error handling, it seems we should receive one of three things. 200, if successful, 404 if the record is not found in VBMS, and 500 if anything else goes wrong.

**Comment by kierachell** [comment]
**PASSED**
At least as far as AC goes
