### ISSUE TITLE
Make Document Fetching Errors clearer

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#51]
We observed users were slightly confused when they encountered errors fetching documents. 

If there are errors while fetching documents:
- Place a `Download Anyway` link in the error message
- Change the `Download now` button to a `Download Anyway`
- Consider changing the `Download Anyway` button to a different color (yellow?)
- Consider showing a popup if the user clicks the `Download Anyway` button indicating that some files will not be downloaded.

**Comment by shanear** [comment]
https://marvelapp.com/h141bc#13388416
