### ISSUE TITLE
Search | Add coach marks announcing VVA changes

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#510]
As a Case Supporter, I would like to have a brief announcement of the VVA changes so that I am aware of what the function now does.

# Acceptance Criteria
1. Verify that upon rendering of the Search page for the 1st time, the following initial coach mark is displayed.

# Mockup

# Related Stories
Manifest | Add coach marks announcing VVA changes #511

**Comment by lakohl** [comment]
closing in favor of 511
