### ISSUE TITLE
Add coach marks announcing VVA changes

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#511]
As a Case Supporter, I would like to have a brief announcement of the VVA changes so that I am aware of what the function now does.

# Acceptance Criteria

Add coach marks on the following pages:

1. Search
1. Start Retrieving efolder
1. Success

When you click on the "hide tutorial" button, the coachmarks should disappear.
When you dismiss all coachmarks, the "hide tutorial" button should change to say "show tutorial".
When you click on the "show tutorial" button, the coachmarks should appear.
The "hide tutorial" button should only be present on a page with coachmarks.

Copy for the coach marks should display as follows:

**Search page:**
> Downloads from eFolder Express now include Virtual VA documents.

**Start Retrieving efolder page:**
1. > The total number of documents that will be retrieved from each database is listed here. 
2. > The Source column shows the name of the database from which the file will be retrieved.

**Success page:**
> The total number of documents that will be downloaded from each database is listed here. 

**Styling:**
Coach mark copy: 19px
Copy color: 323A44
Background color: DCE4EF

Verify that the coachmarks are hidden under VVA feature flag

# Mockups

<img width="514" alt="screen shot 2017-07-03 at 1 01 51 pm" src="https://user-images.githubusercontent.com/4975959/27803765-33e04b72-5ff9-11e7-8a24-789588a343f3.png">
<img width="619" alt="screen shot 2017-07-03 at 12 37 31 pm" src="https://user-images.githubusercontent.com/4975959/27803773-40d3ed7a-5ff9-11e7-978a-bc991407a445.png">
<img width="618" alt="screen shot 2017-07-03 at 12 38 17 pm" src="https://user-images.githubusercontent.com/4975959/27803780-4b086e42-5ff9-11e7-987c-08e0e2a33a56.png">

**Comment by mmlumba** [comment]
@lakohl Is the styling for the bubbles in the mock the exact styling you'd want for the coachmarks?

**Comment by lakohl** [comment]
@mmlumba I wasn't exactly sure of your styling options - something close to this would be ideal.

**Comment by mmlumba** [comment]
Notes:
5px shadow
Use purple from USWDS
Don't cover button from the pages
All bubbles appear on the page at once
Not a "tour"; feature pointers

**Comment by astewarttistatech** [comment]
@NickHeiner 

**FAILED**

Env: UAT/Preprod

Steps to Recreate: 
1. Access Efolder
2. Verify that these pages have coachmarks in the Efolder Express flow
      - Search
      - Start Retrieving efolder
      - Success

Current View: 
![coachmark](https://user-images.githubusercontent.com/23038505/28538267-a9e684b6-707b-11e7-999d-99ff0c203113.gif)

**Comment by NickHeiner** [comment]
@astewarttistatech do you have the `:vva_service` feature flag enabled? It looks like you don't, because the page copy says things like "Remember that Virtual VA documents are not included in this download". That text goes away when the feature flag is enabled.

**Comment by astewarttistatech** [comment]
Sorry about that @NickHeiner, it wasn't but unfortunately this ticket is missing the coachmark for source column

Current View: 
![coachmark](https://user-images.githubusercontent.com/23038505/28539312-3b0fd44e-707f-11e7-8594-8ea1e79efa7e.gif)

**Comment by NickHeiner** [comment]
I see that the coachmark appears for the source column:

![image](https://user-images.githubusercontent.com/829827/28539535-ff6223d8-707f-11e7-8545-796f370742c0.png)

The source column coachmark appears on the "Start Retrieving EFolder" page. From the gif you posted, it looks like you were looking for it on the "Success" page.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod/UAT
Browsers: FF, Chrome, IE

Steps to Validate: 
1. Access efolder with vva_service (feature flag) enable 
2. Go through the flow of searching a new efolder by file number/ssn
3. Validate the coach marks that show on the Search and Start Retrieving Efolder page

Screenshots:
![coachmark](https://user-images.githubusercontent.com/23038505/28541027-76e26bfc-7085-11e7-97f2-1c49d31582e6.gif)
