### ISSUE TITLE
What's New | Update content to include new features of VVA changes

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#512]
As a Product Owner, I would like to have the `What's New `page updated to contain the new VVA changes.

#  Acceptance Criteria
1. Verify that ...

# Mockup

# Related Stories
n/a

**Comment by lakohl** [comment]
@Chingujo can you work with Will on this? see https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/518

**Comment by Chingujo** [comment]
Yes! Will connect with Will on wenesday on copy and mocks (if necessary) :)

**Comment by Chingujo** [comment]
Invision link: https://va-gov.invisionapp.com/d/main/#/projects/prototypes/11589444

Mock below =D

![efolder express](https://user-images.githubusercontent.com/23316107/28423453-1d2c34ac-6d39-11e7-9fee-0fa684fae502.jpg)

**Comment by lakohl** [comment]
Looking good! @Chingujo I still think we should try to make the copy narrower (12-15 words wide) on the page.

**Comment by Chingujo** [comment]
@lakohl 

- Kept original app canvas side
- Reduced copy content width and left aligned to 60 px keeping the other margins the same.  
- Removed italics on the links as it was not consistent with the style guide 

![efolder express](https://user-images.githubusercontent.com/23316107/28469866-b8f23de2-6e05-11e7-85cf-4ba682abf8ae.jpg)

**Comment by aroltsch** [comment]
We can close it because VVA coach marks is not a new feature anymore.
