### ISSUE TITLE
Manifest | Update eX Copy referencing VVA 

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#513]
As a Case Supporter, I would like the copy on the Manifest page ....

# Acceptance Criteria
1. Verify

# Mockup
**_View - Manifest page_**

# Related Stories
n/a

**Comment by nikitarockz** [comment]
Working on developing this issue in: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/195

**Comment by lakohl** [comment]
closing - changes captured in #500
