### ISSUE TITLE
Coach mark behavior

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#517]
As a caseworker, I would like to be able to see the coach marks once, and then have the ability to never see them again.

## AC
Rules: 

### First and second pass
1. Display the coach marks when the user lands on the Search page.
1. Allow the user to proceed/perform their work while the coach marks are displayed.
1. Allow the user to close the coach marks by clicking on the X.
1. Display 'Hide tutorial' link at the very top of the page (17px, color: 0071bc, underlined)
1. On click, 'Hide tutorial' eliminates the coach marks on all pages, and changes the 'Hide tutorial' link copy at the top of the page to read 'See what's new!'.
1. On click, the 'See what's new!' link switches to 'Hide Tutorial' and coach marks are displayed throughout the application until the user 'Hides', 'Skips', or clicks 'x' to stop them from displaying.

### Third Pass
1. Coach marks do not display.
1. Display 'See what's new!' link (underlined) at the top of the page.
1. On click, the 'See what's new!' link switches to 'Hide Tutorial' and coach marks are displayed throughout the application until the user 'Hides', 'Skips', or clicks 'x' to stop them from displaying.

## Mocks

First and Second pass: 
<img width="514" alt="screen shot 2017-07-03 at 1 01 51 pm" src="https://user-images.githubusercontent.com/4975959/27802121-d52e3ca0-5fef-11e7-950a-c1414b179019.png">

Third pass:
<img width="512" alt="screen shot 2017-07-03 at 1 01 31 pm" src="https://user-images.githubusercontent.com/4975959/27802133-e4124860-5fef-11e7-89ca-bc7b5dcbab44.png">

**Comment by mmlumba** [comment]
"got it? skip tutorial" is 17px

**Comment by lakohl** [comment]
See what's new! / Hide tutorial link is 17px

**Comment by lakohl** [comment]
My presumption is that one pass = 1 Vet ID successfully retrieved

**Comment by NickHeiner** [comment]
And clicking "hide tutorial" does not advance you to the next pass, right?

**Comment by lakohl** [comment]
No, 'Hide Tutorial' gets rid of the coach mark(s) on that page and on subsequent pages. It's the equivalent of clicking the 'X' on that and all subsequent coach marks. It does not advance the user, they stay on that page.

**Comment by NickHeiner** [comment]
@lakohl let's chat in person about the "second pass" option on Monday. I have some questions that I think are best answered synchronously.

**Comment by lakohl** [comment]
No problem @NickHeiner

**Comment by astewarttistatech** [comment]
AC needs to include the fact that the coach marks are only visible via feature toggle. It's a more complete end-to-end experience. @lakohl 

Otherwise: 

**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Enable vva_service feature toggle
2. Visit eFolder Express
3. Validate the coach marks against the mocks and AC
4. Disable vva_service feature toggle 
5. Visit eFolder Express
6. Validate the UI against mocks and AC

Screenshots: 
<img width="1231" alt="screen shot 2017-07-26 at 11 16 52 am" src="https://user-images.githubusercontent.com/23038505/28629942-e76acee2-71f6-11e7-8d72-c874774a5d59.png">
