### ISSUE TITLE
Help | FAQs | Update question/answer with VVA docs available in download

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#518]
As a Product Owner, I would like the FAQs to reflect the new change of having VVA docs included in the download of the veteran's efolder so that the user knows about this new feature.

## Acceptance Criteria
1. Verify in the "Frequently Asked Questions" section, it contains the newly updated listing of all questions. (Refer to [eFolder Express FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/In-App-Help/eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf)) **_Note:  Several questions have changed as well as order._**
1. Verify that in the "FAQ Answers" section, it contains all newly updated questions and their answer.  (Refer to [eFolder Express  FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/In-App-Help/eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf))  **_Note:  Several questions have changed as well as order._**
1. Verify that each question in the FAQ section is a hyperlink to its answer. 

## Mocks
**_Current Help Page - update FAQs section_**
![faq_mock](https://user-images.githubusercontent.com/23361723/28533789-6b6f7f44-706c-11e7-9223-330a82f09d96.png)

# Related Story
eFolder Express - VVA | FAQs | Update/Develop questions [#20](https://github.com/department-of-veterans-affairs/appeals-training/issues/20)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: Demo,UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the /help page for eFolder Express
2. Validate that the FAQ was added under the training videos.

Screenshots: 
![efolder expresshelp](https://user-images.githubusercontent.com/23038505/28777580-c235c812-75c9-11e7-847a-1d27e59d5ea1.png)

**Comment by wturne** [comment]
Updated link above with most recent version of eX FAQs.  

[eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1289967/eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf)

**Comment by wturne** [comment]
Issue reopened by mistake.  Closing issue.
