### ISSUE TITLE
Help | Add link to display Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#519]
As a Product Owner, I would like to have links to the Training Guide and Quick Reference Guides so that the users can obtain additional detailed information on how to use eFolder Express.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the "Welcome to the eFolder Express Help Page!" section, the copy has been updated to the following:
     >  Here you will find [Training Videos]() and answers to the [Frequently Asked Questions (FAQs)]() for eFolder Express, as well as links to the [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/TMS-Training-Guide/eFolder%20Express%20Training%20Guide_Sep2017_2.pdf) and the [Quick Reference Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/In-App-Help/eX_Quick_Reference_Guide_Sep2017.pdf). These items are provided to assist you as you access and use eFolder Express. If you require further assistance after reviewing these items, please contact the Caseflow Product Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look forward to assisting you. 

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab.  [eFolder Express Training Guide_Sep2017_2.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/TMS-Training-Guide/eFolder%20Express%20Training%20Guide_Sep2017_2.pdf)
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab.  [eX_Quick_Reference_Guide_Sep2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/In-App-Help/eX_Quick_Reference_Guide_Sep2017.pdf)

**_FAQ Answer Section_** 
1. Verify that FAQ text matches the text in this PDF:
[eFolder.Express_Frequently.Asked.Questions_Sep2017(1).pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1309321/eFolder.Express_Frequently.Asked.Questions_Sep2017.1.pdf)

1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [eFolder Express Training Guide_Sep2017_2.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/TMS-Training-Guide/eFolder%20Express%20Training%20Guide_Sep2017_2.pdf)
1. Verify that the text "FAQs" is a hyperlink to the "Frequently Asked Questions" section. 
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. [eX_Quick_Reference_Guide_Sep2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/eFolder-Express/Rollout-Package/In-App-Help/eX_Quick_Reference_Guide_Sep2017.pdf)

## Mocks
**_eFolder Express Help Page - Introduction section requiring change_**
![image](https://user-images.githubusercontent.com/23063044/29882785-267633ec-8d7c-11e7-9402-847f1c089d08.png)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![image](https://user-images.githubusercontent.com/23063044/29882966-adb40e10-8d7c-11e7-9b8d-eae122fa4cd6.png)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
![image](https://user-images.githubusercontent.com/23063044/29883175-67238aec-8d7d-11e7-9222-8ea3dd539fdc.png)

# Related Stories
eFolder Express - VVA | Training Guide | Update/Develop questions [#25](https://github.com/department-of-veterans-affairs/appeals-training/issues/25)
eFolder Express - VVA | QRG | Update/Develop questions [#26](https://github.com/department-of-veterans-affairs/appeals-training/issues/26)

**Comment by wturne** [comment]
@nikitarockz - Updated the copy for the Help and FAQ page.  Please let me know if you have any questions.

**Comment by wturne** [comment]
Updated story with links for eX Training Guide and Quick Reference Guide. 

[eX_Quick_Reference_Guide_Sep2017.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1289961/eX_Quick_Reference_Guide_Sep2017.pdf) 

[eFolder Express Training Guide_Sep2017_2.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1289962/eFolder.Express.Training.Guide_Sep2017_2.pdf)

**Comment by kierachell** [comment]
### Do not see section 1 or 18 updated?

@lakohl
- are we referring to eFolder as `Caseflow eFolder Express` everywhere now?
- Does this mean the main header should be `Welcome to Caseflow eFolder Express`?

<img width="850" alt="screen shot 2017-09-16 at 5 10 50 pm" src="https://user-images.githubusercontent.com/18075411/30516058-15cad168-9b02-11e7-92bf-c6e6bf17e2e3.png">
<img width="738" alt="screen shot 2017-09-16 at 5 10 53 pm" src="https://user-images.githubusercontent.com/18075411/30516057-15cac1a0-9b02-11e7-88bc-64f125251e5e.png">

**Comment by Sjones352** [comment]
@wturne and @kierachell  
Please refer to Updated FAQs and see that these sections were updated 
[eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1293453/eFolder.Express_Frequently.Asked.Questions_Sep2017.pdf)

**Section 1**
<img width="1095" alt="screen shot 2017-09-17 at 2 42 06 pm" src="https://user-images.githubusercontent.com/23080951/30523846-fa998a32-9bb6-11e7-9654-ef7704b1580f.png">

**Section 19**
<img width="980" alt="screen shot 2017-09-17 at 2 42 18 pm" src="https://user-images.githubusercontent.com/23080951/30523854-14a42982-9bb7-11e7-86bf-96484eeacd2d.png">

**Comment by kierachell** [comment]
**PASSED***

updated AC to current state? Great.
