### ISSUE TITLE
Design tweaks to download progress page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#52]
Every user we saw didn't understand that they could close the window and get back to it. The take a breather messaging was not clear and perhaps not very noticeable. Here are some things that might make it better:

- Revise the copy to something like "You can close this page and your documents will still download."
- Consider putting the message under the fetching status bar
- Consider changing the color to yellow instead of blue

**Comment by KHarshawat** [comment]
From @maryannbrody on the wording of this message

>  ​*I think i put some in the doc, but basically i think it should just be exactly what you mean by take a breather -- how about, "You can close this window — your documents will still download. The download will be on the home screen under your search history"*​  **or something like that**

**Comment by shanear** [comment]
For development:
https://marvelapp.com/h141bc#13388414

**Comment by KHarshawat** [comment]
@shanear I got this take a breather messaging from @maryannbrody to include in this page. Please incorporate as you do development.

**You can close this page at any time.** 
eFolder Express will still continue downloading.  Go to your home screen — https://efolder.cf.ds.va.gov — to open the documents once they've finished.
