### ISSUE TITLE
Implement user based access to VVA integration

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#529]
AC:
Enable VVA service for a user
and ensure it is not enabled globally

**Comment by kierachell** [comment]
### Enabled User

```
FeatureToggle.enable!(:vva_service, users: ["CASEFLOW_283"])                  
=> true
```
![screenshot_2017-07-14_13-20-11](https://user-images.githubusercontent.com/18075411/28222875-38d87e6e-6897-11e7-82e2-837a39b9d93d.png)

![screenshot_2017-07-14_13-21-22](https://user-images.githubusercontent.com/18075411/28222912-5b2ea754-6897-11e7-8fda-2c8c570f9982.png)

### Not-enabled user:
![screenshot_2017-07-14_13-22-20](https://user-images.githubusercontent.com/18075411/28222973-94724ce6-6897-11e7-945a-5826a6eed5d1.png)
![screenshot_2017-07-14_13-22-53](https://user-images.githubusercontent.com/18075411/28222974-9476f764-6897-11e7-8ebd-8413cab5ea3b.png)

### After enabling -> Searching -> then Disabling:
Seems like there's no check for document type when cached on S3?
![screenshot_2017-07-14_13-26-52](https://user-images.githubusercontent.com/18075411/28223125-26911a1c-6898-11e7-9d98-167fea2eda82.png)

**Comment by kierachell** [comment]
**PASSED**

validated in prod
no screenshots because PII
