### ISSUE TITLE
Timeline for VVA rollout

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#534]
Timeline for gradual roll-out of eX + VVA.

The plan is to test the coach marks with users at the BVA FOIA office starting on 8/1 and to allow these users to continue using the application thereafter. This will allow us to test the load that a small group of users places on VVA. 

Thereafter, we will do a gradual roll out adding approximately 5 user a week every Monday  at 6am until we are confident that we can manage adding a larger number of users each week.

## Suggested eX + VVA Roll Out Schedule

**Week 1** 
4 users (BVA FOIA)

  | Date| Time | User Group | User Name | User Contact
  ---|---|---|---| ---|
  Tues 8/1 | 2 pm | BVA FOIA | LaToya Mingledorph | Latoya.Mingledolph@va.gov
  Wed 8/2 | 1 pm | BVA FOIA | Tecola Plowden | Tecola.Plowden@va.gov
  Thurs 8/3 | 9 am | BVA FOIA | Andre Millhouse | Andre.Milhouse@va.gov
  Thurs 8/3 | 10 am | BVA FOIA | LaShawn cooke | Lashawn.Cooke@va.gov

**Week 2**
6 users (OGC )
All users will receive eX + VVA on 8/7 and will participate in a usability follow-up session on the date/time indicated below.

  | Date | Time | User Group | User Name | User Contact
  ---|---|---|---|---|
  | | | OGC | David Quinn (out until 8/7) | david.quinn@va.gov
  ~~~Mon 8/7~~~ | ~~1 pm~~ |  OGC | George Morris | George.Morris@va.gov
  Tues 8/8 | 10 am  | BVA FOIA | Oneal Drummond  | Oneal.Drummond@va.gov
  Tues 8/8 | 11 am | OGC | Clinton Lee | Clinton.Lee@va.gov
  Tues 8/8 | 2 pm | OGC | John Matthews | john.matthew@va.gov
  Wed 8/9 | 12:30 pm | OGC | Catherine Chase | Catherine.Chase@va.gov
  ~~Wed 8/9~~ | ~~1:15 pm~~ | OGC | Drew Silow | Drew.Silow@va.gov
  Thurs 8/10 (or after) | ?  | BVA FOIA | Jessie Retan | Jessie.Retan@va.gov

**Week 3**
Reader Pilot users Group 1?

**Week 4**
Reader Pilot users Group 2?

**Week 5**
5 users (RMC)

**Week 6**
10 users (RMC)

**Week 7** 
20 users (RMC)

**Week 8**
30 users (RMC)

**Week 9**
40 Users (RMC)

**Week 10**
x? users (Honolulu RO)

**Comment by lakohl** [comment]
We will begin testing 7/31. Right now the plan is to give VVA access going forward to the BVA users who do testing with us that week. Then we will roll out to users at other stations with small user groups -e.g. OGC and Hawaii. RMC rollout will be incremental. It will be easier to estimate if we can addd more than 5 people per week after our testing the week of 7/31.

**Comment by lakohl** [comment]
Still waiting to hear back from David Quinn/OGC with a list of names to test/roll out to the week of 8/6.
Need to make a plan for roll-out with RMC.

**Comment by lakohl** [comment]
@aroltsch and @askldjd see above. I will be out 8/11-8/24. So my question is whether you want me to add a batch of users that week or if you prefer to wait til the week of 8/24 to start adding RMC users?

**Comment by lakohl** [comment]
@aroltsch @askldjd I talked to MArk and Abby briefly about rolling out eX + VVA to Reader users  on Week 3. I was wondering what you think about releasing to Reader before RMC? Was thinking of setting up a conversation with you and the Reader folks on Friday or Monday to plan.

**Comment by nikitarockz** [comment]
@lakohl Here's a list of current eFolder Express users as of 8/3/2017.  There are a total of 565 users.   534 of whom have used it within the last 14 days.  There are a couple of users whose accounts are inactive.  I just thought this might be useful in your planning.

[eFolder Express - Current Users as 8-3-2017.xlsx](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/1198514/eFolder.Express.-.Current.Users.as.8-3-2017.xlsx)

**Comment by lakohl** [comment]
Usability sessions with George Morris and Drew Silow were cancelled bc they do not have permission to use eX. I have provided Drew Silow and George Morris instructions on how request access to eX .

**Comment by nikitarockz** [comment]
Here's the Midwest User List (All).  User Ids and confirmation of access have been added.  Additionally, there is a roll-out schedule based on total users.

[eFolder Express + VVA Rollout Users.xlsx](https://github.com/department-of-veterans-affairs/appeals-pm/files/1242997/eFolder.Express.VVA.Rollout.Users.xlsx)
