### ISSUE TITLE
API | Make secure

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#535]
We need a way to authenticate callers to our new API, and we should not be passing sensitive information as a get parameter.

# AC
1. Verify the apis only respond with information when either the static API key is passed or when the user has a valid token.
1. Verify that for the files api the file_number is passed in the header.
1. Verify that for the files api the station_id and css_id are passed in the header.

**Comment by astewarttistatech** [comment]
@mdbenjam ISo tried a few scenarios that have been tried are: 
 
1. Station ID not passed:  

{"errors":[{"status":"500","title":"Unknown error occured","detail":"ERROR:  null value in column \"station_id\" violates not-null constraint\nDETAIL:  Failing row contains (58, CASEFLOW_317, null, null, 2017-07-27 18:06:07.178415, 2017-07-27 18:06:07.178415, 0).\n (Sentry event id: cda3e1133bc448849b7ad52a5ed4aa98)"}]}


There's a Sentry error there and I'm not sure if this is to be expected

2. No file number passed: 

{"data":{"id":"659","type":"file","attributes":{"manifest_fetched_at":null,"vbms_error":true,"vva_error":false,"documents":[]}}}

Yet, this passed with a 200 and a vbms_error value of true. To be expected?

3. Invalid Token: 

{"status":"unauthorized"}  

Is this to be expected?

4. Invalid css_id: 

The response is too long for this ticket, but it does return a 200 and a response as if it were valid. I also do not know if this is to be expected.

**Comment by mdbenjam** [comment]
#3 is correct. #1, 2, and 4, are undefined, but should probably return an error. I will post an update.

**Comment by astewarttistatech** [comment]
@mdbenjam Did you post an update?

**Comment by mdbenjam** [comment]
@astewarttistatech Sorry I merged a change to address the other issues. We return 400's if a header is not provided.

**Comment by astewarttistatech** [comment]
Errors are now being passed for scenarios 1, 2, and 4.

**PASSED**
Env: Terminal/Console

Steps to Validate: 
1. Pass station_id, css_id, and file_numbers incorrectly to see if a correct error appears.
2. Pass station_id, css_id, and file_numbers correctly to see if the results touch the API correctly
