### ISSUE TITLE
CORS | Enable CORS on eFolder Express to allow the caseflow frontend to hit the document endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#536]
In order to retrieve documents from eFolder Express via the frontend we need to enable CORS.

# AC
1. Verify we can make requests to the document eFolder endpoint from the Caseflow app.

**Comment by kierachell** [comment]
**PASSED**

<img width="1418" alt="screen shot 2017-07-26 at 11 22 04 am" src="https://user-images.githubusercontent.com/18075411/28631545-97923766-71fb-11e7-914a-8f647e38614a.png">
