### ISSUE TITLE
Feature Flag | VVA | Enable for BVA FOIA/PA users week of 7/31

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#543]
As Product Owner, I would like the VVA feature flag enabled on Monday, 7/31/2017 so that all users can enjoy this new feature.

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following BVA FOIA/PA users only on the following days/times.

    | Date | Time | User Group | User ID | Name
     ---|---|---|---|---|
    Tues 8/1 | 2 pm | BVA FOIA |VACOMINGLL | MINGLEDOLPH, LATOYA 
    Tues 8/1 | 2 pm | BVA FOIA |  BVALSCREDLE | COOKE, LASHAWN A 
    Wed 8/2 | 1:30 pm | BVA FOIA | | PLOWDEN, TECOLA 
    Thurs 8/3 | 9 am | BVA FOIA | BVAAMILHOUSE | MILHOUSE, ANDRE

## Related Stories
IP | VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)
IP | eFolder Express | VVA | Request feature flag enabled [#1474](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1474)

**Comment by lakohl** [comment]
@aroltsch I just updated the table above. We need to get the user ID for Tecola Plowden

**Comment by lakohl** [comment]
@aroltsch I just updated the times above
