### ISSUE TITLE
ActiveRecord::StatementInvalid in DownloadsController#new

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow-efolder#546]
# Summary
When restarting Rails on local (and cookies exist for eFolder on the user's computer), this message appears on startup:
<img width="1276" alt="screen shot 2017-07-24 at 1 19 51 pm" src="https://user-images.githubusercontent.com/4773320/28536522-e39255e2-7075-11e7-8154-7968ee3146b3.png">

A temporary workaround exists:
![efolder-fix](https://user-images.githubusercontent.com/4773320/28536542-f1d07364-7075-11e7-91a8-37da9c669440.gif)

But this message should not appear when starting Rails server.

**Comment by aroltsch** [comment]
Fixed.
