### ISSUE TITLE
Attempted to update a stale object: Download

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow-efolder#547]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/321/ 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/329/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/510/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/489/ 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/491/

**Comment by mmlumba** [comment]
Related timeout errors for issue 510 in Sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/509/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/508/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/506/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/505/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/504/

**Comment by nickheiner-usds** [comment]
I can see that Sentry issue 329 is related, because it has the same error message as Sentry issue 510. But why do we think the others are related?

**Comment by nickheiner-usds** [comment]
@amprokop is this related to #650?

**Comment by nickheiner-usds** [comment]
Possibly related: #626.

**Comment by aroltsch** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/650
