### ISSUE TITLE
Re-enable Google Analytics

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow-efolder#548]
We first added Google Analytics in #216, but it no longer works. 

## Acceptance Criteria
For GA account `UA-74789258-2`, metrics show up.

**Comment by kierachell** [comment]
@NickHeiner 
- I don't have/know access to our GA account
- Also, I don't know if UAT/Preprod servers send the events to GA
Shall I get @shanear to validate this?

**Comment by NickHeiner** [comment]
@kierachell you should definitely have access to our GA account. What email should I use? I can add you.

Yes, with this change, UAT and preprod will send events to GA. When we query in GA, we'll set up a filter to only view prod traffic.

**Comment by kierachell** [comment]
**PASSED**
@shanear added me to the account:
<img width="970" alt="screen shot 2017-07-25 at 7 23 10 pm" src="https://user-images.githubusercontent.com/18075411/28597961-c02b7274-716e-11e7-8878-763d946e5d2d.png">
