### ISSUE TITLE
Use a unique and more descriptive filename than "documents.zip"

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#55]

**Comment by shanear** [comment]
@KHarshawat still waiting on what this should be

**Comment by KHarshawat** [comment]
@shanear Let's make this [First Name and Last Name]-[Date Fetched From VBMS].zip so `kaviharshawat-20160610.zip`. I want the name to be easy to identify when a person downloads it but I also want to make sure the user understands when the snapshot of the eFolder was taken. I'm explicitly not including the file number.

What are your thoughts on including something for when some files could not be downloaded such as `kaviharshawat-20160610-missingfiles.zip`?
