### ISSUE TITLE
Demo | Zipfile deleted too quickly?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#550]
# Description
When downloading the zip file in `demo`,
it seems like the file is deteled a bit too fast from the server,
which results in eFolder to look for a non existent S3 bucket.

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder in `demo`
1. Search for a file
1. Retireve the documents
1. Click Download the zip file
1. Click Download again just for shits.
1. See Rails error

**Validated in the following Environment(s)**
- [X] Demo
- [ ] UAT
- [ ] Preprod
- [ ] Prod

## Logs:
```
[dsva-appeals-efolder-demo-911721293.us-gov-west-1.elb.amazonaws.com] [25a52673-321
b-4c7e-8001-9091a9786cc3] [localhost] [CSFLOW8 asdasd@jesus.com] [2017-07-24 17:59:38 -0400]
Completed 500 Internal Server Error in 181ms (ActiveRecord: 5.8ms)
dsva-appeals-efolder-demo/opt/efolder-express/src/log/efolder-express.out i-0cbc89b14dd1a4915-172.30.68.65 [dsva-appeals-efolder-demo-911721293.us-gov-west-1.elb.amazonaws.com] [25a52673-321b-4c7e-8001-9091a9786cc3] [localhost] [CSFLOW8 asdasd@jesus.com] [2017-07-24 17:59:38 -0400]
dsva-appeals-efolder-demo/opt/efolder-express/src/log/efolder-express.out i-0cbc89b14dd1a4915-172.30.68.65 Errno::ENOENT (No such file or directory @ rb_sysopen - /opt/efolder-express/src/tmp/files/122/User, Test - 1224.zip):
app/services/download_documents.rb:93:in `stream_zip_from_s3'
app/controllers/downloads_controller.rb:62:in `download'                                                                                                                               app/middleware/metrics_auth.rb:10:in `call'
```

## Screenshots
**_Scenario 1 - [sad!]_**

![screenshot_2017-07-24_18-02-37](https://user-images.githubusercontent.com/18075411/28546936-8128fe36-709a-11e7-8ec0-3d9cb08d4781.png)

**Comment by aroltsch** [comment]
We can close this ticket because now Demo is using AWS s3.
