### ISSUE TITLE
Feature Flag | VVA | Enable for OCG an remaining BVA FOIA users - 8/7/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#553]
As Product Owner, I would like the VVA feature flag enabled on Monday, 8/7/2017 so that all users can enjoy this new feature.

## Acceptance Criteria
1.	Verify that the feature flag has been enabled at 6 am on the day listed for the following OCG users only.

  | Date | User Group | User Name | User Contact| User ID
  ---|---|---|---|---
  Mon 8/7 | OGC | David Quinn | david.quinn@va.gov |VACOQUINND1
  Mon 8/7 | OGC | Catherine Chase | Catherine.Chase@va.gov |VACOCHASEC
  Mon 8/7 | OGC | George Morris | George.Morris@va.gov | VACOMORRIG
  Mon 8/7 | OGC | John Matthews | john.matthew@va.gov | VACOMATTJ 
  Mon 8/7 | OGC | Clinton Lee | Clinton.Lee@va.gov | VACOLEECL
  Mon 8/7 | OGC | SILOW, DREW | Drew.Silow@va.gov | |
  Mon 8/7 | OGC | Naquetta Wortham (on leave) | Naqueeta.Wortham@va.gov |VACOWORTHN 
  Mon 8/7   | BVA FOIA  | DRUMMOND, ONEAL |  Oneal.Drummond@va.gov | BVAODRUMMOND
  Mon 8/7  | BVA FOIA |  RETAN, JESSIE | Jessie.Retan@va.gov |

## Related Stories
IP | VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)
IP | eFolder Express | VVA | Request feature flag enabled [#1474](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1474)

**Comment by aroltsch** [comment]
VVA is enabled for all above users except Drew.Silow@va.gov and George.Morris@va.gov. I could not find CSS ID of Drew.Silow@va.gov. George.Morris@va.gov does not have access to EX. 
@nikitarockz @lakohl

**Comment by lakohl** [comment]
I have provided Drew Silow and George Morris instructions on how request access to eX and have cancelled their usability sessions.
