### ISSUE TITLE
BGS Service | Handle cases when Vet has No SSN

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#554]
# Description
When we receive data from BGS about a particular veteran,
We do not have a way of handling lack of SSNs.

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Search for a filenumber for a veteran with no SSN
1. See sentry errors
1. See Sidekiq go into a retry loop

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:

`undefined method `fetch_veteran_info' for nil:NilClass`
https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/external_api/bgs_service.rb#L19

- BGS resulting hash:
```
vet.keys
=> [:brthdy_dt, :death_dt, :email_addr, :file_nbr, :first_nm, :first_nm_key, :jrn_dt, :jrn_lctn_id, :jrn_obj_id, :jrn_status_type_cd, :jrn_user_id, :last_nm, :last_nm_key, :middle_nm, :middle_nm_key, :mlty_person_ind, :person_death_cause_type_nm, :ptcpnt_id, :ssn_vrfctn_status_type_cd, :station_of_jurisdiction, :suffix_nm_key, :termnl_digit_nbr, :vet_ind]
irb(main):058:0> vet[:ssn_nbr]
=> nil
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/325/

**Comment by nickheiner-usds** [comment]
@mdbenjam, you commented on Slack and said that you fixed this issue: https://dsva.slack.com/archives/C4JECDLSE/p1502204567912429?thread_ts=1502121617.108304&cid=C4JECDLSE. Do you think this is still a problem? Should this ticket be closed?

**Comment by mdbenjam** [comment]
Yeah I think we can close this.

**Comment by aroltsch** [comment]
@NickHeiner I talked to Artem. He believes this Sentry error happens when veteran's SSN is nil. It is a download with ID `36943` in production.

**Comment by aroltsch** [comment]
Artem will do more debugging on this so assigning to him.

**Comment by kierachell** [comment]
**PASSED**
- UAT case: `00000001`
<img width="717" alt="screen shot 2017-11-14 at 2 23 57 pm" src="https://user-images.githubusercontent.com/18075411/32800122-8322218a-c947-11e7-8308-bef93fab96d9.png">

- Works!
<img width="921" alt="screen shot 2017-11-14 at 2 25 16 pm" src="https://user-images.githubusercontent.com/18075411/32800185-acd036de-c947-11e7-99b6-84331e6fd4f0.png">
