### ISSUE TITLE
Expose the `Accept-Ranges`HTTP Header for Reader

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow-efolder#556]
PDF.js reads the `Accept-Ranges` HTTP header to determine how to retrieve the PDF for Reader. It throws an error `Refused to get unsafe header "Accept-Ranges"` if it cannot read the header. 

Allow the header to be read in the HTTP response to prevent this.

- Connects https://github.com/department-of-veterans-affairs/caseflow/issues/2340

# AC
- Requests to `/api/v1/documents` returns the `Accept-Ranges` HTTP header for all requests
- Requests when Reader loads documents no longer return errors

**Comment by kierachell** [comment]
**PASSED**
- So I enabled the `efolder_reader_api` on Caseflow
- Then ran an `ajax` request:
```
$.ajax({
   url: 'https://efolder.cf.uat.ds.va.gov/api/v1/documents/293663',
   xhrFields: {
      withCredentials: true
   }
});
```
- And got pdf content back with response headers:
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:https://appeals.cf.uat.ds.va.gov
Access-Control-Expose-Headers:content-range, content-length, accept-ranges
Access-Control-Max-Age:1728000
Cache-Control:max-age=2592000, public
Content-Disposition:attachment; filename="5103  DTA Letter-20161222-C19F34A4-21EF-4AC8-9D33-05B3F5ED5370.pdf"
Content-Transfer-Encoding:binary
Content-Type:application/pdf
Date:Tue, 01 Aug 2017 01:03:10 GMT
ETag:W/"5c13b4868efb35d28c690c6b07f233b5"
Server:nginx/1.10.3
Vary:Origin
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Request-Id:b840b3ca-07fb-4e29-8126-23628a67a4ad
X-Runtime:0.300599
X-XSS-Protection:1; mode=block
```
