### ISSUE TITLE
Feature Flag | VVA | Enable for OGC users - 8/7

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#560]
## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following BVA FOIA/PA users only at 6am on the day listed below.

  | Date | User Group | User Name | User Contact| User ID
  ---|---|---|---|---
  Mon 8/7 | OGC | David Quinn | david.quinn@va.gov |VACOQUINND
  Mon 8/7 | OGC | Catherine Chase | Catherine.Chase@va.gov |VACOCHASEC
  Mon 8/7 | OGC | George Morris | George.Morris@va.gov | VACOMORRIG
  Mon 8/7 | OGC | John Matthews | john.matthew@va.gov | VACOMATTJ 
  Mon 8/7 | OGC | Clinton Lee | Clinton.Lee@va.gov | VACOLEECL
  Mon 8/7 | OGC | Naquetta Wortham | Naqueeta.Wortham@va.gov |VACOWORTHN 

## Related Stories
IP | VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)
IP | eFolder Express | VVA | Request feature flag enabled [#1474](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1474)

**Comment by nikitarockz** [comment]
# Closing
@lakohl I had already created a story for this.  Feature Flag | VVA | Enable for OCG users - 8/7/2017 #553
