### ISSUE TITLE
[v2] Manifests Endpoint | Move calls to be async 

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#562]
# AC
1. Verify when api/v2/manifests is called it should return immediately with whatever files exist in the DB
1. Verify when api/v2/manifests is called it starts a background job that downloads the document list and returns status as `pending`
1. Verify api/v2/manifests returns a fetched_at time for each source (VBMS and VVA) of when the background job last finished.

**Comment by aroltsch** [comment]
Tech details: 
The files endpoint is using `perform_now` which is synchronous. 

Method peform_later is asynchronous. When you use this method, the job is not run at the moment, but rather is pushed in a job's queue. Method perform_now is synchronous and will run the job at the moment, no matter what is the job's state.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT | Postman

Screenshots:

<img width="860" alt="screen shot 2017-12-21 at 10 21 05 am" src="https://user-images.githubusercontent.com/23038505/34263863-e41e6c64-e63e-11e7-9180-178e9f8fd315.png">
<img width="861" alt="screen shot 2017-12-21 at 11 04 31 am" src="https://user-images.githubusercontent.com/23038505/34263864-e425ec5a-e63e-11e7-81dd-feb4bde3ec56.png">
