### ISSUE TITLE
Lines are missing between some docs on the doc manifest

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#563]
When reviewing the doc manifest with @Sjones352 we noticed that the some lines are missing between docs in the doc manifest. 

## AC
Ensure there is a horizontal line separating each document in the file manifest on the the Retrieve eFolder page or on the Download eFolder page.

## Mock
![screen shot 2017-07-31 at 12 08 14 pm](https://user-images.githubusercontent.com/4975959/28834855-862158c6-76b1-11e7-8817-e5473b339c43.png)

**Comment by mmlumba** [comment]
@lakohl @kierachell @Sjones352 Is there are a particular case number/environment that this happened on?

**Comment by lakohl** [comment]
Mmm I will try to see if I have more info
