### ISSUE TITLE
Extra line shows below last document in doc manifest

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#564]
When reviewing this with @Sjones352  we noticed that there is an extra line shows below last document in doc manifest. 

## AC
Ensure that there is not an extra line below the last document in the doc manifest (e.g. below 'Birth Certificate' in the mock) on the the Retrieve eFolder page or on the Download eFolder page.

## Mock
![screen shot 2017-07-31 at 12 08 14 pm](https://user-images.githubusercontent.com/4975959/28835062-2e0237ea-76b2-11e7-8ae5-005f701805ae.png)

**Comment by Sjones352** [comment]
Currently 

![efolder-extralines](https://user-images.githubusercontent.com/23080951/29008335-1b06f362-7ae3-11e7-98c4-eadc0bbfad99.gif)

**Comment by mmlumba** [comment]
@lakohl The mock above has the bottom line disappearing on scroll. Is this alright with you?

**Comment by lakohl** [comment]
Looks much better @mmlumba Thanks!

**Comment by kierachell** [comment]
**PASSED**
<img width="1085" alt="screen shot 2017-08-08 at 6 31 27 am" src="https://user-images.githubusercontent.com/18075411/29068076-3ce05d68-7c03-11e7-9c3b-bee4314467f8.png">
