### ISSUE TITLE
Make all eX buttons comply with Caseflow Commons styling

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#565]
Ensure that all eX buttons are sentence case and follow the measurements set out in Caseflow Commons.

## AC
1. Verify that all eX buttons are sentence case.
1. Verify that the height of all the eX buttons (including the new copy Vet ID button) follows Caseflow Commons.
1. Verify that the styling of the padding to the left and right of the button label is in accordance with Caseflow Commons.

**Comment by Sjones352** [comment]
Currently

![buttons](https://user-images.githubusercontent.com/23080951/28954990-ee4a5492-78b0-11e7-85e1-d2c7bba70f38.gif)

**Comment by lakohl** [comment]
nice!

**Comment by astewarttistatech** [comment]
@Sjones352 Which buttons are "eX buttons"?

**Comment by lakohl** [comment]
@astewarttistatech all the buttons in the eX application should follow Caseflow Commons guidelines (they were too big).

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access eFolder Express
2. Check that all buttons meet the 10x20 padding exception

Screenshots:
<img width="1248" alt="screen shot 2017-08-07 at 11 18 17 am" src="https://user-images.githubusercontent.com/23038505/29033184-31c9043a-7b62-11e7-961c-ae79e2e73a88.png">
