### ISSUE TITLE
VVA coach marks - Hide Tutorial link is not always present at the top of the page

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#566]
AC:
When VVA service is enabled, ensure Hide Tutorial link is present on every page.

**Comment by mmlumba** [comment]
@aroltsch Are you sure you want this to be on every page? It doesn't make sense to have this link up when you're on a page that doesn't have coachmarks.

**Comment by aroltsch** [comment]
that's a very good question. @lakohl or @Chingujo can you please assist.

**Comment by Chingujo** [comment]
Seems the only page other than the loading spinner screen without Hide Tutorial is the retrieving page below. The only interaction on this page is the efolder express home page link, which does not have a coach mark. So makes sense to me that hide tutorial does not show. Defer to @lakohl tho, as there could be plans to incorporate one here?

<img width="1086" alt="screen shot 2017-08-15 at 8 19 32 am" src="https://user-images.githubusercontent.com/23316107/29316493-3f22de50-8196-11e7-9f6f-a7cf19a3a3ab.png">

**Comment by mmlumba** [comment]
@Chingujo If there is an error retrieving files (either VBMS error, veteran ID doesn't exist, a few downloads didn't work, etc.) then the coach marks don't appear on those screens either.

**Comment by Chingujo** [comment]
Thanks Marian! Don't have specific pages listed, so can't tell if we are adding the hide tutorial to these pages or if there is an issue of a hide tutorial not showing up on a page it should (since it was a bug). Need more context here, so will follow up with Lara when she's back or report if I see an issue in some user testing.

**Comment by Chingujo** [comment]
Talked with @lakohl. Great pointing this out @mmlumba and @aroltsch 

We are leaving it as is (no hide tutorial on pages without coach marks). Closing this out.
