### ISSUE TITLE
Feature Flag | VVA | Enable for Reader users -delayed

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#570]
Reader users would like access to eX + VVA

~~Suggestion is to enable the VVA feature flag for at least a portion of Reader users on Monday, 8/14/31 so that attorneys can view VVA docs in Reader~~ . 

We are holding off on this until Sept.

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following Reader users only on the following days/times:

     Date | Time |User Group | User ID | Name
     ---|---|---|---|---|

# Related Stories
EPIC: IP | eFolder Express - VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)

**Comment by lakohl** [comment]
@aroltsch @askldjd @mdbenjam Let's discuss dates, number of users, and technical considerations on Friday 8/4?

**Comment by abbyraskin** [comment]
👍

**Comment by aroltsch** [comment]
Are we going to have this discussion? @lakohl

**Comment by abbyraskinUSDS** [comment]
I think we're going to have to push out rollout on the Reader side (as we're still working on eX integration), but happy to have a conversation about a general plan moving forward.

**Comment by lakohl** [comment]
@aroltsch and @mdbenjam @askldjd  it would be helpful if you all could chat and outline here any concern you have about adding VVA functionality for Reader users.

**Comment by aroltsch** [comment]
@mdbenjam @askldjd let's chat tomorrow?

**Comment by mattwilcut** [comment]
Please see the above referenced item.  Feel free to contact at matthew.wilcut318@va.gov but would prefer to keep it here.
