### ISSUE TITLE
Retrieving docs page momentarily shows 'no documents'

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#572]
Right before/as all the files are fetched the following things happen:

1. Hide tutorial disappears from the top of the page
1. The document manifest disappears and the message: 'There are no documents' is displayed. 1. A second or two later, the manifest and link reappear and the user is able to download the efolder.

**Comment by amprokop** [comment]
@lakohl — does this happen all the time? On every environment or just UAT/prod? 

@kierachell, can we repro this and add steps to repro in the ticket if we're successful?

**Comment by lakohl** [comment]
This was something I observed twice during usability testing in Prod. It happened while the eFolder was being retrieved and right before it was ready for download.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by kierachell** [comment]
Too many errors in eFolder UAT right now to drill down this issue

**Comment by kierachell** [comment]
Not seeing this happen after running 50 filenumbers :(

**Comment by Chingujo** [comment]
Observed during user testing but could not be replicated. Talked with a few users after and could not replicate I think its good to close @lakohl

**Comment by lakohl** [comment]
Yes, we can close it. But @Sjones352 @RTOLSON take a look at this issue just so you are aware, in case it gets called in to Support.

**Comment by Chingujo** [comment]
Closing per above thanks!
