### ISSUE TITLE
VVA coach marks - Extra long underline under Hide Tutorial

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#573]
Hide Tutorial displays across the app (in IE) with an extra long underline that extends to the right all the way to the user name.

**Comment by amprokop** [comment]
Can we add steps for a dev to reproduce? Not sure if we have to turn coach marks on locally or not.

**Comment by lakohl** [comment]
This was observed on more tan one occasion during usability testing with users who use IE as their browser. I was not able to recreate it on my laptop, but it may be a variant of the following artifact which displays on my computer after the link has been clicked once:
<img width="508" alt="screen shot 2017-08-07 at 3 18 24 pm" src="https://user-images.githubusercontent.com/4975959/29042183-e21f8572-7b83-11e7-9e72-6e69bda8073c.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: IE

Steps to Validate: 
1. Access eFolder with a css id that has coachmarks enabled. 
2. Validate that the underline doesn't stretch passed the "Hide Tutorial" hyperlink. 

Screenshots: 
![coachmarksie](https://user-images.githubusercontent.com/23038505/29367845-2cb25fa8-826c-11e7-9371-5a258867c514.gif)
