### ISSUE TITLE
S3 file name should be the external file id

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#582]
Currently we name files in S3 based on the download and local document ids. We should instead name them based on the external id. This way if multiple users try to download a case, the files only need to be added to S3 once.

# AC
1. Verify the S3 filename is the same as the id coming from VBMS or VVA.

**Comment by kierachell** [comment]
**PASSED**
<img width="924" alt="screen shot 2017-08-10 at 8 19 33 pm" src="https://user-images.githubusercontent.com/18075411/29197425-43ad87d0-7e09-11e7-9f56-ff9b67d7b9ac.png">
