### ISSUE TITLE
Remove code to look for old S3 name

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#583]
About 2 months ago we changed the file names of documents in S3. We still looked for the old name if we couldn't find the new name so that we wouldn't break functionality when we rolled out. Since the S3 bucket expires documents after 2 weeks, and this change was more than 2 months ago, the old named documents are expired, and we are able to remove this code.

## AC (for dev to check):
- Verify all references to the `old_s3_filename` are gone

## AC (for QA to check):
- Verify documents still get fetched from S3

**Comment by nickheiner-usds** [comment]
> Now the old named documents should be expired, and we should be able to remove this code.

Is there a way that we can get a more rigorous level of certainty than "should" here? :smile: It would be nice to ensure that we're not going to cause any errors.

**Comment by mdbenjam** [comment]
Updated to explain my reasoning.

**Comment by kierachell** [comment]
**PASSED**

- Checked S3 to see if any PDFs remained with old names:
<img width="522" alt="screen shot 2017-10-20 at 9 45 39 am" src="https://user-images.githubusercontent.com/18075411/31823885-8bf6843e-b57b-11e7-86df-03d24d5f898d.png">
<img width="685" alt="screen shot 2017-10-20 at 9 45 43 am" src="https://user-images.githubusercontent.com/18075411/31823886-8c1ab854-b57b-11e7-915b-2d599d8ed587.png">
<img width="681" alt="screen shot 2017-10-20 at 9 45 46 am" src="https://user-images.githubusercontent.com/18075411/31823887-8c38152a-b57b-11e7-82cb-1ac53e9a5c61.png">
