### ISSUE TITLE
Retrieving Files | Estimated time disappears momentarily

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#587]
# Description
When retrieving files from eFolder,
estimated time disappears here and there for some strange reason.

## Reproduction Steps

**Scenario 1 -**

1. Go to retrieve documents
1. Start retrieving
1. Get a nice estimate for wait time
1. Have it disappear
1. Be sad
1. Have it pop back up
1. Be happy.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Peace]_**
![disappear](https://user-images.githubusercontent.com/18075411/29073224-d9a3ad52-7c18-11e7-9c77-f79b2ec4eab3.gif)

**Comment by aroltsch** [comment]
@Sjones352 is it something you'd like to investigate?

**Comment by Sjones352** [comment]
@aroltsch Yes I will definitely investigate

**Comment by kierachell** [comment]
**PASSED**
![try](https://user-images.githubusercontent.com/18075411/33177583-27c6cd36-d031-11e7-8d06-abc840a9a859.gif)
