### ISSUE TITLE
Store user's roles and login timestamp

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow-efolder#589]
On successful authentication from CSS, we want to store the current login timestamp and the user's roles.

#### Acceptance Criteria
- Add 2 new columns to the User model. 1 array column `roles` [like in Caseflow](https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/migrate/20170509175505_add_roles_to_users.rb) and 1 timestamp column for last login timestamp.
- On successful CSS authentication, persist the current timestamp and their CSS roles to the user record
- On successful CSS authentication, add the last login timestamp to the user's session cookie. This is so that Caseflow can learn  the last login timestamp.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
