### ISSUE TITLE
Coach marks: clicking X should only clear that instance

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#593]
As a user, I want to be able to close a single coach mark but still see all the other coach marks. Currently clicking the 'x' functions in the same way as the 'Hide Tutorial' link. 

AC
1. When a user click the 'X' on a coach mark it should hide that coach mark (a single instance), but not the other coach marks on the same page or on other pages of the application.

**Comment by mmlumba** [comment]
@lakohl @annienguyenUSDS @shellicious @Chingujo Do you guys have any notes from the user session(s) when this happened (the browser they were using, when this scenario happened, etc)? I recreated this behavior in both Chrome and IE11 and both browsers work as expected:
![ie11-coachmarks-efolder](https://user-images.githubusercontent.com/4773320/29296825-b9a54242-812a-11e7-945f-4f4e0ef6ac84.gif)

(gif from IE11)

**Comment by Chingujo** [comment]
Slams head on desk after realizing we did not record......It was with [Oneal Drummond](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/eFolder%20Express/User%20Research%20Documents/VVA%20Usability%20Research/Oneal.md)

I can check on the IE version/reach out but its their wfh day as well. It could be possible that clicking on a specific coach mark makes this happen (i.e. existing out of the first on a lower version of IE?)?

Annie and I also have a usability session tomorrow with Jessie and will see if this bug happens again.

**Comment by Chingujo** [comment]
Sat with the Onea, the user, and verified that this occurred and is **no longer** an issue. Verified with a 2 other users as well. Will connect with Lara in case of missing context but no seems things are working as intended. 

### Original Steps of reproduction

- [ ] Clicking back to the home page
- [ ] Xing out of the coach mark 
- [ ] Coach marks did not appear on the start retrieval page 

**Tested in Internet Explorer 11 on the same PC where this bug occurred. Mentioned there could have been an IE update recently**

### Verified coach mark behavior with

-  [ ] Oneal
- [ ] Latoya
- [ ] Jessie

**Comment by lakohl** [comment]
My vague  recollection is that this happened on the first page.

**Comment by Chingujo** [comment]
@lakohl 

YESSSSSSSSS!! Welcome back =D

Went through a few variations with the users we did some usability testing with. They didn't seem to have an issue anymore. Also tested on some older internet explorers (8, 9 and 10) using the 11 emulation mode. 

I can verify with a few others as well and can be closed?

**Comment by Chingujo** [comment]
Talked with @lakohl 

We are good to close since the bug seemed to have resolved and hasn't occurred over a few users. Will make notes as we roll to see if this becomes a recurrent issue =D. Thanks all!
