### ISSUE TITLE
Add a Coach Mark for Vet ID

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#594]
Users had a difficult time understanding what to do the button that allows them to copy the vet ID

AC
1. Add a Coach Mark for Vet ID on the eFolder Express Start Retrieval Page
1. Copy for coach mark ' This button allows you to copy the Veteran ID so that you can easily paste it in another application or document.'

**Comment by Chingujo** [comment]
@mmlumba 
In regards to your question, coach mark should appear on the first loaded page that has the vet ID, so the start Retrieving eFolder Page (ss below). Might be good to move the coach mark of the doc count to the left so there is room. cc: @lakohl to verify and for feedback.  

<img width="1130" alt="screen shot 2017-08-28 at 11 33 39 am" src="https://user-images.githubusercontent.com/23316107/29780726-c744847a-8be4-11e7-9c05-d4a0f936fe0d.png">

**Comment by lakohl** [comment]
@Chingujo I agree with you comment. If things get cramped we should move the 'total number of doc' coach mark over to the left and adjust the pointy part so it's on the right side of that coach mark.

**Comment by Chingujo** [comment]
@lakohl 

Just adding some context for confirmation =D

The coach mark placed on the upper left would cover the hide tutorial links and placing it to the far right would bleed over the canvas. Left would hide the veteran ID. Worked with @mmlumba for the placement above.

**Comment by kierachell** [comment]
VVA is down in lower environments, sent an email; waiting for response.

**Comment by kierachell** [comment]
VVA confirmed they had an outage. Waiting for fix

**Comment by kierachell** [comment]
**PASSED**
<img width="1037" alt="screen shot 2017-09-05 at 2 28 17 pm" src="https://user-images.githubusercontent.com/18075411/30076504-ff57d4ee-9246-11e7-9eb6-06456bbaf0c1.png">
