### ISSUE TITLE
Reader integration | eFolder runs out of memory during concurrent Reader/eFolder usage

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#595]
# Description
this is an old issue, but it is more relevant now that Reader relies on eFolder,
when eFolder is hit by API calls and normal UI usage, the memory goes up like mad.

Yes UAT instances are smaller, but this stress test only involved 5 concurrent sessions in Reader and 5 in eFolder so... yeah, not good.

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader with eFolder Service turned on
1. Open 5-6 document lists/views
1. Go to eFolder
1. Start downloading 5-6 of the same filenumbers or different, doesn't matter
1. Go to Grafana and watch the memory usage climb.
1. Watch eFolder die

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Grafana]_**
![efoldermemory](https://user-images.githubusercontent.com/18075411/29183583-39dceae4-7dd1-11e7-9a8f-9bb071707994.gif)

# Related Issues
**_Support_**

**_Engineering_**

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
