### ISSUE TITLE
Connecting eFolder to Staging Environment

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#601]
Currently connecting eFolder to the staging environment is difficult. It involves not just running the decrypt script (easy), but also making changes to the code (hard). We should update eFolder so that you can pass an -e staging flag to rails and automatically make those changes.

# AC
1. Verify that after running the decrypt script and passing -e staging to eFolder that you can connect to staging.
1. Verify this process is documented in the Readme.

**Comment by aroltsch** [comment]
This is done! Thanks @mdbenjam !
