### ISSUE TITLE
Implement Functions module from commons in efolder

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#603]

**Comment by kierachell** [comment]
**PASSED**

```
Functions.list_all
=> {"System Admin"=>{:granted=>["CASEFLOW_283", "CASEFLOW_317", "CF_Q_283"]}}
irb(main):003:0> Functions.deny!("System Admin", users: ["CASEFLOW_283"])
=> true
irb(main):004:0> Functions.list_all
=> {"System Admin"=>{:granted=>["CASEFLOW_317", "CF_Q_283"], :denied=>["CASEFLOW_283"]}}
irb(main):005:0> Functions.deny!("Download eFolder^C users: ["CASEFLOW_283"])
```


### Stats page
<img width="1242" alt="screen shot 2017-09-15 at 8 37 05 am" src="https://user-images.githubusercontent.com/18075411/30482465-2d38666a-99f1-11e7-96f0-26e83c17f484.png">


```
Functions.deny!("Download eFolder", users: ["CASEFLOW_283"])
=> true
```

### Just trying to do my work:
<img width="1170" alt="screen shot 2017-09-15 at 8 38 59 am" src="https://user-images.githubusercontent.com/18075411/30482517-623cfbbe-99f1-11e7-9436-af92d884a72c.png">


Overall works, just one nit:
```
Functions.grant!("System", users: ["CF_MCCOY_317"])
=> true
```

Can we have a list?
