### ISSUE TITLE
Feature Flag | VVA | Enable Group 4 - RMC/OCG users on 9/14/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#606]
As Product Owner, I would like the VVA feature flag enabled on Thursday, 9/14/2017 at 8 am (as early as possible) for the following users so that all users can enjoy this new feature.

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following RCM users only on the following days/times.

Release Date | Employee Name | Email Address | User ID
-- | -- | -- | --
9/14/2017 | Kevin Lovett | Kevin.Lovett@va.gov | VacoLovetK
9/14/2017 | Charles Haslam | Charles.Haslam@va.gov | VACOHaslaC
9/14/2017 | Ailteas Jones (Mitchell) | Ailteas.Jones@va.gov | VACOJonesA1
9/14/2017 | Silow,   Drew | Drew.Silow@va.gov | VacoSilowD
9/14/2017 | Gaw,   Matthew R. | Matthew.Gaw@va.gov | VACOGawM
9/14/2017 | Clemons,   Gabrielle | gabrielle.clemons@va.gov | VACOClemmG
9/14/2017 | Lipscomb,   James | James.Lipscomb@va.gov | CSDJLIPS
9/14/2017 | Lucas,   Dwayne | Dwayne.Lucas@va.gov | VBARMCLUCASD
9/14/2017 | Sims-Jones,   Charlotte | Charlotte.Sims-Jones@va.gov | CSDCJONE
9/14/2017 | Staples,   Nicole | Nicole.Staples@va.gov | CSDNSTAP
9/14/2017 | Steward,   Hakim | Hakim.steward@va.gov | VBARMCSTEWAH
9/14/2017 | Whitehead,   Danny | Danny.Whitehead@va.gov | CSDDWHIT
9/14/2017 | Beckum,   Kathryn | kathryn.beckum@va.gov | VBARMCBECKUK
9/14/2017 | Bell,   Charles | charles.bell2@va.gov | CSDCBELL
9/14/2017 | Bell,   Tammie | tammie.bell@va.gov | VBARMCBELLT
9/14/2017 | Binion-Whtie,   Gloretha | gloretha.binion-white@va.gov | CSDGBINI
9/14/2017 | Byrd,   Valerie | valerie.byrd@va.gov | CSDVBYRD
9/14/2017 | Magrath,   Robert | robert.Magrath@va.gov | VBARMCMAGRAR
9/14/2017 | Malone,   Willie | willie.malone@va.gov | CSDWMALO
9/14/2017 | Moody,   Donna | donna.moody1@va.gov | CSDDMOOD
9/14/2017 | Moore,   Sharon | sharon.moore1@va.gov | CSDSMOOR
9/14/2017 | Payne,   Deandshia | deandshia.payne@va.gov | VBARMCPAYNED
9/14/2017 | Peterson,   Kerry | kerry.peterson@va.gov | VBARMCPETERK
9/14/2017 | Strong,   Dobie | dobie.strong@va.gov | VBARMCSTROND
9/14/2017 | Thirdkill,   Cheri | cheri.thirdkill@va.gov | CSDCTHIR
9/14/2017 | Wells,   Laurice | laurice.wells@va.gov | CSDLWELL
9/14/2017 | Williams,   Kenneth | kenneth.williams11@va.gov | CSDKWILL
9/14/2017 | Wilson,   Latona | latona.wilson@va.gov | CSDLWILS
9/14/2017 | Wright,   Brenda | brenda.wright@va.gov | VBARMCWRIGHB
9/14/2017 | Brooks,   Helen | helen.brooks@va.gov | CSDHBROO
Total |   | 30 |  

## Related Stories
IP | VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)
IP | eFolder Express | VVA | Request feature flag enabled - Midwest [#1553](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1553)

**Comment by nikitarockz** [comment]
@lark This has been updated with the final listing of users.  It includes the 6 RMC people who all have access now.  :smile:

**Comment by aroltsch** [comment]
This is done.

```
FeatureToggle.details_for(:vva_service)
=> {:users=>["VACOClemmG", "VacoLovetK", "VACOHaslaC", "VACOJonesA1", "VacoSilowD", "VACOGawM", "CSDJLIPS", "VBARMCLUCASD", "CSDCJONE", "CSDNSTAP", "VBARMCSTEWAH", "CSDDWHIT", "VBARMCBECKUK", "CSDCBELL", "VBARMCBELLT", "CSDGBINI", "CSDVBYRD", "VBARMCMAGRAR", "CSDWMALO", "CSDDMOOD", "CSDSMOOR", "VBARMCPAYNED", "VBARMCPETERK", "VBARMCSTROND", "CSDCTHIR", "CSDLWELL", "CSDKWILL", "CSDLWILS", "VBARMCWRIGHB", "CSDHBROO"]}
```
