### ISSUE TITLE
VVA Service | Some document lists and some document files are taking over a minute to fetch

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#609]
# Description
When downloading some documents in VVA,
The response time can be over 60s...
it sucks, but happens often enough:
<img width="377" alt="screen shot 2017-09-03 at 9 49 26 am" src="https://user-images.githubusercontent.com/18075411/30003559-31c5a9b2-908d-11e7-88b1-7909b8c3d192.png">

Maybe just rescue the error and prevent auto-retries?
Enable option to "redownload only errored VVA documents" (and same for VBMS)?

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Have VVA feature turned on
1. Start downloading documents
1. Timeout either on document list or when fetching PDFs
1. See Sentry alerts
1. Note that the job goes into a retry loop

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

```
HTTPClient::ReceiveTimeoutError

execution expired
```
from either:
`@vva_client.document_content.get_by_document_id`
or
`@vva_client.document_list.get_by_claim_number`

## Sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/453/

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/393/

## Screenshots
**_Scenario 1 - [Sucks]_**
<img width="407" alt="screen shot 2017-09-03 at 9 49 07 am" src="https://user-images.githubusercontent.com/18075411/30003577-9ad0773e-908d-11e7-8100-3ade49feded0.png">

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
