### ISSUE TITLE
Feature Flag | VVA | Enable Group 3.5 - Honolulu users on 9/11/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#611]
As Product Owner, I would like the VVA feature flag enabled on Monday, 9/11/2017 at 9 am for the following users so that all users can enjoy this new feature.

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following Honolulu users only on the following days/times.

Release Date | Employee Name | Email Address | User ID
-- | -- | -- | --
9/11/2017 | HAYASHIBARA,   BRIAN M | BRIAN.HAYASHIBARA@VA.GOV | ADJBHAYA
9/11/2017 | DEXTER,   BERNADETTE | BERNADETTE.DEXTER@VA.GOV | VSCBDEXT
9/11/2017 | MCNAIR,   CHRISTOPHER | CHRISTOPHER.MCNAIR@VA.GOV | VSCCMCNA
9/11/2017 | FISHER,   PAMELA | PAMELA.FISHER459@VA.GOV | VSCPFISH
9/11/2017 | YORO,   TIFFANY DAWN | TIFFANY.YORO@VA.GOV | VSCTYORO
Total |   | 5 |  

## Related Stories
IP | VVA | Execute Plan [#1416](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1416)
IP | eFolder Express | VVA | Request feature flag enabled - Midwest, Atlantic, Pacific [#1553](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1553)

**Comment by nikitarockz** [comment]
FYI.....@lakohl This issue all updated and ready for implementation.  I am slacking it to @aroltsch .

**Comment by aroltsch** [comment]
@nikitarockz It seems as this user TIFFANY.YORO@VA.GOV is not in our DB. 
Everyone else on this issue should have access.

**Comment by nikitarockz** [comment]
@aroltsch Ok. But does it mean that everyone in our database has logged in at least once?.  We checked to make sure everyone on this list has been granted access.  However, we could have missed this person. Or is it possible that this person has never logged in to eFolder?  I will double check when I get back.

**Comment by aroltsch** [comment]
@nikitarockz I will go ahead and enable it for Tiffany even though her user record doesn't exist. 

```
FeatureToggle.details_for(:vva_service)
=> {:users=>["ADJBHAYA", "VSCBDEXT", "VSCCMCNA", "VSCPFISH", "VSCTYORO"]}
```

**Comment by aroltsch** [comment]
Closing the issue
