### ISSUE TITLE
Alert Banner Heading Styling 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#612]
### Description

@lakohl 

The H2** (edited per style guide) in alert banner in demo is Merriweather should be changed to Source Sans Pro.

### Reproduction 

1. Verify that the heading styling for banners in production is Source Sans Pro
1. Verify that the heading styling for banners in demo and other environments is Source Sans Pro

See screens shot below 
<img width="1122" alt="screen shot 2017-09-07 at 8 28 31 am" src="https://user-images.githubusercontent.com/23316107/30163335-90462e6e-93a6-11e7-9948-03009678f092.png">

**Comment by aroltsch** [comment]
@Sjones352 can you please take a look at this

**Comment by Sjones352** [comment]
@Chingujo currently the "Success" heading is in H3, do you want me to change it to H1. See pic below
<img width="1257" alt="screen shot 2017-11-14 at 8 31 48 am" src="https://user-images.githubusercontent.com/23080951/32790847-82112814-c92d-11e7-80e2-d89f4820be8c.png">

**Comment by Chingujo** [comment]
Thanks @Sjones352!

I just checked the style guide and it actually shows an H2 styling per below. So can you please change it to H2 styling. Thank you rockstar!

<img width="1231" alt="screen shot 2017-11-14 at 11 27 37 am" src="https://user-images.githubusercontent.com/23316107/32791421-ff20d434-c92e-11e7-911f-76d4940bc426.png">

**Comment by Sjones352** [comment]
Current Page 

<img width="1237" alt="screen shot 2017-11-14 at 1 52 50 pm" src="https://user-images.githubusercontent.com/23080951/32798614-374187d2-c943-11e7-83c6-5daf5877ac98.png">

**Comment by Sjones352** [comment]
@Chingujo Not sure if I should change all the alert banners in eFolder 
<img width="940" alt="screen shot 2017-11-14 at 2 11 09 pm" src="https://user-images.githubusercontent.com/23080951/32799689-78f80392-c946-11e7-91dc-15ce271a80a1.png">
to H2 because this AC only states the Success Banner Alert

**Comment by Chingujo** [comment]
@Sjones352 

I would say go ahead and change the title styling on all error messages in demo to H2 =D Nice catch!

**Comment by kierachell** [comment]
**PASSED**
<img width="308" alt="screen shot 2017-11-23 at 10 42 44 am" src="https://user-images.githubusercontent.com/18075411/33180596-3c21d000-d03b-11e7-96c7-8e8b0556e519.png">
<img width="629" alt="screen shot 2017-11-23 at 10 42 51 am" src="https://user-images.githubusercontent.com/18075411/33180601-3eb23800-d03b-11e7-92d9-3fa8c9334b3c.png">
<img width="544" alt="screen shot 2017-11-23 at 10 43 39 am" src="https://user-images.githubusercontent.com/18075411/33180602-3edb0370-d03b-11e7-8913-6a24be390b2d.png">
<img width="476" alt="screen shot 2017-11-23 at 10 43 46 am" src="https://user-images.githubusercontent.com/18075411/33180603-3f02ca68-d03b-11e7-97f4-2fc2405571f2.png">
