### ISSUE TITLE
Fix Veteran Name in Demo

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#613]
I would like to see how a Veteran name render in eX.

Currently demo displays 'Test User' where the Veteran name would show. It is therefore not possible to discern the scenarios when the name appear as 'lastname, first name' e.g. on the downloaded eFolder. Please update the Veteran name throughout demo and use Joe Snuffy as the Veteran name.

**Comment by lakohl** [comment]
We are doing a demo for the HI RO on Monday.

**Comment by Sjones352** [comment]
@lakohl and @amprokop I can work on this one if no one has picked it up.

**Comment by Sjones352** [comment]
### Screenshot
currently
<img width="1187" alt="screen shot 2017-09-13 at 12 43 26 pm" src="https://user-images.githubusercontent.com/23080951/30390280-91356ba0-9883-11e7-972b-5a52dec09544.png">

**Comment by lakohl** [comment]
@Sjones352 looks great! We should also make sure the download folder is labeled with the Veteran name and last 4 in this format: 'Snuffy, Joe - 1234'

**Comment by Sjones352** [comment]
### Currently 
<img width="1242" alt="screen shot 2017-09-13 at 2 48 19 pm" src="https://user-images.githubusercontent.com/23080951/30395240-8132e812-9893-11e7-8032-717891e19df5.png">

**Comment by lakohl** [comment]
Thanks @Sjones352 ! Looks good to go.

**Comment by kierachell** [comment]
**PASSED**

Randomized too!??!?! NICE!
<img width="953" alt="screen shot 2017-09-13 at 8 12 25 pm" src="https://user-images.githubusercontent.com/18075411/30406467-ec91b74c-98bf-11e7-9e8c-6ba5cd95c933.png">
<img width="1164" alt="screen shot 2017-09-13 at 8 12 31 pm" src="https://user-images.githubusercontent.com/18075411/30406469-ec947284-98bf-11e7-8dee-1e3778638517.png">
<img width="842" alt="screen shot 2017-09-13 at 8 12 36 pm" src="https://user-images.githubusercontent.com/18075411/30406468-ec93bace-98bf-11e7-9587-4f954aabf85b.png">
