### ISSUE TITLE
Left Align table headers

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#622]
While working with users I noticed that the 'Source' and 'Receipt Date' table headers are not left aligned in IE.

AC
1. Verify that all table headers: Document Type, Source, and Receipt Date display as left aligned in all browsers.

<img width="573" alt="ie table headers" src="https://user-images.githubusercontent.com/4975959/30449172-9ff3398a-995d-11e7-84d2-364a628e51f5.png">

**Comment by Sjones352** [comment]
Currently both browsers look like this
**IE**
<img width="980" alt="screen shot 2017-09-17 at 7 49 29 pm" src="https://user-images.githubusercontent.com/23080951/30526067-c74bbb0c-9be1-11e7-840c-8cdaacbf9317.png">



**Firefox**
<img width="994" alt="screen shot 2017-09-17 at 7 24 57 pm" src="https://user-images.githubusercontent.com/23080951/30525910-6b43615a-9bde-11e7-9c3b-39ab3140a6d2.png">

**Comment by lakohl** [comment]
thanks @Sjones352 !

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod and UAT
Browsers: Chrome, FF, and IE

Steps to Validate: 
1. Access eFolder with an appropriate css_id
2. Enter in a file number for which an efolder will be downloaded
3. Select "Download eFolder" button
4. On the download page verify that the table headers are left aligned. 

Screenshots: 
(IE)
![ieefolder](https://user-images.githubusercontent.com/23038505/30548657-c316a2ac-9c60-11e7-9c48-5b807a89c08c.gif)
