### ISSUE TITLE
DownloadManifestJob should download as many docs as possible

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#625]
Currently the `DownloadManifestJob` does the following:

1) Try to get a list of documents from VBMS.
1) Try to get a list of documents from VVA.
1) If either of the above fail, abort.

Instead of failing, we should try both document sources at all times. We should also add two fields to the downloads table to mark when each of VVA documents and VBMS documents have been uploaded. On the UI path we should throw an error if either of these were not updated, but the API should work never fail. We should add these timestamps to the API. This way the API can serve whatever documents were available.

# AC
1. Verify the API returns documents from VVA even if VBMS fails (http error only).
1. Verify the API returns documents from VBMS even if VVA fails (http error only).
1. Verify the API returns the timestamp that the VVA and VBMS documents were retrieved.
1. Verify the UI only returns documents if both VVA and VBMS succeed.

**Comment by kierachell** [comment]
### Download manifest is working
<img width="532" alt="screen shot 2017-10-18 at 9 07 45 am" src="https://user-images.githubusercontent.com/18075411/31722643-a7358cd2-b3ea-11e7-8898-63507bb1fe8c.png">
<img width="571" alt="screen shot 2017-10-18 at 9 08 03 am" src="https://user-images.githubusercontent.com/18075411/31722644-a7912592-b3ea-11e7-889a-b46eb8703c83.png">

**Comment by kierachell** [comment]
#### What kind of errors are you expecting to handle?

- 504?
- unreachable?

### The following filenumber has VVA documents, should it still work?

<img width="681" alt="screen shot 2017-10-18 at 11 58 04 am" src="https://user-images.githubusercontent.com/18075411/31728948-ab48375a-b3fb-11e7-8e81-931a4437e4c9.png">

**Comment by sunil-sadasivan** [comment]
Hmm, thanks @kierachell.  Yeah I believe for now we're not handling connection timeouts gracefully, though we should.  

I believe this handles 5XXs from the service, though I could be wrong.  @kierachell, I'll find you tomorrow to discuss.

**Comment by kierachell** [comment]
Check alerts channel. Seems like some VVA errors are not caught.

**Comment by sunil-sadasivan** [comment]
@kierachell, I'm going to create a new ticket for better error handling of network specific errors.  I believe at the moment this will only handle cases where VBMS/VVA library throws a ClientError. 

(new ticket to handle service timeouts and network related issues)
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/645

I'll still look into the exceptions thrown

**Comment by kierachell** [comment]
**PASSED***

- Killed VBMS:
<img width="655" alt="screen shot 2017-10-19 at 7 58 46 pm" src="https://user-images.githubusercontent.com/18075411/31799430-069da74a-b508-11e7-9a7c-7ebcab4ff26a.png">


<img width="754" alt="screen shot 2017-10-19 at 7 59 36 pm" src="https://user-images.githubusercontent.com/18075411/31799440-0e579ea0-b508-11e7-8344-60d109367410.png">


- VBMS error for reference:
https://sentry.uat.ds.va.gov/sentry/efolder-uat/issues/477/
