### ISSUE TITLE
Migrate eFolder DB to split up Documents and Downloads

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#626]
# Context

When working on the eFolder Express integration we uncovered several architectural decisions that made future extensibility difficult. The main obstacle was that the Download and Document tables both contained data from VBMS/VVA as well as maintained values that were specific to each instance of a user interacting with the system. When a user searches for a veteran id we look for a download record from the last three days. If such a record doesn't exist, then a new one is created. Each download object has its own document objects associated with it. This means that downloads done outside of the three days are recreated in the DB, and downloads of the same veteran id but by different users are held in different records. This means that all of the data about the download and documents from VBMS are duplicated as we try to keep track of all the fields that are specific to an individual interaction with the app such as the time it took to download and whether or not those downloads were successful.

# Overview

We propose separating these two functions in the database. The Download table will contain exactly one entry for each veteran id. The Document table will contain exactly one entry for each document in the veteran's file. Then separate log tables will maintain the specific information about every user interaction with the system.

We think this structure has three main advantages:

1) StaleObjectErrors: eFolder has had a number of StaleObjectErrors in Sentry. This is partly due to having a complex architecture with several threads all trying to access DB entries at once. However, if we separate the actual data of the entry from the audit functions, we should be able to reduce these. It's the audit side of the tables that are usually in conflict, but if we aren't limited to one Download row and instead have several audit rows then we can create new audit entries for each user's download and avoid trying to write to them at the same time.

1) Store Less Data: We are needlessly duplicating data in our DB. It seems that where possible we should reduce the number of rows in our tables.

1) Better Caching: Now that we have implemented the API endpoints we've increased the instances when two people are going to be looking at the same Download around the same time. If attorney A and judge B want to both view the same case it would be ideal for them to be able to share the same download object so that fetching the data can avoid a call to VBMS.

1) Easier Reasoning About Data: With this model we can impose uniqueness constraints on our tables. No two downloads can have the same veteran id. No two documents can have the same document id. These constraints allow us to replace fuzzier `wheres` with concrete `finds`.

# Transitioning the Downloads Table

Transitioning the Downloads table will take several steps. Consider the current schema below:
```
  create_table "downloads", force: :cascade do |t|
    t.string   "request_id"
    t.string   "file_number"
    t.integer  "status",                          default: 0
    t.datetime "created_at",                                      null: false
    t.datetime "updated_at",                                      null: false
    t.integer  "lock_version"
    t.datetime "manifest_fetched_at"
    t.datetime "started_at"
    t.datetime "completed_at"
    t.string   "veteran_last_name"
    t.string   "veteran_first_name"
    t.string   "veteran_last_four_ssn"
    t.integer  "user_id"
    t.integer  "zipfile_size",          limit: 8
    t.boolean  "from_api",                        default: false
  end
```

Our final schema should look like this:
```
  create_table "downloads", force: :cascade do |t|
    ~t.string   "request_id"~ I CAN'T FIGURE OUT WHERE THIS IS USED, SEEMS TO BE NIL
    t.string   "file_number"
    t.integer  "status",                          default: 0
    t.datetime "created_at",                                      null: false
    t.datetime "updated_at",                                      null: false
    t.integer  "lock_version"
    t.string   "veteran_last_name"
    t.string   "veteran_first_name"
    t.string   "veteran_last_four_ssn"
  end
```

```
  create_table "download_logs", force: :cascade do |t|
    t.integer  "download_id"
    t.datetime "manifest_fetched_at"
    t.datetime "started_at"
    t.datetime "completed_at"
    t.integer  "user_id"
    t.integer  "zipfile_size",          limit: 8
    t.boolean  "from_api",                        default: false
    t.datetime "created_at",                                      null: false
  end
```

1) Create a copy of the current DB in case the migration goes badly
2) Create the download_logs table as seen above
3) Start writing to the download_logs table while still leaving the code that writes the logging fields to the original download table.
4) Write a migration that moves each Download objects logging fields to new rows in the download_logs DB.
5) Remove the code that is writing to the log fields of the download table.
6) Remove the log fields of the download table.

Open questions: 
1) What is request_id?
1) Where should lock_version go? What does it do?
# Transitioning the Documents Table 

We can use a similar process to migrate the Documents table. The current schema is:

```
  create_table "documents", force: :cascade do |t|
    t.integer  "download_id"
    t.integer  "download_status",  default: 0
    t.string   "document_id"
    t.string   "vbms_filename"
    t.string   "filepath"
    t.string   "source"
    t.string   "mime_type"
    t.datetime "received_at"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.datetime "started_at"
    t.datetime "completed_at"
    t.integer  "lock_version"
    t.string   "type_description"
    t.string   "type_id"
    t.text     "error_message"
    t.string   "downloaded_from",  default: "VBMS"
    t.string   "jro"
    t.string   "ssn"
    t.integer  "size"
  end
```

We would instead like two tables:

```
  create_table "documents", force: :cascade do |t|
    t.integer  "download_id"
    t.string   "external_document_id" <- THIS SHOULD BE RENAMED TO EXTERNAL_DOCUMENT_ID
    t.string   "vbms_filename"
    t.string   "source"
    t.string   "mime_type"
    t.datetime "received_at"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.integer  "lock_version"
    t.string   "type_description"
    t.string   "type_id"
    t.string   "downloaded_from",  default: "VBMS"
    t.string   "jro"
    t.string   "ssn"
    t.integer  "size"
  end
```

```
  create_table "document_logs", force: :cascade do |t|
    t.integer  "document_id"
    t.integer  "download_status",  default: 0
    t.string   "filepath"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.datetime "started_at"
    t.datetime "completed_at"
    t.text     "error_message"
  end
```

1) Create a copy of the current DB in case the migration goes badly
2) Create the document_logs table as seen above
3) Start writing to the document_logs table while still leaving the code that writes the logging fields to the original document table.
4) Write a migration that moves each Document objects logging fields to new rows in the document_logs DB.
5) Remove the code that is writing to the log fields of the documents table.
6) Remove the log fields of the document table.

Open questions:
1) Should we have some way to mark if the document came from S3?
1) What is `lock_version`?

# Finishing touches
We should run one final migration to enable a uniqueness constraint.

1) Run a migration that iterates through the Download table from most recent to oldest record. For each record delete all other records with the same file_number, and delete all their corresponding document objects.
1) Turn on the uniqueness constraint such that each veteran id has at most one Download object and each external_document_id has at most one document object.
1) Add code to catch the uniqueness constraint violation error if two threads try to create a download object for the same download at the same time. We can rescue this case by letting the first thread do all the work.

**Comment by nickheiner-usds** [comment]
It would be easier to comment on this if it were a PR.

```rb
  create_table "download_logs", force: :cascade do |t|
    t.integer  "download_id"
    t.datetime "manifest_fetched_at"
    t.datetime "started_at"
    t.datetime "completed_at"
    t.integer  "user_id"
    t.integer  "zipfile_size",          limit: 8
    t.boolean  "from_api",                        default: false
    t.datetime "created_at",                                      null: false
  end
```

If there's only ever one downloads object, then why do we need `completed_at`, `started_at`, etc to be on the logs table? If there's one downloads object, then is the only thing that's actual varying on a per-user basis the user id itself?

Are you also suggesting getting rid of the notion of invalidating downloads after three days?
