### ISSUE TITLE
(DownloadManifestJob) When a service fails to fetch, only retry that specific service

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow-efolder#632]
Continuing on #625, #630 allows us to handle gracefully downloading from multiple services.  

However if one service fails, we will retry both services.  Ideally we should only retry the one that fails.  Implement a way for us to fetch only one service at a time, gracefully handle the error, and on retry, only fetch the service that fails. 

**AC**
When a service fails, the next time the file api is called for that object, ensure only that failed service is retried.

**Comment by aroltsch** [comment]
@sunil-sadasivan is this done?

**Comment by aroltsch** [comment]
It is done.
