### ISSUE TITLE
HTTPI::SSLErrorSidekiq

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow-efolder#633]
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/436/
```
    result ||= MetricsService.record("VVA: fetch document content for: #{document.document_id}",
                                     service: :vva,
                                     name: "document_content.get_by_document_id") do
      @vva_client.document_content.get_by_document_id(
        document_id: document.document_id,
        source: document.source,
        format: document.preferred_extension,
```
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/484/
```
    documents ||= MetricsService.record("VVA: get document list for: #{download.file_number}",
                                        service: :vva,
                                        name: "document_list.get_by_claim_number") do
      @vva_client.document_list.get_by_claim_number(download.file_number)
    end
    Rails.logger.info("VVA Document list length: #{documents.length}")
    documents
```

**Comment by amprokop** [comment]
@mmlumba — reassigning to @mdbenjam since whiskey's gonna handle efolder

**Comment by mdbenjam** [comment]
Seems linked to https://github.com/department-of-veterans-affairs/connect_vva/issues/13

**Comment by aroltsch** [comment]
It is not linked to department-of-veterans-affairs/connect_vva#13

**Comment by amprokop** [comment]
It might be a different OpenSSL version error, no?

**Comment by aroltsch** [comment]
@kierachell  If we see SSL errors again, that means it is not fixed. In the meantime I think we can close it.

**Comment by kierachell** [comment]
Yeah, too much work trying to force these errors in lower envs.

TEST IT IN PROD
