### ISSUE TITLE
OGC Issue

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#636]
Speaking to David and Merri on 09/12 and I learned that all notes, bookmarks, and annotations in VBMS are part of the (CAVC) court record. Is this true for regular appeals? 
(Apparently no.)

My impression was that comments in Reader are off-the-record. Would like to understand this area better.

David an Merri need to provide the bookmarks and annotations as part of the court record and their contractors are concerned that if they use eX they don't know which docs have these.
Their ask was to at least flag the documents that have notes and bookmarks in VBMS  in eX so that they ensure those are later copied and put included in the record.

**Comment by lakohl** [comment]
James brought this up to David Ames. 
James said 'the Board took a hardline position that these are absolutely not part of the record.  I don't know if GC is pushing back.  I'm trying to find out.'

**Comment by lakohl** [comment]
We should probably follow up on this again, as I'd like to get back to David and Merri

**Comment by mattwilcut** [comment]
As an attorney, my opinion is 1) if CAVC/OGC considers it part of the record, the fact the Board disagrees is one court case away from losing all import, and 2) I find CAVC/OGC's interpretation more reasonable regardless as VBMS currently contains annotations I would categorize as "substantive" that amount to findings/factual determinations that can be disagreed with and raised during those appeals.

I dont necessarily agree with #618's inclusion of Subject title and Bookmarking being in the same camp though.  I don't consider those substantive or evidence of a determination/finding - at least not nearly as clearly as, for example, an annotation on a set of military medical records that reads "no evidence of injury"

**Comment by paultag** [comment]
(keep in mind this is a public issue)

**Comment by mattwilcut** [comment]
@paultag You can invite me to pilot as a stakeholder and I'd be happy to provide my feedback through the established feedback process :)

**Comment by paultag** [comment]
Oh I'm not employed by the VA, just a bit caught offguard to see internal
chatter about VA's legal advice

**Comment by mattwilcut** [comment]
no complaints here :)
