### ISSUE TITLE
Turn on VVA for Reader users

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#638]
We need to start turning on VVA for Reader users. We also need to coordinate with VVA to make sure this will not be a problem.

**Comment by aroltsch** [comment]
@mdbenjam do you still need this issue?

**Comment by mdbenjam** [comment]
Yeah since we un-rolled it out earlier. Let's leave this open.

**Comment by alisan16** [comment]
VVA is turned on, though we are currently having issues. This ticket is no longer relevant. Closing.
