### ISSUE TITLE
Better handle Timeout and Network errors for VVA and VBMS services

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow-efolder#645]
We should be throwing a VBMS/VVA::ClientError when there is a network issue.  Right now the FileAPI we timeout and throw a 500.  

**AC:**
When a socket error occurs, the FileAPI should return a 200, with a vbms_error or vva_error = true

**Comment by aroltsch** [comment]
This PR should have fixed it https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/664
