### ISSUE TITLE
Create a timeout for downloads

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow-efolder#646]
When the user is waiting for the eFolder download to complete, the browser polls on the `/downloads/:id` page. If there's an error in the backend, this polling may continue forever. This is problematic:

1. The user may continue to wait, even if it's vanishingly unlikely that the download will ever complete.
1. If the polling process causes side effects, then those side effects can pile up as the user continues to poll. For instance, today we hit BGS during the poll. If a user keeps their browser on the polling page, then we could send a lot of traffic to BGS for no reason. For instance, the surge in traffic below is caused by a single user sitting on the polling page:

![image](https://user-images.githubusercontent.com/25331532/31795843-54ccbdd8-b4f5-11e7-9480-e4ab0e617ca1.png)

To fix this, we should decide on a timeout. In the browser, when the timeout is reached, we should show an error message. For analytics and debugging purposes, we should probably write to the `download` in the database and indicate that it has timed out. It would also be nice if we could feed this information into monitoring systems so we can keep track of how many timeouts are happening.

## Possibly Related
* #580 
* #408

**Comment by nickheiner-usds** [comment]
@lakohl can you provide a design for this? I'm happy to chat if you'd like more context.

**Comment by lakohl** [comment]
@NickHeiner is this related to one of the support tickets from today?
A little more context would help. What should the user do to accomplish their task (download this efolder)?
Also is this urgent? (I'm in mtgs/at a conference the next 3 days - so likely won't get to this until mid-next week). If it is might ask @Chingujo to help.

**Comment by nickheiner-usds** [comment]
> What should the user do to accomplish their task (download this efolder)?

Good question. In this case, we won't necessarily have a specific error. So the user should probably just reach out to support, and provide the download ID. (We could put that ID in the error message.) It would be better if we could just have monitoring and not need to ask the user to reach out to support, but our responsiveness to monitoring is not adequate right now to make this feasible.

> Also is this urgent? 

Not necessarily. @mdbenjam – when could we have this done by?

**Comment by lakohl** [comment]
@NickHeiner do you think this could be the same problem? https://github.com/department-of-veterans-affairs/appeals-support/issues/722#event-1302032368

**Comment by mdbenjam** [comment]
It is probably not the same issue.

I'd say we probably won't work on it until at least after the first week of reader rollout.

**Comment by lakohl** [comment]
OK. 
Trying to better understand what is the user seeing at this point, so I can understand how to message them. Are they stuck at the spinning caseflow logo? and they just let it spin endlessly?
If they Search for the Vet ID again, does the same thing happen over and over?

**Comment by Chingujo** [comment]
Based on Mark's post mortem #649 last night seems like this is triggered after a user searches for an invalid ID _a second time_, which hangs the UI and causes a poll once per second @lakohl. The first search shows a veteran not found error and a second search of the same ID shows an endless spinner?

Happy to assist here as needed and have the same questions as Lara with what error the users are exactly seeing. A screen shot would be super helpful =D. There could be a few UI patterns we could explore on the design side after such as a generic error with a retry button after the timeouts, a redirect to a page like the home screen with a banner error, or we could tell the user to submit a ticket based on above.

**Comment by mdbenjam** [comment]
So the goal with the timeout isn't to address this specific problem, but rather the generic endless spinner problem. If a user ever ends up in a state where the spinner spins endless, we need to surface some UI to them after some amount of time that the download has been canceled.

**Comment by Chingujo** [comment]
There is a UI ticket for this in #675 =D

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
