### ISSUE TITLE
Searching twice for a non-existent SSN causes downloads to hang

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow-efolder#647]
## Repro Steps
1. Search eFolder for a non-existent SSN 
1. See that it gives an error message saying that the SSN is not found
1. Search eFolder for the same SSN again
1. See that the "gathering files now" page hangs indefinitely

@mdbenjam has an explanation for why this occurs.

# AC
1. Verify that in the above flow, the page does not hang, but gives the correct error message saying that SSN is not found.

**Comment by kierachell** [comment]
**PASSED**

- Tried all kinds of wonky IDs... can't get it to hang no more

I can finally remove the logic to handle this from integration tests 👏 

<img width="666" alt="screen shot 2017-11-02 at 8 55 39 pm" src="https://user-images.githubusercontent.com/18075411/32357128-421affda-c010-11e7-84cd-983fa3411f7a.png">
<img width="538" alt="screen shot 2017-11-02 at 8 55 46 pm" src="https://user-images.githubusercontent.com/18075411/32357129-4229789e-c010-11e7-8a6f-c6cd05561e42.png">
<img width="639" alt="screen shot 2017-11-02 at 8 55 56 pm" src="https://user-images.githubusercontent.com/18075411/32357130-42364dbc-c010-11e7-8408-86c86f28c790.png">
