### ISSUE TITLE
[Post Mortem] 30k calls to BGS

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#649]
# Summary
On October 19, 2017 Alan and Artem noticed the following graph in the #appeals-system-graphs slack channel.
![image](https://user-images.githubusercontent.com/3885236/31800823-95b251de-b511-11e7-8ab6-580554b9da32.png)

This showed nearly 20k calls to BGS's `find_by_file_number` endpoint on October 19. Way more than we'd expect to see.

# Root causes
When a user searches eFolder Express for an invalid veteran id the user is told that the veteran id is invalid, but a download record is erroneously created. However, if the user then searches for the same invalid id again, the previously created download object will be loaded and the users browser will continuously poll the download's status. Since the download is not actually downloading anything, the UI will hang for ever. Each poll of an invalid veteran id causes a call to BGS. The browser polls about 1/second leading to thousands of requests until the user terminates the browser.

# Tracking down the root cause
We began the investigation by looking into the eFolder logs. By searching for BGS calls we saw the same download id (50822) being hit over and over again. Looking up that download in the DB we saw that it had no veteran information. This suggested that it was an invalid veteran id. Upon examining the logs more closely we saw that each call to the download endpoint was a json request. This led us to believe it was the frontend polling the backend that caused the BGS calls. Next we tried this veteran's id in production. The first search showed an error message saying the veteran didn't exist. But the second search started spinning endlessly. Now that we knew searching for a bad veteran id twice cause it to spin indefinitely, we were able to set up a reproduction of the bug locally and debug.

# Solution
See the PR [here](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/648). We changed the search model to validate the veteran id before saving the download object. This way a download object is never saved erroneously.

# Timeline (EST)
2017/10/19 12:06 am – Incident begins
2017/10/19 6:58 am – Incident ends
2017/10/19 2:00 pm – Alan notices the offending graph
2017/10/19 2:15 pm – Alan brings the offending graph to the attention of the Whiskey team
2017/10/19 3:10 pm – Nick and Mark start debugging
2017/10/19 6:00 pm – Root cause is determined
2017/10/19 6:30 pm – PR with fix is sent out

# What went well
- We responded in a timely manner once the incident was raised.
- We utilized logs very well to quickly track down the problem.
- New monitoring surfaced this bug.

# What didn't go well
- We realized Mark & Nick haven't logged into prod and were not able to.
- We didn't realize this was a problem until new monitoring brought it up. This has presumably been a bug for a long time.
- Logs and graphs are not always labeled with time zone, so it was confusing whether we were looking at UTC or local time. Some sources are in UTC, and others are in local time, so converting back and forth took extra mental resources.

**Comment by aroltsch** [comment]
We already implemented a solution so we can close it. 
connects #675
