### ISSUE TITLE
exclude /health-check from force_ssl config option

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#65]
Apparently [this](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/60/files#diff-1d98f0039bbc6df92adee882ed99d993R48) is the Rails 3 syntax for excluding a path from `force_ssl`

**Comment by orischwartz** [comment]
[Discussion](https://github.com/rails/rails/pull/5515#issuecomment-11864757) on why option was removed

**Comment by shanear** [comment]
boom:
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/ssl.rb#L40
