### ISSUE TITLE
Feature Flag | Enable Reader Pilot users on 10/23/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#653]
As Project Manager, I would like the following feature flag enabled on Monday, 10/23/2017 at 8 am (as early as possible) for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

**_Reader Pilot User IDs (79)_**
“VACOALHINM”, “VACOALLENN”, “BVATBERRYMAN”, “BVAMBLACK”, “BVACBOSELY”, “BVADBREDEHORS”, “BVAJBROCK”, “BVAMBRUCE”, “BVAJBURRO”, “VACOBUSHL2”, “BVADMCASULA”, “BVATCATINO”, “BVAPCHILDERS”, “BVAKCHURCH”, “VACOCOMNIG”, “BVALCONNOR”, “BVARCOSTELLO”, “VACOCRAWFJ2”, “BVACCYKOWSKI”, “BVATDOUGLAS”, “BVASECKERMA”, “VACOEDWARC”, “BVASFINN”, “BVAKFLETCHER”, “VACOFRANKM2”, “VACOGEORGEJ”, “BVAAGIBSON”, “BVAMHARRIGAN”, “BVASHENEKS”, “BVAMHERMAN”, “BVANHOLTZ”, “BVAKHUBERS”, “BVABISAACS”, “BVAAISHIZ”, “BVACBOYD”, “BVAADJAKSON”, “VACOJIMERD”, “VACOJOHNSS3”, “BVADJJONES”, “BVAMLKANE”, “VACOKASSC”, “BVARKESSEL”, “BVANKROES”, “BVALKYLE”, “BVAMLAVAN”, “BVAMMAC”, “BVATMATTA”, “VACOMETZNP”, “VACOMOOREB1”, “BVAVMOSHI”, “BVAJNICHOLS”, “BVANNORTHCUTT”, “BVAMNYE”, “BVAMPETERS”, “VACOPRATTV”, “VACOROBINN”, “BVAPRUBIN”, “BVACRYAN”, “VACOSAINDP”, “VACOSANDLJ”, “BVAASANTIAGO”, “BVADSEATON”, “VACOSHOWAM”, “VACOSIMSR”, “BVAESTRUENING”, “BVAMTAYLOR”, “BVARVELDENZ”, “BVADWARE”, “BVARWATKINS”, “BVADWIGHT”, “VACOWINKLT”, “BVALYANTZ”, “BVAMYUAN”, “BVALZOBRIST”, “VACOHUMPHD”, “VACOLEEM2”, “BVADHAVELKA”, “BVAAWEIS”, “VACOGONZAM6”

## Related Stories
IP | eFolder Express - VVA | - Reader Pilot Users [#1609](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1609)

**Comment by mdbenjam** [comment]
These users should be enabled.

**Comment by nikitarockz** [comment]
# Update
This feature was turned off after encountering issues.  However after fixing the issue, these users are now being enabled again.
