### ISSUE TITLE
Project Outline: MeFGA - Make eFolder Great Again

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#654]
This is a overview of the current state of eFolder Express. There are a large number of sentry errors and support issues that have been on the back burner. Here we try to catalog the most common ones, and provide some possible solutions to addressing them. Then we consider some possible refactors to put the application on a more solid footing:

# Errors
1) Stale Object: These probably require a pretty large refactor to deal with. See the proposed tech spec here: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/626
1) KeepAliveDisconneced: We don't have a good understanding of why this is happen. It appears that VBMS is rejecting our requests. https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/524/
1)

**Comment by aroltsch** [comment]
@mdbenjam do you still want to keep this open?

**Comment by mdbenjam** [comment]
This has been moved to appeals-pm: https://github.com/department-of-veterans-affairs/appeals-pm/pull/1655/files
