### ISSUE TITLE
Optimistic locking causes error to be thrown

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#656]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/?query=StaleObjectError

Sentry captures StaleObjectErrors from eFolder Express at a steady clip. These errors are caused by optimistic locking. If the same object is loaded in two different contexts, and it's saved in one context, then the other, then Rails will throw an error.

There are a number of lines of code where we observe this error:

```
app/jobs/download_manifest_job.rb in capture_error at line 36
app/jobs/download_manifest_job.rb in download_from_service at line 55
app/services/download_documents.rb in block in create_documents at line 58
app/services/download_documents.rb in block in create_documents at line 57
app/services/download_documents.rb in block (3 levels) in create_documents at line 54
app/services/download_documents.rb in block (3 levels) in create_documents at line 53
 app/controllers/downloads_controller.rb in start at line 22
```
## AC
- Errors should not be thrown by the eFolder API if a user makes multiple near-simultaneous requests to the eFolder API

**Comment by aroltsch** [comment]
@amprokop can I close this issue in favor of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/650

**Comment by amprokop** [comment]
@aroltsch — ya you can close it, this is complete
