### ISSUE TITLE
Feature Flag | Enable user (Murrell) on 10/27/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#660]
As Project Manager, I would like the following feature flag enabled on 10/27/2017 as early as possible for the following user so that all user can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

User Name | Email | User ID
-- | -- | ---
Murrell, Carol | Carol.Murrell@va.gov | "bvacmurrell"

## Related Stories
IP | EFolder Express - VVA | Request Feature Flag enabled (Murrell) [#1607](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1607)

**Comment by mdbenjam** [comment]
Turned on.
