### ISSUE TITLE
Investigate "Document ID does not exist" errors

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-efolder#661]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/529/events/11175/

Look at the text in the body of the error. Sentry has grouped it oddly.

## Questions
- How can this error happen? We fetch our documents according to the manifest received from VBMS.

## Steps
- Are there more instances of this error than the ones associated with the Sentry link above? @kierachell says it has been happening since the summer. Search AWS logs to get a sense of how often this is happening.
- Is this reproducible? Try to call VBMS using the document ids associated with these errors and see if they're really there.

## AC
When VBMS returns a "Document ID does not exist" error, we track the information in the database instead of throwing an error.

**Comment by nickheiner-usds** [comment]
Yeah, this is odd – why does Sentry contain both `WssVerification Exception` and `RecordNotFoundException`? It seems like the one you want me to look in to is the latter.

**Comment by nickheiner-usds** [comment]
I made requests manually, and found the following:

## VMBS says they exist
```
{40052652-0000-CE1C-89B5-070AECDA011E}
{7E0A03DF-02E5-4DAA-8A0C-25371929997F}
{F1C637DB-3904-40B4-AA9B-14E7AF845E5F}
```

## VBMS says they do not exist
```
ExternalApi::VBMSService.fetch_document_file(Document.new(document_id: '{BE836C2D-5162-4ACB-8E21-8CA1D3D9871A}'))
{4D83C104-913B-41E0-96E1-AED635FD3570}
```

The error message I got back was the same reported by Sentry. I retried this request, but it failed a second time as well.

I used the following line of code to test:

```rb
ExternalApi::VBMSService.fetch_document_file(Document.new(document_id: doc_id))
```

**Comment by amprokop** [comment]
Cool. So then potentially we need to handle this error on the application level — if we observe that some documents exist in the VBMS manifest but not in the eFolder, then maybe we should just catch it, log it, and move on, no?

**Comment by nickheiner-usds** [comment]
I made a `FindDocumentSeriesReference` call and confirmed that `{BE836C2D-5162-4ACB-8E21-8CA1D3D9871A}` does indeed exist in a manifest. 

> if we observe that some documents exist in the VBMS manifest but not in the eFolder, then maybe we should just catch it, log it, and move on, no?

I'm troubled by the fact that VBMS seems to intermittently decide that certain docs are not available.   I'm not sure what the best solution is here from a business perspective.

**Comment by kierachell** [comment]
1. `FindDocumentSeriesReference` endpoint is really unreliable (ask @aroltsch how painful it is) so we are not using it. It is possible that it corrupted a few Downloads due to inconsistencies ( document versioning, count discrepancies, etc)
  - There were 3-4 document lists that returned `nil` in place of Document ID (that's the error you're most likely seeing) (https://github.com/department-of-veterans-affairs/connect_vbms/issues/154)
  - Some document names are messed up (file extensions `.bin`, etc) and/or the content type `octet/stream` and we just end up not saving the document and not having the document id for it.

2. It is possible to change/move documents between the time when manifest is fetched and documents are downloaded.
  - List documents in eFolder
  - Rename/reupload documents in VBMS
  - Start retrieving documents in eFolder
  - Re-list documents from VBMS ( need to bust the cache in eFolder)
  - find discrepancies

**Comment by nickheiner-usds** [comment]
> `FindDocumentSeriesReference` endpoint is really unreliable (ask @aroltsch how painful it is) so we are not using it. It is possible that it corrupted a few Downloads due to inconsistencies ( document versioning, count discrepancies, etc)

Good point. I was mistaken above when I said I was using `FindDocumentSeriesReference`. I was actually using `ListDocuments`. So `FindDocumentSeriesReference` is not the problem.

> There were 3-4 document lists that returned `nil` in place of Document ID

That is not what I'm seeing in this case. The `document_id` field is populated, and requesting that `document_id` causes the "not found" error.

> Some document names are messed up (file extensions `.bin`, etc) and/or the content type `octet/stream` and we just end up not saving the document and not having the document id for it.

Interesting. But that's not what I'm seeing in this case. For one failed doc, I see:

```rb
@mime_type="application/pdf"
@filename="name-with-no-extension"
```

> It is possible to change/move documents between the time when manifest is fetched and documents are downloaded.

That's an interesting idea, and seems like it could happen generally, but I don't think it's what's happening here. In my testing, I made the list documents request, then immediately requested the `document_id`s from that request, and saw some of them fail.

**Comment by aroltsch** [comment]
It is possible that it is an issue on the VBMS side. if you find a similar case in UAT environment, we can create a Github issue with the VBMS dev team, they are usually very proactive.  https://github.com/department-of-veterans-affairs/dsva-vbms/

**Comment by nickheiner-usds** [comment]
I found the [same Sentry error in UAT](https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/284/), but I did not find the corresponding `Document` in the db. I will look through the logs for more info now.

**Comment by kierachell** [comment]
**PASSED**

Validated as part of https://github.com/department-of-veterans-affairs/caseflow/issues/3794
