### ISSUE TITLE
Downloading demo cases with arbitrary numbers fail

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#662]
A recent change broke downloading arbitrary numbered demo cases. So downloading only works for:
- DEMO1
- DEMO2
- DEMO3
- DEMO4
- DEMO5

But not for any other numbers.

# AC
- Verify you can download a demo case with an arbitrary file number.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Demo
Browser: Chrome

Steps to Validate: 
1. Access Efolder Demo
2. Enter some of the DEMO# for veteran IDs, referenced above. 
3. Verify that these samples bring up efolders containing documents 
4. Enter other DEMO# (123,234,8,9...) and verify that those numbers bring up efolders containing documents. 

Screenshots: 
![efolderdemo](https://user-images.githubusercontent.com/23038505/33026120-baae51ce-cddd-11e7-915e-6778fc76172d.gif)
