### ISSUE TITLE
VBMS docs don't save yet manifest says it's fetched

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#666]
On 10/30 a user reported that only VVA docs were present in a case. After examining the download we discovered that 430 docs were pulled from VBMS, the `vbms_manifest_fetched_at` was set, then the docs were added to the download in `create_documents` in `download_documents.rb`. The last line in `create_documents`: `@download.update_attributes!(manifest_fetched_at: Time.zone.now)` failed with a stale document error. Since creating the documents was in the same transaction block, we rolled all of it back. Yet since `vbms_manifest_fetched_at` was set earlier, it was still set, but the documents were not. Since we don't re-download the documents for 3 hours after the manifest was set, this user would not be able to just refresh the page to get the docs.

# AC
1. Verify that `vbms_manifest_fetched_at` and `vva_manifest_fetched_at` are only set if the corresponding document records have been created.

**Comment by sunil-sadasivan** [comment]
Oh shoot this is a good one Mark!  Great catch here. Let's chat about this tomorrow. 

Truthfully I believe `manifest_fetched_at` is only used for backwards compatibility so clients don't break, I think we can remove this if we feel comfortable clients don't use this any more.

**Comment by astewarttistatech** [comment]
@mdbenjam How would this be validated?

**Comment by mdbenjam** [comment]
We don't have a good way of reproducing what we think caused this. So we're going to close it on the assumption that the automated test is a sufficient test case.
