### ISSUE TITLE
EOFErrorSidekiq 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-efolder#669]
Sentry link: 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/535/

## AC
This error no longer appears in production.

**Comment by nickheiner-usds** [comment]
Here are the relevant log entries: https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-efolder_worker-prod/opt/efolder-express/src/log/efolder-express-worker.out;stream=i-0c1eb60192423571f-172.30.82.13;filter=07f018e5edf0917663b8b1d3.

**Comment by nickheiner-usds** [comment]
This was the only place I could find in our gems that includes the error message:

`gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb`:
```rb
    def readpartial(size, buf = nil)
      while @bufstr.size == 0
        if fill() == -1
          raise EOFError.new('end of file reached')
        end
      end
      str = @bufstr.slice!(0, size)
      debug(str)
      if buf
        buf.replace(str)
      else
        str
      end
    end
```

**Comment by nickheiner-usds** [comment]
> Artem Vovk [7 days ago] 
> It happens sometimes when their service just…drops…
>
>
> Mark Benjamin [7 days ago] 
> there's like nothing in the ticket
>
>
> Artem Vovk [7 days ago] 
> like: I'll be listing documents or something and then packets just stop
```

**Comment by nickheiner-usds** [comment]
One of the failed jobs has the following parameter:

```
"_aj_globalid": "gid://caseflow-efolder/Download/64041"
```

If I look for a download with ID `64041` in the prod database, I'll see that it was indeed downloaded at the time of the failure for that job.

**Comment by nickheiner-usds** [comment]
```
irb(main):009:0> Download.find(64041).errors?
  Download Load (0.6ms)  SELECT  "downloads".* FROM "downloads" WHERE "downloads"."id" = $1 LIMIT 1  [["id", 64041]]
[2017-11-16 15:47:03 -0500]   Download Load (0.6ms)  SELECT  "downloads".* FROM "downloads" WHERE "downloads"."id" = $1 LIMIT 1  [["id", 64041]]
   (1.0ms)  SELECT COUNT(*) FROM "documents" WHERE "documents"."download_id" = $1 AND "documents"."download_status" = $2  [["download_id", 64041], ["download_status", 2]]
[2017-11-16 15:47:03 -0500]    (1.0ms)  SELECT COUNT(*) FROM "documents" WHERE "documents"."download_id" = $1 AND "documents"."download_status" = $2  [["download_id", 64041], ["download_status", 2]]
=> false
```

This makes sense, because the job succeeded on the retry.

**Comment by nickheiner-usds** [comment]
I think that the problem here is just that we're throwing an error before giving up on the job. If we are going to retry anyway, we should not be throwing an error. We should only throw the error when we're out of retries.

**Comment by nickheiner-usds** [comment]
From the [sidekiq docs](https://github.com/mperham/sidekiq/wiki/Error-Handling):

> Let Sidekiq catch errors raised by your jobs. Sidekiq's built-in retry mechanism will catch those exceptions and retry the jobs regularly. [Sentry] will notify you of the exception. You fix the bug, deploy the fix and Sidekiq will retry your job successfully.

Looks like Sidekiq will indeed throw an error every time the job fails, not just when the job is moved to the Dead Job Queue.

**Comment by nickheiner-usds** [comment]
@aroltsch @mdbenjam an idea for a tech improvement that I'm not going to do in scope of this ticket: enable the `backtrace` option, so we actually get stack traces in Sentry and errors like this are more useful.

From the [sidekiq docs](https://github.com/mperham/sidekiq/wiki/Advanced-Options#workers) it looks like we can enable `backtrace` if we have a custom worker. It does not appear that we have one now in eFolder. Adding one and modifying existing calls to use it seems like it'd be a larger code change than I'd like to undertake now.

**Comment by nickheiner-usds** [comment]
I've been poking at this for a while, and am having trouble with my lack of ActiveJob / Sidekiq knowledge. Here's the current state.

**Problem:** We are firing too many Sentry alerts. We fire on every retry, not just when we run out of retries.
**Solution:** Only fire an alert when we run out of retries.

### Why the struggle is real
1. I don't know how to detect that a job has run out of retries. I tried hooking in to ActiveJob's callbacks like `around_perform` and `after_enqueue`, but couldn't find the info I was looking for. I was only able to get `deserialize` to be hit once, and trying to print out the object I wanted to inspect in `byebug` caused the Ruby VM to crash.
1. Sidekiq will allow us to specify custom workers, where we could use the `sidekiq_retries_exhaused` option, and do custom error handling. But Sidekiq's docs seem to suggest that basically nothing fancy works when you're using it with ActiveJob, including, unfortunately, recording backtraces so an error like this would have been easier to debug.
    * Using a custom worker would also require us to schedule the jobs differently, I think, at which point we'd no longer be using ActiveJob. It seems like we already decided to use ActiveJob.

Does anyone else have some context here that will be helpful? :smile:

**Comment by mdbenjam** [comment]
I think some of this is moot, we should just move this job over to the new SQS system right? Then see if this double alerting structure continues. In fact @sunil-sadasivan might just know.

**Comment by nickheiner-usds** [comment]
Yes, that is a good question. Are we ditching Sidekiq for SQS?

**Comment by nickheiner-usds** [comment]
Well, regardless of whether we are switching to SQS long term, I had an easy fix to silence the errors for the short term.

**Comment by sunil-sadasivan** [comment]
@NickHeiner @mdbenjam yeah for sure we should move this over to SQS!  I never got around to it as it wasn't as high priority as caseflow was yet.  Seeing some of the chatter in sidekiq keeping idle db connections, it might be good to prioritize this.  

@aroltsch and @mdbenjam, Perhaps I can work/show you how to replace sidekiq with sqs?

**Comment by aroltsch** [comment]
@sunil-sadasivan I can create a ticket to move eX Sidekiq jobs to SQS and we can take it on next sprint.

**Comment by aroltsch** [comment]
Thanks @nickheiner-usds for your investigative work on this prod alert!

**Comment by aroltsch** [comment]
Feel free to close the ticket @NickHeiner
