### ISSUE TITLE
VVA| Documents with no content hang download retrieval

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#679]
# Description
When downloading certain VVA documents,
it seems like some documents might not have content,
which then forced the whole download job to stall,
and there's no retry or skip button.

The only workaround is delete the download

## Reproduction Steps

**Scenario 1 -**

1. Go to efolder and start download no 56410 (doc id: {BB3CD3FD-A4A3-42FD-87DE-CF0227BCA40B})
1. Find it stall when downloading documents
1. Find a lack of retry/skip button

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:
```
NoMethodError: undefined method `unpack' for nil:NilClass
  from base64.rb:59:in `decode64'
  from vva/services/document_content.rb:21:in `get_by_document_id'
  from app/services/external_api/vva_service.rb:21:in `block in fetch_document_file'
  from app/services/metrics_service.rb:12:in `block in record'
  from benchmark.rb:293:in `measure'
  from app/services/metrics_service.rb:11:in `record'
```

- https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/eeb673e915e6d528aadfd3e02157b5490ef7ff0d/vendor/gems/connect_vbms/src/vbms/responses/document_with_content.rb#L11

- https://github.com/department-of-veterans-affairs/connect_vva/blob/bb345136dd98b1d4008c183efc97c4227785bc88/lib/vva/services/document_content.rb#L9

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/584/

## Screenshots
**_Scenario 1 - [Dat Timer Is fake news]_**
<img width="817" alt="screen shot 2017-11-05 at 2 19 06 pm" src="https://user-images.githubusercontent.com/18075411/32418251-4e4f7b48-c234-11e7-8059-b32613d96aec.png">

QA Notes: Need to validate with an actual document that has `nil` content not just `blank`.

**Comment by amprokop** [comment]
holla @kierachell — efolder is in whiskeyland now. @aroltsch or @mdbenjam might take a look at this

**Comment by aroltsch** [comment]
yeah, I can look into it

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access eFolder
2. Access VBMS 
3. In VBMS, upload a blank PDF
4. Navigate back to eFolder and find the blank PDF in the veteran's file. 
5. Retrieve eFolder, verify that there are no hang ups because of the blank pdf. 

Screenshots:
![loadingefolder](https://user-images.githubusercontent.com/23038505/32732238-f11d886c-c859-11e7-8e55-e6c4d4787a71.gif)

**Comment by kierachell** [comment]
Need to validate with an actual document that has `nil` content.

**Comment by astewarttistatech** [comment]
@kierachell Copying that and putting it in the ACs

**Comment by kierachell** [comment]
**PASSED**
<img width="543" alt="screen shot 2017-11-14 at 2 39 59 pm" src="https://user-images.githubusercontent.com/18075411/32800962-beba65de-c949-11e7-9cb4-edc43c4b81aa.png">
