### ISSUE TITLE
Feature Flag | Enable FOIA users on 11/6/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#682]
As Project Manager, I would like the following feature flag enabled on Monday, 11/6/2017 at as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

**_New Users:  14_**
"VBARMCBLOUGR", "RCDBBOOK", "VBARMCBRIGHR", "VBARMCBROWNL", "DIRMBUTL", "RCDKFLOY2", "VBARMCGOFFC", "VBARMCHATCHD", "VBARMCJONESD", "CSDMMASO", "VBARMCMORGAT", "VBARMCRODAWR", "VBARMCSMITHD", "VBARMCWOLKR"

## Related Stories
**_PM Issues_**
IP | eFolder Express - VVA | Request Feature Flag enabled [#1654]( https://github.com/department-of-veterans-affairs/appeals-pm/issues/1654)

**Comment by aroltsch** [comment]
Done 
```
FeatureToggle.details_for(:vva_service)
=> {:users=>["VBARMCBLOUGR", "RCDBBOOK", "VBARMCBRIGHR", "VBARMCBROWNL", "DIRMBUTL", "RCDKFLOY2", "VBARMCGOFFC", "VBARMCHATCHD", "VBARMCJONESD", "CSDMMASO", "VBARMCMORGAT", "VBARMCRODAWR", "VBARMCSMITHD", "VBARMCWOLKR"]}
```

**Comment by nikitarockz** [comment]
## Closing
All tasks have been completed.
