### ISSUE TITLE
Alerts for user access

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#687]
### Context 
Currently, there is no alert in place when new users are added and gain access to eFolder Express. One recent example is that we did not know FOIA and Privacy got new members of the team until they sent a request to get VVA functionality. 

Keeping in mind that eFolder Express is unique because a bunch of users got access years ago. So now we are retroactively doing user management and discovering people who did not get or need VVA  access who previously had access. Such as the FOIA group***** edited for more clarity. 

Right now we can manually pull new users to eFolder Express but there is no automated alert when users receive new access. 

### Concern

- If there is a sudden large influx of users that are added without us knowing, it can affect the rollout of other Caseflow Products 
- eFolder Express adds a lot of load to VBMS and want to avoid sudden, unprecedented spike in users 
- Complicates user management  

### Next steps

@aroltsch @mdbenjam mentioned that this would be best as a broader team discussion as it could be useful to other Caseflow products. Please feel free to add/edit this issue and include anyone that would be important =D. Placing in this repo per request.

**Comment by mdbenjam** [comment]
This might be worth having a post standup discussion. I feel like we've discussed similar things before about access control, and we've talked about maybe doing some sort of user monitoring, but I think a broad team discussion could be used here. @aroltsch thoughts?

**Comment by Chingujo** [comment]
Also adding @nikitarockz as our roll out guru who probably know can give the most amount of context about how users currently get access

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
