### ISSUE TITLE
API returns VVA timestamp even when documents are not retrieved

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#690]
If the VVA feature toggle is off, the API still returns a value for manifest_vva_fetched_at. We should only return a value for this field when we've retrieved documents from VVA.

References: https://github.com/department-of-veterans-affairs/appeals-support/issues/818

# AC
1) Verify when the VVA feature toggle is off, the files API returns nil for manifest_vva_fetched_at

**Comment by kierachell** [comment]
eFolder is broke af currently

**Comment by kierachell** [comment]
**PASSED**

- no VVA:
<img width="646" alt="screen shot 2017-11-17 at 8 59 53 am" src="https://user-images.githubusercontent.com/18075411/32950928-1d8a7b0c-cb76-11e7-9dd6-94873d5baa88.png">


- yes VVA:
<img width="799" alt="screen shot 2017-11-17 at 9 02 22 am" src="https://user-images.githubusercontent.com/18075411/32950936-227c7700-cb76-11e7-9cc1-1e33a8902638.png">
