### ISSUE TITLE
Undefined method `at_xpath' for nil:NilClass Did you mean

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#699]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/578/

Notes: it seems as it happens when the response is nil in connect_vbms when downloading an individual file.

**Comment by kierachell** [comment]
### Debugging

- Download id: 62541
- 277 documents from VBMS
- Fetch by ID succeeds, no hiccups
- Will try saving locally: no errors
- Reran SaveFilesToS3Job: no errors
- Not sure wtf is going on

**Comment by aroltsch** [comment]
1. Same result as @kierachell for download id 62541
2. Looking into download id 58785:

**Comment by aroltsch** [comment]
Here is the fix that I think will work: https://github.com/department-of-veterans-affairs/connect_vbms/pull/164.  I don't think we can test it. We will re-open the ticket we see a Sentry alert again.

**Comment by aroltsch** [comment]
This bug is for eDocument old api. We are hoping we will turn on the new API this month so I am going to mute this bug for 3 weeks and close it.
