### ISSUE TITLE
[v2] Connect API RecordsController to the v2 data model

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#700]
# AC:
1. Create a new file called `controllers/api/v2/records_controller.rb`
2. Connect API::V2::DocumentsController to the new data model: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/docs/v2/database_structure.md
3. Ensure the new API endpoint works the same as `/api/v1/documents`

# Steps
Curl the API with curl "http://localhost:3000/api/v2/records/:id" -H "Authorization: Token token=token" -H "css_id: CF_Q_283" -H "station_id: 283"

**Comment by kierachell** [comment]
**PASSED**

<img width="591" alt="screen shot 2017-12-13 at 8 22 41 am" src="https://user-images.githubusercontent.com/18075411/33941076-5226aca0-dfdf-11e7-880f-9a6c35e0459a.png">
<img width="605" alt="screen shot 2017-12-13 at 8 24 42 am" src="https://user-images.githubusercontent.com/18075411/33941077-5255ef24-dfdf-11e7-8e65-09c111324bc8.png">
<img width="678" alt="screen shot 2017-12-13 at 8 24 47 am" src="https://user-images.githubusercontent.com/18075411/33941078-528f5656-dfdf-11e7-839c-7a89e0073094.png">
<img width="634" alt="screen shot 2017-12-13 at 8 24 54 am" src="https://user-images.githubusercontent.com/18075411/33941079-530a0374-dfdf-11e7-8f05-c36b273afa8f.png">
<img width="930" alt="screen shot 2017-12-13 at 8 26 05 am" src="https://user-images.githubusercontent.com/18075411/33941080-53549a06-dfdf-11e7-9750-03fbc81d00b4.png">
