### ISSUE TITLE
[v2] Connect API ManifestsController to the v2 data model

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#701]
tech notes: 
1. Create a new file called `controllers/api/v2/manifests_controller.rb`
2. Connect API::V2::ManifestsController to the new data model: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/docs/v2/database_structure.md

# AC:
Ensure the new API endpoint `api/v2/manifests` works the same as `/api/v1/files`

# Steps to Validate:
1.
```Curl the API with curl "http://localhost:3000/api/v2/manifests" -H "Authorization: Token token=token" -H "css_id: CF_Q_283" -H "station_id: 283" -H "file_number: 1234"```
2. Ensure statuses are correct
3. Ensure the record list is accurate

**Comment by kierachell** [comment]
### you mean `file-number` header, not `veteran-id`
### Why does this 500 result in a `forbidden record` response?
```
SOAP response (status 500)                       dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-08adbc13a11592d98-172.30.66.34 D, [2017-12-03T17:20:03.191427 #2902] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope
 xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuMAAA</work:WorkContext></S:Header><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>findFlash
es: Invalid Input</faultstring><detail><ns2:ShareException xmlns:ns2="http://services.share.benefits.vba.va.gov/"><message>findFlashes: FileNumber is empty</message></ns2:ShareException></detail></S:Fault></S:Body></S:Envelope>
dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-08adbc13a11592d98-172.30.66.34 [efolder.cf.uat.ds.va.gov] [3c1fced2-3a2e-4683-ae9f-097176c24cb8] [172.30.66.34] [2017-12-03 17:20:03 -0500] FINISHED BGS: can_access? (find_flashes): :   0.000000   0.000000   0.000000 (  0.763375)
```

- because you're doing a BGS lookup even when no header is sent

### Works for VVA too, nice:
<img width="494" alt="screen shot 2017-12-03 at 5 24 01 pm" src="https://user-images.githubusercontent.com/18075411/33530516-d3d02210-d84e-11e7-8984-0f1110690e49.png">

<img width="549" alt="screen shot 2017-12-03 at 5 24 36 pm" src="https://user-images.githubusercontent.com/18075411/33530565-58204356-d84f-11e7-801e-322aa73d8da6.png">

**Comment by kierachell** [comment]
### What kind of SSN is considered valid?:

- BGS tells you:
```
<faultstring>findFlashes: Invalid Input</faultstring><detail>
<message>findFlashes: FileNumber is invalid, must be 8 or 9 digits</message><
```
<img width="553" alt="screen shot 2017-12-05 at 7 37 23 pm" src="https://user-images.githubusercontent.com/18075411/33638354-becf0b3c-d9f3-11e7-9224-155a16931a5a.png">

- or non-numeric:
```
<message>findFlashes: FileNumber is invalid, must be numeric</message>
```

- or empty:
```
<message>findFlashes: FileNumber is empty</message>
```

- and it will tell you if the record is _actually_ sensitive:
```
<faultstring>This is a Sensitive Record and you do not have high enough access to update it</faultstring>
```

**Comment by astewarttistatech** [comment]
Hey @aroltsch we do not test locally so is this ticket able to be passed in one of the validation environments (preferably preprod)?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT \ Postman

Screenshots:
