### ISSUE TITLE
Feature Flag | Enable OGC users on 11/15/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#706]
As Project Manager, I would like the following feature flag enabled on 11/15/2017 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

**_New Users:  6_**
“VacoFlynnM”, “VACOChhadD”, “VACORatnaU”, “VACOSuthaV”, “VACOJaniA”, “VACOPandyJ”

## Related Stories
**_PM Issues_**
IP | eFolder Express - VVA | Request Feature Flag enabled (OGC) [#1673]( https://github.com/department-of-veterans-affairs/appeals-pm/issues/1673)

**Comment by aroltsch** [comment]
"VacoFlynnM", "VACOChhadD", "VACORatnaU", "VACOSuthaV", "VACOJaniA", "VACOPandyJ"
