### ISSUE TITLE
Average Database Connections Greater Than Threshold for DBInstanceIdentifier

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow-efolder#711]
Alarm:  90% of the value for our instance size as the threshold

Reason: Threshold Crossed: 1 datapoint [200.2 (16/11/17 17:35:00)] was greater than the threshold (200.0).

Link to issue: https://dsva-appeals.pagerduty.com/incidents/PLSY443

<img width="942" alt="screen shot 2017-11-16 at 12 51 08 pm" src="https://user-images.githubusercontent.com/23038505/32907106-01157af2-cacd-11e7-8fd0-352b9ec2af6b.png">
<img width="607" alt="screen shot 2017-11-16 at 12 51 52 pm" src="https://user-images.githubusercontent.com/23038505/32907222-4db815ea-cacd-11e7-8659-cf91fe5241c6.png">

**Comment by kierachell** [comment]
#### When you're suddenly a DBA

- Look at cloudwatch
<img width="1140" alt="screen shot 2017-11-16 at 8 02 28 pm" src="https://user-images.githubusercontent.com/18075411/32924170-55694656-cb09-11e7-83d1-77d0da84553e.png">
<img width="895" alt="screen shot 2017-11-16 at 8 02 33 pm" src="https://user-images.githubusercontent.com/18075411/32924171-558211e0-cb09-11e7-9d38-948de902cf57.png">
- Well, that's a lot certainly. What changed?

Ok so we scaled up:
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/aws-config.yml#L119

- But we scaled up 16 days ago
<img width="952" alt="screen shot 2017-11-16 at 8 05 36 pm" src="https://user-images.githubusercontent.com/18075411/32924222-8dd3953c-cb09-11e7-88bb-1e3c2b09fe8b.png">

- Let's look at other metrics:
<img width="891" alt="screen shot 2017-11-16 at 8 03 50 pm" src="https://user-images.githubusercontent.com/18075411/32924172-5590c9d8-cb09-11e7-8c5a-65ead56f0a86.png">
<img width="808" alt="screen shot 2017-11-16 at 8 06 42 pm" src="https://user-images.githubusercontent.com/18075411/32924257-be508c10-cb09-11e7-9718-bd35438e287d.png">
<img width="603" alt="screen shot 2017-11-16 at 8 06 55 pm" src="https://user-images.githubusercontent.com/18075411/32924259-be6645b4-cb09-11e7-94dc-23a6465ef476.png">


- These spikes don't correlated, but they're also not healthy. What in the world are we doing with the DB at 44mb/second??????


### Anyway, keep on going:
Get into the database:
```
 select *
efolder_express-> from pg_stat_activity
efolder_express-> where datname = 'efolder_express'
efolder_express-> ;
```

- Get 209 idle connections back. What the why?
```
select max_conn,used,res_for_super,max_conn-used-res_for_super res_for_normal
efolder_express-> from
efolder_express->   (select count(*) used from pg_stat_activity) t1,
efolder_express->   (select setting::int res_for_super from pg_settings where name=$$superuser_reserved_connections$$) t2,
efolder_express->   (select setting::int max_conn from pg_settings where name=$$max_connections$$) t3
efolder_express-> ;
 max_conn | used | res_for_super | res_for_normal
----------+------+---------------+----------------
      494 |  210 |             3 |            281
```

- Learn about connection pools: https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/roles/efolder-express/defaults/main.yml#L93

Well, max size is 25 times 7 = ohhh...

- Still, why are we hitting the max?
- Right, those connections we got from `pg_stat_activity` are all Jobs:

```
SELECT "documents".* FROM "documents" WHERE "documents"."do
wnload_id" = $1 AND "documents"."download_status" = $2  ORDER BY "documents"."received_at" DESC, "documents"."id" ASC
 16389 | efolder_express | 26718 |    16386 | efolder_express | /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/bin/puma | 172.30.82.254 |                 |       55714 | 2017-11-16 09:01:29.958412+00 |
                               | 2017-11-17 00:39:33.388143+00 | 2017-11-17 00:39:33.388168+00 | f       | idle   |             |              | SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMI
T 1
 16389 | efolder_express | 26719 |    16386 | efolder_express | /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/bin/puma | 172.30.86.40
```

- Why is that shit hanging around? Your fancy indexes won't drop our connections.

### POWER OF GOOGLE

- https://stackoverflow.com/questions/28628822/why-does-sidekiq-not-close-old-connections

Maybe that'll fix it?
