### ISSUE TITLE
[FE] eFolder Express Document NOT RETRIEVED Error Messaging 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#712]
### Story
As a user, I want to clearly know how to retrieve my error documents and clearly know what my next steps are. 

### Acceptance Criteria

1. Verify that the title of the alert message reads "Some files could not be retrieved" 
1. Verify that the body of the error message has the following copy: 

- Line 1: "Click on the 'Errors' tab to see which documents did not download. 

- Line 2: You can still download the completed documents by clicking the 'Download anyway' button below or go back to the home page by clicking the 'Search for another efolder button'.
3. Verify that there is a button called 'Search for another efolder' in secondary button blue styling
4. Verify that clicking the 'Search for another efolder button' takes you back to the home page

### Mocks
![05_errors](https://user-images.githubusercontent.com/23316107/32909640-0f27afe0-cad5-11e7-9f83-bed96c82dfc2.png)

**Comment by Chingujo** [comment]
@lakohl 

Issue to update the error message we have now for retrieval errors. Copy is updated based on feedback and our content meeting.

Also reflected is the change from gray button to the secondary blue with the changed text from 'Ttry again' to 'search for another eFolder".

**Comment by Chingujo** [comment]
With refactoring finishing up, we are ready to have a discussion on the future state of the eFolder Express UI. Will update related UI tickets after that conversation next week.

**Comment by lakohl** [comment]
Icebox or kill this as we are not updating eX at the moment?

**Comment by Chingujo** [comment]
closed thanks Lara!
