### ISSUE TITLE
eX development environment session issues

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#717]
Tech notes:
Caseflow and eX share a session so when logged into Caseflow and then trying to open eX you see the following message:

Error:
```
ActiveRecord::StatementInvalid (PG::NotNullViolation: ERROR:  null value in column "css_id" violates not-null constraint
DETAIL:  Failing row contains (1, null, 283, null, 2017-11-16 21:37:45.979134, 2017-11-16 21:37:45.979134, 0).
: INSERT INTO "users" ("station_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"):
  app/models/user.rb:46:in `from_session'
  app/controllers/base_controller.rb:22:in `current_user'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

Steps to Reproduce (locally):
1.  Login to Caseflow, default to the Fake User, stop rails s
2. Start rails s for eX, go to the browser localhost:3000 and see the error

AC:
Switching between Caseflow and eX in the browser works without any errors.

**Comment by kierachell** [comment]
**PASSED**

<img width="630" alt="screen shot 2017-12-13 at 8 10 28 am" src="https://user-images.githubusercontent.com/18075411/33940502-3586447c-dfdd-11e7-9106-0cd8841dcfad.png">
<img width="628" alt="screen shot 2017-12-13 at 8 10 42 am" src="https://user-images.githubusercontent.com/18075411/33940503-35b812d6-dfdd-11e7-8f49-0a3cbb7bc4e6.png">
