### ISSUE TITLE
API | Add source application to requests

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#723]
### Problem:

- When delegating external requests to VA backends, it is hard to tell where the request has originated. We need a way to track how certain requests are delegated.
Currently, it is hard to tell how hard Reader is hitting VBMS via eFolder.
I can tell how hard Reader is hitting VACOLS vs Dispatch:
<img width="463" alt="screen shot 2017-11-19 at 12 58 10 pm" src="https://user-images.githubusercontent.com/18075411/32993663-604dd9e8-cd29-11e7-8531-b0218e55114d.png">

But I cannot tell that about VBMS:
<img width="978" alt="screen shot 2017-11-19 at 12 54 02 pm" src="https://user-images.githubusercontent.com/18075411/32993627-bc41ce40-cd28-11e7-8a88-134b3f5fdd92.png">

### Request:
- add a host-app or some kind of origin header to the API: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/api/v1/application_controller.rb
- this way we can track request originator here: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/metrics_service.rb#L8
- this way we can track delegation of requests by other services as well.

#### Related:
- https://github.com/department-of-veterans-affairs/caseflow/issues/3692
- https://github.com/department-of-veterans-affairs/caseflow/issues/3921

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
