### ISSUE TITLE
Handle VBMS connection reset in ExternalApi::VBMSService.send_and_log_request()

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#727]
ExternalApi::VBMSService.send_and_log_request() occasionally throws an exception as the result of VBMS resetting the connection. We should be more resilient in this situation, I don't think we should really care about each individual connection reset. Maybe we could retry and return a more valuable error (or throw a better exception) if the connection is repeatedly reset and alert in that case. Consider catching and retrying these ECONNRESET errors in `DownloadManifestJob.perform()` and `Document.fetch_content!()`.

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/606/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/608/

> Errno::ECONNRESET - app/services/external_api/vbms_service.rb in block in send_and_log_request. 
> Connection reset by peer - SSL_connect

**Comment by lowellrex** [comment]
Similar issue here: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/621/

> HTTPI::SSLError
> SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read finished A
> app/services/external_api/vbms_service.rb in block in send_and_log_request

**Comment by lowellrex** [comment]
Similar issue here: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/640/

> HTTPClient::KeepAliveDisconnected
> HTTPClient::KeepAliveDisconnected: Connection reset by peer
> app/services/external_api/vbms_service.rb in block in send_and_log_request

**Comment by aroltsch** [comment]
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1034#issuecomment-348509357
