### ISSUE TITLE
Handle VBMS timeout error in ExternalApi::VBMSService.send_and_log_request()

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#728]
Similar to #727, I think we need to be more resilient to an external dependency's hiccups. I think we should retry on individual failures (on repeated failures display a banner or something?), aggregate failures across all sessions and alert (and possibly change the application's behaviour? Stop making requests to VBMS until it recovers?) only after we reach some threshold of failures. We cannot control the availability/responsiveness of this external dependency, so we should probably not trigger an error when we run across it just a few times.

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/632/

> HTTPClient::ReceiveTimeoutError
> execution expired
> app/services/external_api/vbms_service.rb in block in send_and_log_request

**Comment by lowellrex** [comment]
Same issue: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/634/

**Comment by aroltsch** [comment]
Timeouts should be re-retried by Envoy. 
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1034#issuecomment-348509357
We can re-open if we see it again.
