### ISSUE TITLE
Handle ExternalApi::VVAService timeout gracefully

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#729]
Request to VVA timed out in ExternalApi::VVAService.fetch_document_file(). We should probably attempt to reconnect, attempt the query again, gracefully handle any repeated failures, and only alert on this error if we encounter it across some threshold of users/attempts/time since VVA is an external dependency upon which we have no direct control.

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/627/

> Net::ReadTimeout
> app/services/external_api/vva_service.rb in block in fetch_document_file

**Comment by lowellrex** [comment]
Similar issue here: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/610

> Net::OpenTimeout
> execution expired
> app/services/external_api/vva_service.rb in block in fetch_document_file

Perhaps these errors should be caught by [connect_vva](https://github.com/department-of-veterans-affairs/connect_vva) and re-thrown as a some type of VVA::*Error?

**Comment by aroltsch** [comment]
Timeouts should be re-retried by Envoy. 
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1034#issuecomment-348509357
We can re-open if we see it again.
