### ISSUE TITLE
Handle ExternalApi::BGSService timeout gracefully

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#730]
`ExternalApi::BGSService.check_sensitivity()` timed out yesterday (probably due to the VPN hullabaloo). We should probably attempt to reconnect, attempt the query again, gracefully handle any repeated failures, and only alert on this error if we encounter it across some threshold of users/attempts/time since BGS is an external dependency upon which we have no direct control. 

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/625/

> HTTPClient::ReceiveTimeoutError
> execution expired
> app/services/external_api/bgs_service.rb in block in check_sensitivity

**Comment by lowellrex** [comment]
Related connection reset issue with BGS: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/641/

> Errno::ECONNRESET
> Connection reset by peer
> app/services/external_api/bgs_service.rb in block in check_sensitivity

**Comment by lowellrex** [comment]
Related connection timeout with BGS: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/642/

> HTTPClient::ConnectTimeoutError
> execution expired
> app/services/external_api/bgs_service.rb in block in check_sensitivity

**Comment by lowellrex** [comment]
Related connection timeout with BGS: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/62/

> HTTPClient::ConnectTimeoutError
> execution expired
> app/services/external_api/bgs_service.rb in block in check_sensitivity

**Comment by aroltsch** [comment]
Timeouts should be re-tried by Envoy. We can re-open if we se it again.
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1034#issuecomment-348509357

**Comment by kierachell** [comment]
Are you basically setting timeout to `Inf` client side?
