### ISSUE TITLE
CalculateStatsJob | The job causes 100s of User lookups per second

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#734]
# Description
When CalculateStatsJob runs. It's doing 200+ requests per second to the database to lookup users.
Does it need to run that often? We have a ton of users now so it's inefficient.

We got 1000 users now; the job runs every 2 minutes; there's 7 app servers... yeah

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder logs
1. Watch the job run
1. Get a an enormous logdump

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:

- After watching logs for about 15 seconds
```
cat eFolderWorker.out | grep 'User Load (1.1ms)' | wc -l
    7843
```

**_Engineering_**
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1022
#739

**Comment by aroltsch** [comment]
Stats will be deprecated as part of v2 rollout.
