### ISSUE TITLE
VBMS/VVA Service | Client object is kept in memory and not cleared by GC

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#735]
# Description
When changing configurations on the client:
https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/external_api/vbms_service.rb#L21

These configurations will persist on the servers unless all the server threads are rebuilt or the client objects are manually cleared.

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Start VBMS requests
1. Change configurations for the client (e.g. FeatureToggle, change env vars, etc) that would affect client's functionality: in this case I will demonstrate with: Forward Proxy use
1. Log the forward proxy requests in `va_services.log`
1. Use eFolder UI to make VBMS requests
1. Note that the proxy is not being used
1. Manually force a VBMS request from the console using the new settings
1. Note that the request goes through the proxy
```
dsva-appeals-efolder-prod/var/log/va_services.log i-02766126724e5b3d9-172.30.87.34 [2017-11-25T18:36:20.499Z] [prod_bgs] [e0577ce4-3124-484d-a03e-46ac7574a602] [152.131.36.161:443] Started GET "/ClaimantServiceBean/ClaimantWebService?WSDL" | Response: 200 - 603 ms
dsva-appeals-efolder-prod/var/log/va_services.log i-0a998d0fcbfccc10e-172.30.83.100 [2017-11-25T18:38:36.078Z] [prod_vbms] [1929186f-9436-48a4-a107-5931d49c947f] [152.131.36.162:443] Started POST "/vbmsp2-cms/streaming/eDocumentService-v4" | Response: 200 - 2449 ms
```
1. This indicates that all other servers/threads are holding on to old client objects and are not letting them go. Which explains these endlessly rising charts:
<img width="1391" alt="screen shot 2017-11-25 at 1 41 26 pm" src="https://user-images.githubusercontent.com/18075411/33233680-fca72cdc-d1e7-11e7-87a8-9aaa64c260e2.png">

1. Manually reboot the server
1. Note that VBMS service now uses proxy on that one server (check the `va_services` log)

### Why should we care?
- save money: less memory use -> we can keep the costs down by not `just scaling up`
- resolve the old AF issue: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/595
- allow for on-the-fly config change for eFolder
- if you won't fix it, I will.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:
```
FeatureToggle.features
=> [:vva_service, :reader_api, :vbms_forward_proxy, :bgs_forward_proxy]
```
- Logging the requests. Note the lack of VBMS requests
```
dsva-appeals-efolder-prod/var/log/va_services.log i-0a998d0fcbfccc10e-172.30.83.100 [2017-11-25T18:34:45.926Z] [prod_bgs] [9ea018e8-8428-449a-bec2-759269adf3a7] [152.131.36.161:443] Started GET "/ClaimantServiceBean/ClaimantWebService?WSDL" | Response: 200 - 657 ms
dsva-appeals-efolder-prod/var/log/va_services.log i-02766126724e5b3d9-172.30.87.34 [2017-11-25T18:35:27.893Z] [prod_bgs] [ff8757b9-453b-426a-bdc0-850b9f32765c] [152.131.36.161:443] Started GET "/ClaimantServiceBean/ClaimantWebService?WSDL" | Response: 200 - 708 ms
dsva-appeals-efolder-prod/var/log/va_services.log i-0ee30c5b986dca363-172.30.86.202 [2017-11-25T18:35:26.448Z] [prod_bgs] [56e3ac4f-6a0e-4c55-b5a9-7275ab4170d5] [152.131.36.161:443] Started GET "/ClaimantServiceBean/ClaimantWebService?WSDL" | Response: 200 - 709 ms
```

## Screenshots
**_Scenario 1 - [TITLE]_**

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
