### ISSUE TITLE
No implicit conversion of nil into String

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#736]
Sentry link: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/650/. It appears that `document.filepath` is nil.

**Comment by mdbenjam** [comment]
Can't wait for when we calculate this rather than save it in the DB!

**Comment by Chingujo** [comment]
Possibly fixed by refactoring making a comment for @aroltsch due to GH issues

**Comment by astewarttistatech** [comment]
@lowellrex @aroltsch how is this to be validated if necessary?

**Comment by lowellrex** [comment]
If a user can download an efolder from the UI, then this works.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Prod/Preprod

Smoke test
