### ISSUE TITLE
Sanitize incoming user data from CSS in single location

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#740]
This ticket exists to address the work that remains after doing the migrations in #569.

After chatting with @shanear on Wednesday, we determined that the tidiest way of sanitizing data we receive from CSS for use by our applications would be to move all of that logic into a single module. This module would allow us to be more resilient to changes made within CSS (for example, if we uppercase all CSS IDs at their point of entry into the Caseflow ecosystem then we do not care if the casing of CSS IDs change upstream), as well as allowing for parity across all Caseflow applications (for example, if we strip leading and trailing spaces from email addresses in one application and not in another it would be more difficult to associate a user in efolder with that same user in caseflow).

Currently, we authenticate users in SessionsController.create() via the information returned from CSS and Api::V1::ApplicationController.authenticate_or_authorize() when the API request contains the correct API key. SessionController creates a hash that represents the authenticated user and stores it in the session's user element which we can later use to create a User object through User.from_session() in BaseController.current_user() (or which the caseflow applications can use for their own authentication purposes). Api::V1::ApplicationController.authenticate_or_authorize() uses User.find_or_create_by() to instantiate a new User object.

I propose we create a new module to consolidate the handling of authenticated users in efolder, which I am calling AuthenticatedUser. This module could consolidate a lot of that logic as follows:

Existing | Proposed
---------|---------
User.from_css_auth_hash() | AuthenticatedUser.from_css_auth_hash(), AuthenticatedUser.serialize()
User.from_session() | AuthenticatedUser.deserialize(), User.from_authenticated_user()
Api::V1::ApplicationController.authenticate_or_authorize() | AuthenticatedUser.from_request_headers(), User.from_authenticated_user()

cc: @aroltsch 

## AC:
* Create module to handle sanitizing of data from CSS, serializing/deserializing that object for use by caseflow applications
* Verify that we only ever instantiate Users from CSS data (from_session, from_css_auth_hash) and replace it with the new module's way of instantiating
* Remove existing code that sanitizes data from CSS
* Update existing records in the database if they do not agree with the sanitized data format in the new module
* Ensure that changes to this module do not alter behaviour of downstream Caseflow applications

## Test plan:
* Make sure users can still log in to efolder UI
* Make sure Reader still works (made slight--non-breaking--changes to the authentication/authorization process for the efolder API)

**Comment by kierachell** [comment]
like Caseflow commons?

**Comment by lowellrex** [comment]
By "in single location" I mean not only a single location in the code, but also a single service. Since efolder provides authentication services for caseflow and is the single point of entry for CSS data into our system, I think it makes sense that the single service that sanitizes incoming CSS data is efolder. This design also has the additional benefit of making it simple to pull out the authentication component of efolder into a standalone service should we ever want to do that.

**Comment by lowellrex** [comment]
@kierachell this ticket contains a data migration similar to the one in #569, so we will need to test that the data is transformed properly like we did with that ticket (spun up RDS prod-clone, ran the migration and verified that the data looked as we expected).

**Comment by astewarttistatech** [comment]
@lowellrex The test plan for this is a smoke test on both Reader and eFolder, correct?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Run smoke test of eFolder and ensure that nothing is broken or a bug has been introduced because of this ticket.
2. Run smoke test of Reader and ensure that nothing is broken or a bug has been introduced because of this ticket.
