### ISSUE TITLE
API v1 | 500 that should be a 404 is treated like a 403 and interpreted to be a 502...lolwut

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-efolder#742]
# Description
When trying to list documents for an appeal that,
and the veteran is not found in BGS; or BGS might be down for the night.
eFolder throws a 403 error, even though it's technically a 404.
And then Reader interprets it as 502.

## Reproduction Steps

**Scenario 1 -**

1. Reader with eFolder API on
1. Kill BGS(iptables, tcpkill, whichever) or just find an SSN that doesn't exist in BGS
1. Open a case for a vet who
1. See `unable to load documents`
1. Watch JS console
1. See 502 error that is actually a 403 from eFolder
1. Go to eFolder logs
1. See that it's just a a `vet not found` error
1. So it should be a 404, but BGS returns 500...
1. Be very very confused

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:

```
<?xml version='1.0' encoding='UTF-8'?><S:Envelop
e xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuMAAA</work:WorkContext></S:Header><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>No Perso
n record found</faultstring><detail><ns2:ShareException xmlns:ns2="http://services.share.benefits.vba.va.gov/"><message>No Person record found</message></ns2:ShareException></detail></S:Fault></S:Body></S:Envelope>
```

- in JS
```
{"errors":[{"status":502,"title":"eFolder HTTP status code: 403 for appeal: #\u003cAppeal:0x00558035c80ef0\u003e.","detail":"eFolder HTTP status code: 403 for appeal: #\u003cAppeal:0x00558035c80ef0\u003e."}]}
```

## Screenshots
**_Scenario 1 - [JS]_**
<img width="1099" alt="screen shot 2017-11-28 at 5 54 59 pm" src="https://user-images.githubusercontent.com/18075411/33348851-e3530776-d465-11e7-8122-87f0c80078f7.png">

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
