### ISSUE TITLE
(WIP) Post-Mortem: 20% Efolder db connection attempts failed for ~15 seconds

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#743]
## Summary
269 requests to efolder backend (API and web app) returned 500 errors due to database connection attempt failures over a period of ~15 seconds beginning at 11:01:47 EST and ending at 11:02:01 EST

## Status
No longer experiencing elevated database connection error rate. Resolved naturally without external intervention.

## Timeline
* **11:01:47 AM** First of 269 ActiveRecord::ConnectionTimeoutError errors occurs
* **11:01 AM** Sentry posted to Whiskey team slack channel - "ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds..."
* **11:02:01 AM** Last of 269 ActiveRecord::ConnectionTimeoutError errors occurs
* **11:02 AM** Sentry posted to Whiskey team slack channel - "ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds..."
* **11:06 AM** Artem noted in a thread that the database had run out of connections
* **11:08 AM** PagerDuty posted to App Alerts slack channel triggered by "Sum HTTPCode_Backend_5XX GreaterThanOrEqualToThreshold 30.0 for LoadBalancerName dsva-appeals-efolder-prod" cloudwatch alert
* **11:11 AM** Lowell acknowledged this alert in PagerDuty, debugging began with Nick, Sunil, Mark, Anya, and Lowell in Hoth conference room
* **11:45 AM** Debugging stopped for lunch

## Root causes
Still to be determined. The short period (15 seconds) during which we saw these errors and the fact that over the two minutes when we encountered these errors we had a 20% total error rate suggests the database was unavailable to the rails servers for those 15 seconds. Do not yet know why the database would be unavailable or how to validate this theory (inspect db logs in AWS?), but will report back as I uncover more.

Text of the exception ([example sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/666/)):
> **ActiveRecord::ConnectionTimeoutError**
> could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)

During this time the number of production RDS database connections grew from ~100 to ~280. 
![rds_connection_count](https://user-images.githubusercontent.com/32683958/33396435-81cc7ee0-d516-11e7-8e9c-a8343bb6c755.png)

Error rates were uniform at ~20% of all requests during those two minutes across the 7 efolder hosts.
<img width="409" alt="error_rates" src="https://user-images.githubusercontent.com/32683958/33396444-88a84a82-d516-11e7-8c4a-d9a6c8df92cb.png">

## What went well?
* Readiness for multiple developers to engage with the alert when it happened

## What can be improved?
* Lowell did not realize he could not access AWS until the incident response was underway. Developers should ensure they have access to all vital applications and tools at all times.

**Comment by askldjd** [comment]
https://user-images.githubusercontent.com/32683958/33396983-32fef9d0-d518-11e7-973c-d9d5b23c002c.png

Are you looking at Caseflow PostGres connection instead of eX? We are not plotting eX DB connections in Grafana.

**Comment by lowellrex** [comment]
@askldjd Yup! Thanks for checking me on that. Good call

**Comment by kierachell** [comment]
eFolder DB connections are here: https://prometheus.ds.va.gov/grafana/dashboard/db/reader?orgId=1

**Comment by nickheiner-usds** [comment]
![image](https://user-images.githubusercontent.com/25331532/33400995-d70c4980-d525-11e7-8077-a60522f0ff64.png)

https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/how-we-work/prod-squad.md

@lowellrex please make post-mortems markdown files in appeals-pm repo. That makes them much easier to comment on and edit over time. Thanks!

**Comment by lowellrex** [comment]
Moved this post-mortem to https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1068
