### ISSUE TITLE
[Refactor] Remove VVA coach marks

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#781]

**Comment by aroltsch** [comment]
@Chingujo Phillip, let us know if it is something we can tackle this sprint.

**Comment by Chingujo** [comment]
Thanks @aroltsch 

I'm inclined to keep the coach marks due to the potential roll out to about 269 completely new users that is happening in the future (existing feedback was that it was helpful). 

When/if we remove the feature flag, then okay with getting rid of this.

**Comment by aroltsch** [comment]
v2 won't have VVA coach marks
