### ISSUE TITLE
Deploy message is sometimes wrong

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow-efolder#790]
[Example error in Slack](https://dsva.slack.com/archives/C7VNGMYUQ/p1513613436000289):

![image](https://user-images.githubusercontent.com/25331532/34116215-e8af35e8-e3e5-11e7-8a69-28bd2c3170dd.png)

In this case, the script mis-reported what was about to be deployed. It listed several changes that would be deployed, when in reality, it was only the most recent of those changes.

The error is in `Jenkinsfile` of this repo. Caseflow has the same logic, so it presumably has the same error.

**Comment by aroltsch** [comment]
@nickheiner-usds is it still an issue?

**Comment by nickheiner-usds** [comment]
If we haven't changed the Jenkinsfile since I made this ticket, then yes. :smile:

**Comment by mdbenjam** [comment]
This no longer seems to happen. Someone must have fixed it.
