### ISSUE TITLE
Feature Flag | Enable Group 7 – RMC users on 12/21/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#798]
As Project Manager, I would like the following feature flag enabled on Thurs., 12/21/2017 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

"VBARMCCOLEA", "VBARMCFICKEJ", "VBARMCJOHNSKE", "VBARMCMARLOK", "VBARMCPAGANA", "VBARMCPHILLC", "VBARMCSTUARL", "VBARMCSMITHT", "VBARMCOLIVEK", "VBARMCDUNNJ", "VBARMCJENNIL", "VBARMCWILLIK", "VBARMCWELCHC", "VBARMCMURPHD", "VBARMCDIERKC", "VBARMCDIERKC"

## Related Stories
**_PM Issues_**
IP | eFolder Express -  VVA | Request Feature Flag enabled - (RMC Group 7) [#1710](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1710)

**Comment by aroltsch** [comment]
Done!

```
{:users=>["VBARMCCOLEA", "VBARMCFICKEJ", "VBARMCJOHNSKE", "VBARMCMARLOK", "VBARMCPAGANA", "VBARMCPHILLC", "VBARMCSTUARL", "VBARMCSMITHT", "VBARMCOLIVEK", "VBARMCDUNNJ", "VBARMCJENNIL", "VBARMCWILLIK", "VBARMCWELCHC", "VBARMCMURPHD", "VBARMCDIERKC"]}```
