### ISSUE TITLE
[BE] Implement download zip file

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#811]
### AC
1. New v2 endpoint exists that will return a zip file with all the files 
2. If the file doesn't exist, returns nothing

Steps to validate:
1. Start retrieving manifest:
```POST <url>/api/v2/manifests/```
2. Check status of the manifest to ensure it is completed:
```GET <url>/api/v2/manifests/``` (keep calling this endpoint until status is success or failed)
3. Start downloading and packaging files into a zip file:
```POST <url>/api/v2/manifests/:manifest_id/files_downloads```
4. Check the status of the files download
  ```GET <url>/api/v2/manifests/:manifest_id/files_downloads```(keep calling this endpoint until status is finished or failed)
5. To download zip file:
```GET <url>/api/v2/manifests/:manifest_id/zip```

**Comment by Sjones352** [comment]
**FAILED**

<img width="975" alt="screen shot 2018-02-02 at 10 56 34 am" src="https://user-images.githubusercontent.com/23080951/35742356-2cbe9580-0808-11e8-868b-876683cdcf81.png">

**Comment by Sjones352** [comment]
**PASSED**
Validate Postman
1. Start retrieving manifest

<img width="977" alt="screen shot 2018-02-02 at 11 28 24 am" src="https://user-images.githubusercontent.com/23080951/35746916-7a5f538e-0816-11e8-9793-9dcfac11ac24.png">

2.Check status of the manifest to ensure it is completed
<img width="960" alt="screen shot 2018-02-02 at 11 50 27 am" src="https://user-images.githubusercontent.com/23080951/35746924-807c3b24-0816-11e8-93f0-ac594620399c.png">

3. Start downloading and packaging files into a zip file
<img width="968" alt="screen shot 2018-02-02 at 11 52 52 am" src="https://user-images.githubusercontent.com/23080951/35746933-85bc6e92-0816-11e8-9c6c-5d873c739c50.png">

4.
<img width="959" alt="screen shot 2018-02-02 at 11 53 33 am" src="https://user-images.githubusercontent.com/23080951/35746937-8ac49cfc-0816-11e8-9202-ddc27643a41c.png">
