### ISSUE TITLE
[BE] Return historical cases searched for the landing page

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#813]
###AC

1. New v2 endpoint is created that returns historical cases for the current user
2. It should have an expiration date (3 days is what we have currently)

**Comment by Sjones352** [comment]
**PASSED**

Validate Postman
1. Check the status of the files download
`GET <url>/api/v2/manifests/:manifest_id/files_downloads`

2. It should have an expiration date (3 days is what we have currently
<img width="958" alt="screen shot 2018-02-02 at 12 02 44 pm" src="https://user-images.githubusercontent.com/23080951/35746843-4bb13f0c-0816-11e8-86e9-81da05619693.png">
