### ISSUE TITLE
Caching 502 responses

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#814]
When the documents_controller fails due to an upstream dependency we return a 502. However, we provide the same caching policy that good responses get. We should not send that caching policy.

## AC
1) Verify 502 responses from the documents_controller are not cached.
2) Verify 502 responses from the records_controller are not cached.

**Comment by aroltsch** [comment]
@mdbenjam this is done, right?

**Comment by mdbenjam** [comment]
Whoops, yup! Closing it.
