### ISSUE TITLE
[BE] Return time estimate for files download

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#836]
### AC:
As part of the files_downloads response, return time estimate how long it is left to download the files

**Comment by Sjones352** [comment]
PASSED
Validate Postman

Start retrieving manifest
1. Returns  ```time_to_complete": "less than a minute```
2. Returns    ```       "seconds_left": 40```
<img width="975" alt="screen shot 2018-02-04 at 4 17 52 pm" src="https://user-images.githubusercontent.com/23080951/35782517-0a824834-09c7-11e8-883d-025c630e8dd8.png">
