### ISSUE TITLE
Feature Flag | Enable Exam Vendors Group 1 – LHI users on 2/5/2018

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#858]
As Project Manager, I would like the following feature flag enabled on Monday, 2/5/2018 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  VVA

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

**_LHI Group 1 - 30 Users_**
"VBAMIWADAMSL", "VbaMiwAddisW", "VbaMiwAgensJ", "vbamiwallenn", "VbaMiwBohnL", "vbamiwbrevit", "vbamiwbrowj2", "VbaMiwBurchD", "vbamiwburkwm", "vbamiwbussk", "VbaMiwCampS", "vbamiwcougha", "VbaMiwDahlB", "vbamiwerdmaa", "VbaMiwHendeS", "vbamiwhorstn", "VbaMiwKempA", "VbaMiwKlugL", "vbamiwmarsok", "VbaMiwMcDanN", "VBAMIWNearys", "VbaMiwNoelAn", "VbaMiwNogaT", "vbamiwparing", "VbaMiwRolffK", "VbaMiwRuegeD", "VBAMIWsinnit", "VbaMiwVueL", "VbaMiwVueS", "VbaMiwXiongP"

## Related Stories
**_PM Issues_**
IP | eFolder Express - VVA | Request Feature Flag enabled [#1781]( https://github.com/department-of-veterans-affairs/appeals-pm/issues/1781)

**Comment by mattwilcut** [comment]
shameful
