### ISSUE TITLE
Handle Aws::S3::Errors::NotFound errors in DownloadDocuments.fetch_from_s3

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#865]
This afternoon we started seeing `Aws::S3::Errors::NotFound` errors bubbling up from `DownloadDocuments.fetch_from_s3()` for download IDs 127893 and 127934. We killed the jobs that were spawning these errors for the time being, but the long term solution is to handle this properly. It appears as if the error is being thrown in caseflow-commons' [Caseflow::S3Service.fetch_file()](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/6be9e1e95b1a012af1fb5b7aa292ec7123281dc2/app/services/caseflow/s3_service.rb#L34) function. We catch the `Aws::S3::Errors::NotFound` error in the similar [Caseflow::S3Service.fetch_content()](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/6be9e1e95b1a012af1fb5b7aa292ec7123281dc2/app/services/caseflow/s3_service.rb#L50) function and should probably do something similar for `fetch_file()`.

Single example of error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/943/events/33196/

Whole set of errors: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/943/events/

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years and the errors haven't been seen since then.
