### ISSUE TITLE
Efolder does not use correct fonts in prod

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#866]
Can replicate in UAT. Main caseflow apps do not have this problem, but at a glance it does not appear as if efolder is handling these woff assets any differently than caseflow (however there clearly is some difference because caseflow does not have this problem...).

![image](https://user-images.githubusercontent.com/32683958/35890323-4bf6ad44-0b6d-11e8-86f1-c62566488906.png)

Console reveals that requests to assets failed:
![image](https://user-images.githubusercontent.com/32683958/35890358-7d83a754-0b6d-11e8-9f82-569e7b8fc325.png)

**Comment by mdbenjam** [comment]
@lowellrex This is fixed now right?

**Comment by lowellrex** [comment]
Correct, fixed this with the change in appeals-deployment #1326. Closing this issue now.
