### ISSUE TITLE
Add analytics to React frontend

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#890]
@mdbenjam [made the point](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/857#discussion_r166035505) that since we are early in the project and still have plenty of flexibility to change things, now is the right time to add analytics. To that end, we need to determine what we want to measure (http response errors? every network request? every validation error?) and how (how does Caseflow currently capture this information?).

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years.
