### ISSUE TITLE
Add an alert in the table when VVA files are not included

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#901]
As a user, I want to know if the files I downloaded contain all the files after a VVA outage. 

### Acceptance criteria 
1. Verify that the table shows the following text when it does not contain vva files: 
- VVA files were not included in this download. Please retry.

**Comment by lowellrex** [comment]
@Chingujo does [this PR](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/904) to display a more specific banner if either manifest source (VVA or VBMS) is unavailable satisfy this issue?

**Comment by Chingujo** [comment]
This would be for after the download occurred. For example, if the user qued a few vbms only downloads and the results finished in the table and the started new downloads when the service was up, they wouldn't know which had complete and incomplete files. 

We can either write a small note on the table or render an error (exclamation mark) and when they click on the link an error banner shows them there were no vva documents in this download.

**Comment by lowellrex** [comment]
Hmm alright. Is this different than #888?

**Comment by Chingujo** [comment]
That's the affected part of the app. This is part of a conversation in January to explore how we communicate to users regarding the lack of VVA files. The main concern here is that if a download did not contain vva files and sends the file, it is technically an incomplete FOIA requests. As not all files were included. 

Here are some options:

- [ ] We can render an error like in #888 when there are no VVA documents and when the user clicks on it they receive a banner saying that no VVA documents are contained here. Like the one in #666 only for VVA. 
- [ ] We can just add text to the table. 
 - For example this file does not contain VVA documents! Please view results for next steps or retry the download. 
- [ ] Both

**Comment by Chingujo** [comment]
Will post some mocks and AC and will put a feature definition on it when some mocks are ready

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
