### ISSUE TITLE
React Design Pass

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#928]
Looked through react update for eFolder Express. Things look pretty Ace and great job @lowellrex. 
Here are a few nits I found and happy to make these as individual issues. Lmk if I can help, provide better mocks, or if I am missing something =D. 

### Font
- I may be going crazy but the kerning seems different between our font and the ones we have on apps even though both is Source Sans. 

#### Current
<img width="590" alt="screen shot 2018-03-12 at 1 32 21 pm" src="https://user-images.githubusercontent.com/23316107/37299487-d25af18c-25f9-11e8-8996-b2925c4e5872.png">

#### Reference 
<img width="676" alt="screen shot 2018-03-12 at 1 29 52 pm" src="https://user-images.githubusercontent.com/23316107/37299445-b65a1a80-25f9-11e8-8c2d-5fc4727813ca.png">

### Banner
Creating consistent banner messages and quick notes on styling. 
#### Font of title
- Inspection shows Source Sans. However, title is a serif (probably Meriwether) 
<img width="134" alt="screen shot 2018-03-12 at 12 24 57 pm" src="https://user-images.githubusercontent.com/23316107/37297959-6f429ffe-25f5-11e8-998f-ee3a0765817d.png">

- No periods at the end of major alerts
<img width="1063" alt="screen shot 2018-03-12 at 12 21 03 pm" src="https://user-images.githubusercontent.com/23316107/37298019-9b95bd52-25f5-11e8-8831-5cc680121c5b.png">

- Spacing should be tighter between the lines (usually not a crazy big deal but this is about 2x more is what I see) 
<img width="994" alt="screen shot 2018-03-12 at 1 02 59 pm" src="https://user-images.githubusercontent.com/23316107/37298057-b5bd7242-25f5-11e8-9cb2-3671cdbfecec.png">

_Reference_ 
<img width="659" alt="screen shot 2018-03-12 at 1 03 35 pm" src="https://user-images.githubusercontent.com/23316107/37298092-ced679c2-25f5-11e8-896f-32c545585171.png">

### Header and veteran ID 
Looks like our fonts are bigger and the Veteran ID is bolded. Can we change styling to match certification and our other apps?
#### Current
<img width="1148" alt="screen shot 2018-03-12 at 1 14 47 pm" src="https://user-images.githubusercontent.com/23316107/37298699-61229ac6-25f7-11e8-9258-d593071547b6.png">

#### Reference mock
<img width="993" alt="screen shot 2018-03-12 at 1 10 42 pm" src="https://user-images.githubusercontent.com/23316107/37298650-3dbdac2e-25f7-11e8-8929-4d849bfe57a7.png">

### Size of the user name drop box
- Currently we have it in full caps and at a larger size. Please see reference for our other apps
#### Current
<img width="220" alt="screen shot 2018-03-12 at 1 09 33 pm" src="https://user-images.githubusercontent.com/23316107/37298783-b80bf3f0-25f7-11e8-94b3-10c9075eb992.png">

**Reference**
<img width="169" alt="screen shot 2018-03-12 at 1 09 26 pm" src="https://user-images.githubusercontent.com/23316107/37298794-c0f44c4c-25f7-11e8-9fd7-9f4817160188.png">

**Comment by lowellrex** [comment]
I've created PRs for the two non-typeface related issues here and will look into solving the typeface issue tomorrow (additional info on that issue exists in #866). @Chingujo let me know if I overlooked anything in this set of issues (other than those typeface hiccups which I will look at as part of #866).

**Comment by Chingujo** [comment]
These have been fixed and look good so closing =D Thanks Lowell
