### ISSUE TITLE
ImageConverterService throws exception if running when deploy shuts down instance

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#929]
This morning we saw [two](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1020/) [instances](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1021/) of the following error:
> **HTTPClient::KeepAliveDisconnected**
> HTTPClient::KeepAliveDisconnected: Connection reset by peer

The timing aligns nicely with two deploys of efolder:

 __ | Error occurred | Deploy completed
-- | -------------- | ----------------
First event | [15:38 UTC](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1020/) | [15:42](https://dsva.slack.com/archives/C7VNGMYUQ/p1520869320000382)
Second event | [16:28](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1021/) | [16:31](https://dsva.slack.com/archives/C7VNGMYUQ/p1520872273000761)

I imagine we need to gracefully shut down the ImageConverterService when we kill off instances during deploys, or capture this error and allow the job to be retried on one of the newly provisioned instances.

One reason why the imagemagick service might be getting killed before the rails server is because--according to [the deployment script](https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/roles/efolder-express/meta/main.yml#L66)--the imagemagick process was (probably) started after rails (which would have been kicked off through the roadrunner role on line 7 of that same yaml file). I supposed the instance is shutting down processes in reverse order, which would explain this order of shutting down imagemagick before rails.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
