### ISSUE TITLE
Download page shows different document order on each auto-refresh

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#93]

**Comment by orischwartz** [comment]
the `has_many` relationship between download and documents doesn't declare an order. see http://stackoverflow.com/questions/2205618/how-do-i-order-a-has-many-through-association-in-ruby-on-rails

**Comment by shanear** [comment]
fixed by f34b433768174f25ddaad408d2cb22b647ddc386
