### ISSUE TITLE
[Bug] Manifest sources are stuck in a pending state.

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#945]
I have noticed there is a manifest source that is stuck in a pending state. Theoretically, this should never happen because we of https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/jobs/v2/download_manifest_job.rb#L16. 

```
[#<ManifestSource id: 176, manifest_id: 88, status: "pending", name: "VBMS", fetched_at: "2018-03-12 18:01:24", created_at: "2018-03-08 17:38:43", updated_at: "2018-03-13 14:11:21">, #<ManifestSource id: 177, manifest_id: 88, status: "success", name: "VVA", fetched_at: "2018-03-18 21:45:32", created_at: "2018-03-08 17:38:43", updated_at: "2018-03-18 21:45:32">]
```

Because the status is pending, VBMS manifest was never attempted to fetch on 03/18 while VVA was successful. 

## AC:
1. Track down the issue 
2. Manifest sources can never be stuck in a pending state. 
3. Idea: can we have a timing mechanism on the duration of the job and if it lasts longer than a day (?) for example, set the manifest source to failed.

**Comment by lowellrex** [comment]
Ran the cronjob ([it worked!](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1057/)) and changed the two manifest sources' (IDs 176, 272) statuses to failed.
```
ManifestSource.where(status: 1).where("updated_at < ?", 1.day.ago).map { |m| m.update!(status: 3) }
```
