### ISSUE TITLE
|eFolder Express React| Blank home screen

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#948]
### Context

After we turned on React production this morning, the user was experiencing a blank home page. 
Currently gathering more context.

**Comment by Chingujo** [comment]
Currently follow up with the user to validate the issue and see if it is affecting all of our 6 users.

**Comment by Chingujo** [comment]
works on chrome

**Comment by lowellrex** [comment]
Do we know which version of IE this person was running?

**Comment by Chingujo** [comment]
The versions that are being used run from 10 to 11 @lowell. Most of the computers where the FOIA team work at the board have newer versions. May not be the case for remote. 

The user is away but will double check with other FOIA members. They should have similar machine set ups.
