### ISSUE TITLE
Do not display expired efolders in react app UI

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow-efolder#954]
We consider efolder fetches to be expired (in the web UI) if they are [more than 3 days old](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/a7854aaedb9e45dc7e60f999adda949ecc734918/app/models/manifest.rb#L22). In the efolder v1 html templates UI, we currently display a technical issues page (below). If we consider an efolder that is more than 3 days old to be expired we should have a similar solution for the efolder app. I *think* we currently handle the case when somebody searches for the file number of an expired efolder properly (that is, we create a new manifest--manifest sources?--instead of presenting the expired efolder).

I think we can do better than showing a technical difficulties message for v2. Maybe we could kick off a new manifest fetch for the given efolder file number and redirect the user to that URL. 

I drafted a test to confirm v2 does not handle this properly [here](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/926#issuecomment-374721902).

### Current (v1) UI behaviour
![image](https://user-images.githubusercontent.com/32683958/37680505-7d499592-2c5a-11e8-8315-ccb14babb186.png)

## Acceptance Criteria
* Do not display an expired efolder manifest (or download results) when accessing an expired efolder directly via URL
* Confirm that we do not present an expired efolder when searching for the file number of an expired efolder

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
