### ISSUE TITLE
Extend the manifest fetch timeout

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#959]
For larger files, it takes more than 20 seconds to fetch the manifest. We should extend this timer to 30 seconds to account for this use case. 

# Steps for reproduction 
1.) User searches for the file in the home page of the application
2.) The loading spinner occurs with the fetch manifest 
3.) Timeout error occurs before the manifest can be fetched 
4.) This has been reproduced with the user

# Solution
- Extend timeout to 90 seconds and follow up with user to see if it actually fetches. If not, identify other source of problem. 
- If loads, keep track of the time and adjust/keep the elongated timeout

**Comment by lowellrex** [comment]
Excellent! Closed!
