### ISSUE TITLE
Add a status IO link to the footer of the application

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#968]
As a user I want to be able to quickly see the status of eFolder Express without having to wait for support responses so i can play my workflow more effectively. 

### Acceptance Criteria 
- [ ] Verify that on the footer of the application there is a link to our Status.io to the left of the Send Feedback link
- [ ] Verify this link sends the user to our status.io page

I know this is in the footer of our applications now. May be there but did not see it in Demo so making a ticket. Feel free to close if there.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
