### ISSUE TITLE
Reduce the time of the visibility timeout and lock for the package files job

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#975]
Since deploys kill all running jobs, our package files job poses a problem. It can take a long time to run, so we've set a long visibility timeout. However, this means that if the job is killed it won't be retried for 12 hours. This is a really bad user experience. We could retry more often, but having multiple of these jobs running seems wasteful (but maybe not really that bad). There are two possible options for us.

1) Reduce the visibility timeout to only a few hours.
1) Spin up lots of jobs to cache the files in S3, and then run one final job to build the zip file. This allows us to restart any one of the jobs which should be quick rather than one long job which is slow.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
