### ISSUE TITLE
Table broken on file retrieval page 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#989]
### Context
In production - the file retrieval page shows a skewed table. 

### Priority
High - since it is a production bug

### Steps of reproduction
- Log into production via safari
- Enter Veteran ID
- Searches the file and see the following table. 

### Screen shoot 
<img width="977" alt="screen shot 2018-04-18 at 10 48 43 am" src="https://user-images.githubusercontent.com/23316107/38939617-55b023ea-42f6-11e8-8b81-63a4d3e2b11c.png">

**Comment by lowellrex** [comment]
The broken-ness here is the way the columns are displayed, is that correct? Or is it that the document types should be different?

If it is the former, can we get information on what browser/OS this person is running?

**Comment by Chingujo** [comment]
The brokeness is in the display of the UI. This seems to be happening only in Safari. So going to de-escalate in favor of the stalled downloads and history showing up. 

DOn't know any users who are using safari other than us or will be super super super small

**Comment by mdbenjam** [comment]
If this only happens in Safari I think this is low priority.

**Comment by Chingujo** [comment]
Great! Will double check in product today and de-escalate as necessary and provide some updates.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
