### ISSUE TITLE
Downloads are stalling in proudction

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#992]
## Context
A few tickets today showed that downloads are stalling and are stuck in progress. This may be due to the VVA upgrade, the old API points, or something with the manifest request. We would have to either clear the cache or re-start the request for the affected appeals - less a larger issue. 

## 
Priority - highest . Production issue and could point to a larger issue where files are not downloading. 

## Reproduction
- Search affected ID's in production
- Download is stuck in progress
- I can provide the veteran names

**Comment by lowellrex** [comment]
Do we have any non-PII IDs that we can use to find these downloads (CSS IDs, manifest IDs, etc.)?

**Comment by Chingujo** [comment]
We set the files to fail and tried it just now in production and unfortunately this is the error now T_T:

<img width="1049" alt="screen shot 2018-04-18 at 6 55 20 pm" src="https://user-images.githubusercontent.com/23316107/38962206-365dad2a-433a-11e8-9dec-fc2691eab79d.png">

**Comment by lowellrex** [comment]
I'm pretty sure we expected to see that error (this is the result of setting the download to failed). What happens when we click on "Retry download"?

**Comment by Chingujo** [comment]
## Context
Duh T_T...checking in prod retry download renders a complete file counter but no real progress. 

Also, there are some weird redirect errors @lowellrex. Each of the three appeal id's are defaulting to the same page regardless of the Veteran ID. See below:  

## Reproduction
1.) Search first veteran ID let's say Veteran A
2.) Click retry download
3.) Defaults to the below screen shot
4. Search another veteran ID, let's say Veteran B. Veteran B's error page flashes for a second and re-directs to the below screen shot

<img width="950" alt="screen shot 2018-04-19 at 8 02 22 am" src="https://user-images.githubusercontent.com/23316107/38990472-65641c9e-43a8-11e8-8b84-f07780e69044.png">



For one of them, when you type in a new Veteran ID and click search, the other Veteran does appear as should for a brief second with the above error but then defaults to the picture above and

**Comment by Chingujo** [comment]
All affected manifest ID's. Not sure why they are directing to each other when you try to download. 

- 16243
- 18077
- 16539
- 16529

**Comment by lowellrex** [comment]
Hard to disentangle these issues from the VVA connection issues, so I'm going to go ahead and hold off on further investigation until we reconnect to VVA. 

I did some digging into the most recent failing download (18077) which leads me to believe that we were in the middle of  `ZipfileCreator.process()` (and the loop over each record in `ZipfileCreator.write_to_tempfile()` to be precise) when we stopped working on these records. We [deployed efolder at 12:32 eastern time yesterday](https://dsva.slack.com/archives/C7VNGMYUQ/p1524069177000176) which coincides very neatly with when these records stopped having their statuses updated (-4 hour time difference with UTC). I suspect we aren't restarting jobs (specifically [the PackageFilesJob](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/08d037bee67da8722361748ca1c4acd413de0540/app/jobs/v2/package_files_job.rb)) properly when we kill them when we spin up (and tear down) AWS instances when we deploy new code.

I think the fix might be to add back in some of the cronjobs we removed in the PR where we [changed from Sidekiq to Shoryuken](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/961), or maybe we could send some signal to pause running jobs when we deploy (and restart on a new box when the deploy finishes). Will chat with @mdbenjam and @aroltsch to see what they think.

```
psql> select status, substring(updated_at::text, 12, 5), count(*) from records where manifest_source_id in (select id from manifest_sources where manifest_id = 18077) group by 1, 2 order by 2;

 status | substring | count 
--------+-----------+-------
      0 | 15:26     |   305
      1 | 16:22     |    13
      1 | 16:23     |    30
      1 | 16:24     |    30
      1 | 16:25     |    31
      1 | 16:26     |    33
      1 | 16:27     |    39
      1 | 16:28     |    38
      1 | 16:29     |    39
      1 | 16:30     |    32
      1 | 16:31     |     7
```

**Comment by lowellrex** [comment]
I may have been to hasty to point the finger in this case. I'm not so sure that PR caused these issues (rather it just got rid of some alerting around when they happen), but I think we need something similar to [what we had for stalled downloads](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/jobs/restart_stalled_downloads_job.rb) now that we've changed over to manifests.

**Comment by lowellrex** [comment]
Looks like it should be resolved by this PR https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/986

**Comment by lowellrex** [comment]
Will set these manifests files_fetched_statuses back to failed once that PR is merged

**Comment by Chingujo** [comment]
We reached out to the users and haven't heard back. Will check on these appeal ID's and see if this problem persists today. If it does will close this.

**Comment by alisan16** [comment]
This is out of date. Doesn't seem like it's an issue anymore. Closing
