### ISSUE TITLE
Redis Semaphores keys are not being deleted

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow-efolder#996]
I noticed that we hit the Redis OOM exception this weekend.  Taking a look at the keys, we have several `SEMAPHORE` cache entries that were added this week.  I _think_ correlated with the v2 api roll out.   

Taking a look at the `redis-semaphore` implementation, I believe we may need to set a hard expiration for the semaphore lock, or call the delete! function when we unlock so that these semaphore keys get deleted. 
https://github.com/dv/redis-semaphore#expiration

**Comment by sunil-sadasivan** [comment]
For now, I have a way to delete these semaphore entries:

```
redis-cli -u <REDIS_URI> --scan --pattern "SEMAPHORE:*" | grep "SEMAPHORE:record_[0-9]\+" | head -n 10000000 | xargs redis-cli -u <REDIS_URI> DEL
```

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
